package main

const codeTemplate = `// Code generated by query-gen. DO NOT EDIT.
package {{.Package}}

import (
	"context"
	"database/sql"
	"errors"
	"fmt"
	"strings"

	"{{.ModelPkg}}"
)

{{if .HasPK -}}
// Insert{{.Name}} inserts a new {{.Name}} record into the {{.Table}} table.
func Insert{{.Name}}(ctx context.Context, db DBTX, m *{{.ModelPkgAlias}}.{{.Name}}) error {
	if db == nil {
		return errors.New("insert{{.Name}}: db is nil")
	}
	if m == nil {
		return errors.New("insert{{.Name}}: m is nil")
	}

	fields := []struct {
		col        string
		val        any
		omitIfZero bool
	}{
		{{range .WritableFields -}}
		{col: "{{.Column}}", val: m.{{.Name}}, omitIfZero: {{or .HasDefault (and .IsTimestamp (not .Nullable))}}},
		{{end -}}
	}

	cols := make([]string, 0, len(fields))
	args := make([]any, 0, len(fields))
	placeholders := make([]string, 0, len(fields))

	for _, f := range fields {
		if f.omitIfZero && IsZero(f.val) {
			continue
		}
		cols = append(cols, f.col)
		args = append(args, f.val)
		placeholders = append(placeholders, fmt.Sprintf("$%d", len(args)))
	}

	var query string
	if len(cols) == 0 {
		query = "INSERT INTO {{.Table}} DEFAULT VALUES RETURNING {{.AllColumns ""}}"
	} else {
		query = fmt.Sprintf("INSERT INTO {{.Table}} (%s) VALUES (%s) RETURNING {{.AllColumns ""}}",
			strings.Join(cols, ", "), strings.Join(placeholders, ", "))
	}

	if err := db.QueryRowContext(ctx, query, args...).
		Scan({{.AllScanArgs "m"}}); err != nil {
		return fmt.Errorf("insert{{.Name}}: %w", err)
	}
	return nil
}

// ============ Bulk insert ========================

// Insert{{.NamePlural}} inserts multiple {{.Name}} records into {{.Table}} in efficient parameter-bounded batches.
// Automatically populates database-generated values (e.g., auto-increment primary keys, default values) back into input structs via RETURNING.
func Insert{{.NamePlural}}(ctx context.Context, db DBTX, models []*{{.ModelPkgAlias}}.{{.Name}}) error {
	if db == nil {
		return errors.New("insert{{.NamePlural}}: db is nil")
	}
	if len(models) == 0 {
		return nil
	}
		
	const batchSize = {{.BulkInsertBatchSize}}
	for i := 0; i < len(models); i += batchSize {
		end := min((i + batchSize), len(models))
		batch := models[i:end]
		if err := insert{{.NamePlural}}Batch(ctx, db, batch); err != nil {
			return fmt.Errorf("insert{{.NamePlural}}: batch [%d:%d]: %w", i, end, err)
		}
	}
	return nil
}

func insert{{.NamePlural}}Batch(ctx context.Context, db DBTX, batch []*{{.ModelPkgAlias}}.{{.Name}}) error {
	if len(batch) == 0 {
		return nil
	}

	{{$writable := .WritableFields -}}
	{{$numCols := len $writable -}}
	{{if eq $numCols 0 -}}
	for i, m := range batch {
		if m == nil {
			return fmt.Errorf("insert{{$.NamePlural}}Batch: model at index %d is nil", i)
		}
		const query = "INSERT INTO {{$.Table}} DEFAULT VALUES RETURNING {{$.AllColumns ""}}"
		if err := db.QueryRowContext(ctx, query).Scan({{$.AllScanArgs "m"}}); err != nil {
			return fmt.Errorf("insert{{$.NamePlural}}Batch row %d: %w", i, err)
		}
	}
	return nil
	{{else -}}
	args := make([]any, 0, len(batch)*{{$numCols}})
	var sb strings.Builder
	sb.Grow(128 + len(batch)*{{$numCols}}*8)
	sb.WriteString("INSERT INTO {{.Table}} ({{.InsertColumns}}) VALUES ")

	paramIdx := 1
	for i, m := range batch {
		if m == nil {
			return fmt.Errorf("model at index %d is nil", i)
		}
		if i > 0 {
			sb.WriteString(", ")
		}
		sb.WriteByte('(')
		{{range $j, $f := $writable -}}
		{{if gt $j 0}}sb.WriteString(", "){{end}}
		sb.WriteString(getPlaceholder(paramIdx))
		paramIdx++
		args = append(args, m.{{$f.Name}})
		{{end -}}
		sb.WriteByte(')')
	}

	sb.WriteString(" RETURNING {{.AllColumns ""}}")
	rows, err := db.QueryContext(ctx, sb.String(), args...)
	if err != nil {
		return fmt.Errorf("executing bulk insert: %w", err)
	}
	defer rows.Close()

	idx := 0
	for rows.Next() {
		if idx >= len(batch) {
			return errors.New("unexpected extra row returned from insert")
		}
		m := batch[idx]
		if err := rows.Scan({{.AllScanArgs "m"}}); err != nil {
			return fmt.Errorf("scanning row %d: %w", idx, err)
		}
		idx++
	}

	if err := rows.Err(); err != nil {
		return fmt.Errorf("iterating bulk insert rows: %w", err)
	}

	if idx < len(batch) {
		return fmt.Errorf("expected %d inserted rows, got %d", len(batch), idx)
	}

	return nil
	{{end -}}
}

// Get{{.Name}}ByID retrieves a single {{.Name}} record from {{.Table}} by its primary key.
func Get{{.Name}}ByID(ctx context.Context, db DBTX, {{.PKParams .ModelPkgAlias}}, opts ...QueryOption) (*{{.ModelPkgAlias}}.{{.Name}}, error) {
	if db == nil {
		return nil, errors.New("get{{.Name}}ByID: db is nil")
	}
	{{- if or .Relations .HasDeletedAt}}

	cfg := parseQueryOptions(opts...)
	{{- end}}
	{{- if .Relations}}

	if cfg.PreloadAssociations {
		return get{{.Name}}ByIDWithRelations(ctx, db, {{.PKArgs ""}}, cfg)
	}
	{{- end}}
	{{- if .HasDeletedAt}}

	query := ` + "`" + `
		SELECT {{.AllColumns ""}}
		FROM {{.Table}}
		WHERE {{.PKWhereClause "" 1}}
	` + "`" + `
	if !cfg.IncludeDeleted {
		query += " AND {{.DeletedAtField.Column}} IS NULL"
	}
	{{- else}}

	const query = ` + "`" + `
		SELECT {{.AllColumns ""}}
		FROM {{.Table}}
		WHERE {{.PKWhereClause "" 1}}
	` + "`" + `
	{{- end}}

	row := db.QueryRowContext(ctx, query, {{.PKArgs ""}})
	var m {{.ModelPkgAlias}}.{{.Name}}
	if err := row.Scan({{.AllScanArgs "m"}}); err != nil {
		return nil, fmt.Errorf("get{{.Name}}ByID(%v): %w", {{if eq (len .PK) 1}}id{{else}}fmt.Sprint({{.PKArgs ""}}){{end}}, err)
	}

	return &m, nil
}
{{end -}}

// Get{{.Name}} retrieves a single {{.Name}} record matching mandatory query options/where clause.
// Returns sql.ErrNoRows if no matching record is found.
func Get{{.Name}}(ctx context.Context, db DBTX, opts ...QueryOption) (*{{.ModelPkgAlias}}.{{.Name}}, error) {
	if db == nil {
		return nil, errors.New("get{{.Name}}: db is nil")
	}

	cfg := parseQueryOptions(opts...)
	if cfg.Where == "" {
		return nil, errors.New("get{{.Name}}: query options/where clause required to prevent returning arbitrary row")
	}

	pOpts := append([]QueryOption(nil), opts...)
	pOpts = append(pOpts, Limit(1))

	items, err := FetchAll{{.NamePlural}}(ctx, db, pOpts...)
	if err != nil {
		return nil, fmt.Errorf("get{{.Name}}: %w", err)
	}
	if len(items) == 0 {
		return nil, fmt.Errorf("get{{.Name}}: %w", sql.ErrNoRows)
	}
	return items[0], nil
}

{{if .HasPK -}}
// Update{{.Name}}Columns updates only the specified updatable columns/fields for an existing {{.Name}} record in {{.Table}}.
// Column arguments can be database column names (e.g. "email") or Go field names (e.g. "Email").
func Update{{.Name}}Columns(ctx context.Context, db DBTX, m *{{.ModelPkgAlias}}.{{.Name}}, cols ...string) error {
	if db == nil {
		return errors.New("update{{.Name}}Columns: db is nil")
	}
	if m == nil {
		return errors.New("update{{.Name}}Columns: m is nil")
	}
	if len(cols) == 0 {
		return errors.New("update{{.Name}}Columns: at least one column/field must be specified")
	}

	allowedColumns := []string{
		{{range .UpdatableFields -}}
		"{{.Column}}", "{{.Name}}",
		{{end -}}
	}

	setClauses := make([]string, 0, len(cols))
	args := make([]any, 0, len(cols)+{{len .PK}})

	for _, col := range cols {
		if !slices.Contains(allowedColumns, col) {
			return fmt.Errorf("update{{.Name}}Columns: column or field %q is not updatable", col)
		}

		var dbCol string
		var val any

		switch col {
		{{range .UpdatableFields -}}
		case "{{.Column}}", "{{.Name}}":
			dbCol = "{{.Column}}"
			val = m.{{.Name}}
		{{end -}}
		}

		args = append(args, val)
		setClauses = append(setClauses, fmt.Sprintf("%s = $%d", dbCol, len(args)))
	}

	pkClauses := make([]string, 0, {{len .PK}})
	{{range $i, $pk := .PK -}}
	pkClauses = append(pkClauses, fmt.Sprintf("%s = $%d", "{{$pk.Column}}", len(args)+{{$i}}+1))
	{{end -}}

	query := fmt.Sprintf("UPDATE {{.Table}} SET %s WHERE %s",
		strings.Join(setClauses, ", "), strings.Join(pkClauses, " AND "))

	args = append(args, {{.PKArgs "m."}})

	res, err := db.ExecContext(ctx, query, args...)
	if err != nil {
		return fmt.Errorf("update{{.Name}}Columns(%v): %w", fmt.Sprint({{.PKArgs "m."}}), err)
	}

	n, err := res.RowsAffected()
	if err != nil {
		return fmt.Errorf("detect rows affected: %w", err)
	}
	if n == 0 {
		return fmt.Errorf("update{{.Name}}Columns(%v): %w", fmt.Sprint({{.PKArgs "m."}}), sql.ErrNoRows)
	}
	return nil
}

// Exists{{.Name}}ByID reports whether a {{.Name}} record with the given primary key exists.
func Exists{{.Name}}ByID(ctx context.Context, db DBTX, {{.PKParams .ModelPkgAlias}}, opts ...QueryOption) (bool, error) {
	if db == nil {
		return false, errors.New("exists{{.Name}}ByID: db is nil")
	}
	{{- if .HasDeletedAt}}

	cfg := parseQueryOptions(opts...)
	query := ` + "`" + `SELECT EXISTS(SELECT 1 FROM {{.Table}} WHERE {{.PKWhereClause "" 1}}` + "`" + `
	if !cfg.IncludeDeleted {
		query += " AND {{.DeletedAtField.Column}} IS NULL"
	}
	query += ")"
	{{- else}}

	const query = ` + "`" + `SELECT EXISTS(SELECT 1 FROM {{.Table}} WHERE {{.PKWhereClause "" 1}})` + "`" + `
	{{- end}}

	var exists bool
	if err := db.QueryRowContext(ctx, query, {{.PKArgs ""}}).Scan(&exists); err != nil {
		return false, fmt.Errorf("exists{{.Name}}ByID(%v): %w", {{if eq (len .PK) 1}}id{{else}}fmt.Sprint({{.PKArgs ""}}){{end}}, err)
	}
	return exists, nil
}
{{end -}}

// Exists{{.Name}} reports whether a {{.Name}} record matching the mandatory query options/where clause exists.
func Exists{{.Name}}(ctx context.Context, db DBTX, opts ...QueryOption) (bool, error) {
	if db == nil {
		return false, errors.New("exists{{.Name}}: db is nil")
	}

	cfg := parseQueryOptions(opts...)
	if cfg.Where == "" {
		return false, errors.New("exists{{.Name}}: query options/where clause required")
	}

	var whereClause string
	if cfg.Where != "" {
		whereClause = " WHERE " + cfg.Where
	}
	{{- if .HasDeletedAt}}

	if !cfg.IncludeDeleted {
		if whereClause != "" {
			whereClause += " AND {{.DeletedAtField.Column}} IS NULL"
		} else {
			whereClause = " WHERE {{.DeletedAtField.Column}} IS NULL"
		}
	}
	{{- end}}

	tableName := "{{.Table}}"
	if cfg.Table != "" {
		tableName = cfg.Table
	}

	query := "SELECT EXISTS(SELECT 1 FROM " + tableName + whereClause + ")"

	var exists bool
	if err := db.QueryRowContext(ctx, query, cfg.Args...).Scan(&exists); err != nil {
		return false, fmt.Errorf("exists{{.Name}}: %w", err)
	}
	return exists, nil
}

// Count{{.NamePlural}} returns total records matching optional filter criteria.
func Count{{.NamePlural}}(ctx context.Context, db DBTX, opts ...QueryOption) (int64, error) {
	if db == nil {
		return 0, errors.New("count{{.NamePlural}}: db is nil")
	}

	cfg := parseQueryOptions(opts...)

	var whereClause string
	if cfg.Where != "" {
		whereClause = " WHERE " + cfg.Where
	}
	{{- if .HasDeletedAt}}

	if !cfg.IncludeDeleted {
		if whereClause != "" {
			whereClause += " AND {{.DeletedAtField.Column}} IS NULL"
		} else {
			whereClause = " WHERE {{.DeletedAtField.Column}} IS NULL"
		}
	}
	{{- end}}

	tableName := "{{.Table}}"
	if cfg.Table != "" {
		tableName = cfg.Table
	}

	query := "SELECT COUNT(*) FROM " + tableName + whereClause

	var count int64
	if err := db.QueryRowContext(ctx, query, cfg.Args...).Scan(&count); err != nil {
		return 0, fmt.Errorf("count{{.NamePlural}}: %w", err)
	}
	return count, nil
}

// FetchAll{{.NamePlural}} retrieves a filtered/paginated slice of {{.Name}} records.
func FetchAll{{.NamePlural}}(ctx context.Context, db DBTX, opts ...QueryOption) ([]*{{.ModelPkgAlias}}.{{.Name}}, error) {
	if db == nil {
		return nil, errors.New("fetchAll{{.NamePlural}}: db is nil")
	}
	{{- if and .Relations .HasPK}}

	clause, args, cfg := applyQueryOptions("{{.PKColumns ""}}", {{if .HasDeletedAt}}"{{.DeletedAtField.Column}}"{{else}}""{{end}}, opts...)
	if cfg.PreloadAssociations {
		return fetchAll{{.NamePlural}}WithRelations(ctx, db, clause, args, cfg)
	}
	{{- else}}

	clause, args, cfg := applyQueryOptions({{if .HasPK}}"{{.PKColumns ""}}"{{else}}""{{end}}, {{if .HasDeletedAt}}"{{.DeletedAtField.Column}}"{{else}}""{{end}}, opts...)
	{{- end}}

	tableName := "{{.Table}}"
	if cfg.Table != "" {
		tableName = cfg.Table
	}

	query := "SELECT {{.AllColumns ""}} FROM " + tableName + clause

	rows, err := db.QueryContext(ctx, query, args...)
	if err != nil {
		return nil, fmt.Errorf("fetchAll{{.NamePlural}}: %w", err)
	}
	defer rows.Close()

	items := make([]*{{.ModelPkgAlias}}.{{.Name}}, 0, 16)
	for rows.Next() {
		var m {{.ModelPkgAlias}}.{{.Name}}
		if err := rows.Scan({{.AllScanArgs "m"}}); err != nil {
			return nil, fmt.Errorf("fetchAll{{.NamePlural}}: scanning row: %w", err)
		}
		items = append(items, &m)
	}

	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("fetchAll{{.NamePlural}}: iterating rows: %w", err)
	}

	return items, nil
}

{{if .HasPK -}}
// Update{{.Name}} updates an existing {{.Name}} record in {{.Table}}.
func Update{{.Name}}(ctx context.Context, db DBTX, m *{{.ModelPkgAlias}}.{{.Name}}) error {
	if db == nil {
		return errors.New("update{{.Name}}: db is nil")
	}
	if m == nil {
		return errors.New("update{{.Name}}: m is nil")
	}

	const query = ` + "`" + `
		UPDATE {{.Table}}
		SET {{.UpdateSetClause}}
		WHERE {{.PKWhereClause "" .UpdatePKPlaceholderStartIdx}}
	` + "`" + `

	res, err := db.ExecContext(ctx, query, {{.UpdatableScanArgs "m"}}, {{.PKArgs "m."}})
	if err != nil {
		return fmt.Errorf("update{{.Name}}(%v): %w", fmt.Sprint({{.PKArgs "m."}}), err)
	}

	n, err := res.RowsAffected()
	if err != nil {
		return fmt.Errorf("detect rows affected: %w", err)
	}
	if n == 0 {
		return fmt.Errorf("update{{.Name}}(%v): %w", fmt.Sprint({{.PKArgs "m."}}), sql.ErrNoRows)
	}
	return nil
}

// Delete{{.Name}} deletes the {{.Name}} record identified by primary key from {{.Table}}.
func Delete{{.Name}}(ctx context.Context, db DBTX, {{.PKParams .ModelPkgAlias}}, opts ...QueryOption) error {
	if db == nil {
		return errors.New("delete{{.Name}}: db is nil")
	}
	{{- if .HasDeletedAt}}

	cfg := parseQueryOptions(opts...)
	if !cfg.HardDelete {
		const query = ` + "`" + `UPDATE {{.Table}} SET {{.DeletedAtField.Column}} = CURRENT_TIMESTAMP WHERE {{.PKWhereClause "" 1}} AND {{.DeletedAtField.Column}} IS NULL` + "`" + `
		res, err := db.ExecContext(ctx, query, {{.PKArgs ""}})
		if err != nil {
			return fmt.Errorf("delete{{.Name}}(%v): %w", {{if eq (len .PK) 1}}id{{else}}fmt.Sprint({{.PKArgs ""}}){{end}}, err)
		}
		n, err := res.RowsAffected()
		if err != nil {
			return fmt.Errorf("detect rows affected: %w", err)
		}
		if n == 0 {
			return fmt.Errorf("delete{{.Name}}(%v): %w", {{if eq (len .PK) 1}}id{{else}}fmt.Sprint({{.PKArgs ""}}){{end}}, sql.ErrNoRows)
		}
		return nil
	}
	{{- end}}

	const query = ` + "`" + `DELETE FROM {{.Table}} WHERE {{.PKWhereClause "" 1}}` + "`" + `

	res, err := db.ExecContext(ctx, query, {{.PKArgs ""}})
	if err != nil {
		return fmt.Errorf("delete{{.Name}}(%v): %w", {{if eq (len .PK) 1}}id{{else}}fmt.Sprint({{.PKArgs ""}}){{end}}, err)
	}

	n, err := res.RowsAffected()
	if err != nil {
		return fmt.Errorf("detect rows affected: %w", err)
	}
	if n == 0 {
		return fmt.Errorf("delete{{.Name}}(%v): %w", {{if eq (len .PK) 1}}id{{else}}fmt.Sprint({{.PKArgs ""}}){{end}}, sql.ErrNoRows)
	}
	return nil
}

// Delete{{.NamePlural}} deletes records from {{.Table}} matching the provided query options and returns the number of affected rows.
func Delete{{.NamePlural}}(ctx context.Context, db DBTX, opts ...QueryOption) (int64, error) {
	if db == nil {
		return 0, errors.New("delete{{.NamePlural}}: db is nil")
	}

	cfg := parseQueryOptions(opts...)
	if cfg.Where == "" {
		return 0, errors.New("delete{{.NamePlural}}: query options/where clause required to prevent accidental bulk deletion")
	}
	{{- if .HasDeletedAt}}

	clause, args, cfg := applyQueryOptions("", "{{.DeletedAtField.Column}}", opts...)
	{{- else}}

	clause, args, cfg := applyQueryOptions("", "", opts...)
	{{- end}}

	tableName := "{{.Table}}"
	if cfg.Table != "" {
		tableName = cfg.Table
	}

	var query string
	{{- if .HasDeletedAt}}
	if !cfg.HardDelete {
		query = "UPDATE " + tableName + " SET {{.DeletedAtField.Column}} = CURRENT_TIMESTAMP" + clause
	} else {
		query = "DELETE FROM " + tableName + clause
	}
	{{- else}}
	query = "DELETE FROM " + tableName + clause
	{{- end}}

	res, err := db.ExecContext(ctx, query, args...)
	if err != nil {
		return 0, fmt.Errorf("delete{{.NamePlural}}: %w", err)
	}

	n, err := res.RowsAffected()
	if err != nil {
		return 0, fmt.Errorf("delete{{.NamePlural}}: detecting rows affected: %w", err)
	}

	return n, nil
}
{{end -}}

// ================= FETCHING RELATIONS ===============================
{{- if and .Relations .HasPK}}
{{- if .UseJoinStrategy}}
func get{{.Name}}ByIDWithRelations(ctx context.Context, db DBTX, {{.PKParams .ModelPkgAlias}}, cfg QueryOptions) (*{{.ModelPkgAlias}}.{{.Name}}, error) {
	{{- if .HasDeletedAt}}
	query := ` + "`" + `
		SELECT 
			{{.AllColumns "p"}}{{.AllRelationColumns}}
		FROM {{.Table}} p
		{{.AllRelationJoins "p"}}
		WHERE {{.PKWhereClause "p" 1}}
	` + "`" + `
	if !cfg.IncludeDeleted {
		query += " AND p.{{.DeletedAtField.Column}} IS NULL"
	}
	{{- else}}
	const query = ` + "`" + `
		SELECT 
			{{.AllColumns "p"}}{{.AllRelationColumns}}
		FROM {{.Table}} p
		{{.AllRelationJoins "p"}}
		WHERE {{.PKWhereClause "p" 1}}
	` + "`" + `
	{{- end}}

	rows, err := db.QueryContext(ctx, query, {{.PKArgs ""}})
	if err != nil {
		return nil, fmt.Errorf("get{{.Name}}ByIDWithRelations(%v): %w", {{if eq (len .PK) 1}}id{{else}}fmt.Sprint({{.PKArgs ""}}){{end}}, err)
	}
	defer rows.Close()

	var parent *{{.ModelPkgAlias}}.{{.Name}}
	var p {{.ModelPkgAlias}}.{{.Name}}

	{{range $idx, $rel := .Relations -}}
	{{$target := index $.AllKnownModels $rel.TargetModel -}}
	seen_{{$rel.FieldName}} := make(map[{{$target.PKType $.ModelPkgAlias}}]struct{}, 4)
	var c{{$idx}} {{$.ModelPkgAlias}}.{{$target.Name}}
	{{end -}}

	scanArgs := []any{
		{{.AllScanArgs "p"}},
		{{range $idx, $rel := .Relations -}}
		{{$target := index $.AllKnownModels $rel.TargetModel -}}
		{{range $target.SelectableFields -}}
		ScanNullable(&c{{$idx}}.{{.Name}}),
		{{end -}}
		{{end -}}
	}

	for rows.Next() {
		if err := rows.Scan(scanArgs...); err != nil {
			return nil, fmt.Errorf("get{{.Name}}ByIDWithRelations(%v): scanning row: %w", {{if eq (len .PK) 1}}id{{else}}fmt.Sprint({{.PKArgs ""}}){{end}}, err)
		}

		if parent == nil {
			parent = &p
		}

		{{range $idx, $rel := .Relations -}}
		{{$target := index $.AllKnownModels $rel.TargetModel -}}
		if !({{$target.PKZeroCheck (print "c" $idx)}}) {
			rPk{{$idx}} := {{$target.PKValue (print "c" $idx) $.ModelPkgAlias}}
			if _, ok := seen_{{$rel.FieldName}}[rPk{{$idx}}]; !ok {
				seen_{{$rel.FieldName}}[rPk{{$idx}}] = struct{}{}
				child := c{{$idx}}
				{{if or (eq $rel.Type "HasMany") (eq $rel.Type "ManyToMany") -}}
				{{if $rel.IsPointer -}}
				parent.{{$rel.FieldName}} = append(parent.{{$rel.FieldName}}, &child)
				{{else -}}
				parent.{{$rel.FieldName}} = append(parent.{{$rel.FieldName}}, child)
				{{end -}}
				{{else if eq $rel.Type "BelongsTo" -}}
				{{if $rel.IsPointer -}}
				parent.{{$rel.FieldName}} = &child
				{{else -}}
				parent.{{$rel.FieldName}} = child
				{{end -}}
				{{end -}}
			}
		}
		{{end -}}
	}

	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("get{{.Name}}ByIDWithRelations(%v): iterating rows: %w", {{if eq (len .PK) 1}}id{{else}}fmt.Sprint({{.PKArgs ""}}){{end}}, err)
	}
	if parent == nil {
		return nil, fmt.Errorf("get{{.Name}}ByIDWithRelations(%v): %w", {{if eq (len .PK) 1}}id{{else}}fmt.Sprint({{.PKArgs ""}}){{end}}, sql.ErrNoRows)
	}

	return parent, nil
}

func fetchAll{{.NamePlural}}WithRelations(ctx context.Context, db DBTX, clause string, args []any, cfg QueryOptions) ([]*{{.ModelPkgAlias}}.{{.Name}}, error) {
	query := ` + "`" + `
		WITH p AS (
			SELECT {{.AllColumns "p"}}
			FROM {{.Table}} p
	` + "`" + ` + clause + ` + "`" + `
		)
		SELECT 
			{{.AllColumns "p"}}{{.AllRelationColumns}}
		FROM p
		{{.AllRelationJoins "p"}}
		ORDER BY {{.PKColumns "p"}} ASC
	` + "`" + `

	rows, err := db.QueryContext(ctx, query, args...)
	if err != nil {
		return nil, fmt.Errorf("fetchAll{{.NamePlural}}WithRelations: %w", err)
	}
	defer rows.Close()

	items := make([]*{{.ModelPkgAlias}}.{{.Name}}, 0, 16)
	itemsMap := make(map[{{.PKType .ModelPkgAlias}}]*{{.ModelPkgAlias}}.{{.Name}}, 16)

	{{range $idx, $rel := .Relations -}}
	{{$target := index $.AllKnownModels $rel.TargetModel -}}
	seen_{{$rel.FieldName}} := make(map[seenKey[{{$.PKType $.ModelPkgAlias}}, {{$target.PKType $.ModelPkgAlias}}]]struct{}, 64)
	{{end -}}

	for rows.Next() {
		var p {{.ModelPkgAlias}}.{{.Name}}
		{{range $idx, $rel := .Relations -}}
		{{$target := index $.AllKnownModels $rel.TargetModel -}}
		var c{{$idx}} {{$.ModelPkgAlias}}.{{$target.Name}}
		{{end -}}

		scanArgs := []any{
			{{.AllScanArgs "p"}},
			{{range $idx, $rel := .Relations -}}
			{{$target := index $.AllKnownModels $rel.TargetModel -}}
			{{range $target.SelectableFields -}}
			ScanNullable(&c{{$idx}}.{{.Name}}),
			{{end -}}
			{{end -}}
		}

		if err := rows.Scan(scanArgs...); err != nil {
			return nil, fmt.Errorf("fetchAll{{.NamePlural}}WithRelations: scanning row: %w", err)
		}

		pPK := {{.PKValue "p" .ModelPkgAlias}}
		parent, exists := itemsMap[pPK]
		if !exists {
			parent = &p
			itemsMap[pPK] = parent
			items = append(items, parent)
		}

		{{range $idx, $rel := .Relations -}}
		{{$target := index $.AllKnownModels $rel.TargetModel -}}
		if !({{$target.PKZeroCheck (print "c" $idx)}}) {
			rPk{{$idx}} := {{$target.PKValue (print "c" $idx) $.ModelPkgAlias}}
			key{{$idx}} := seenKey[{{$.PKType $.ModelPkgAlias}}, {{$target.PKType $.ModelPkgAlias}}]{parent: pPK, child: rPk{{$idx}}}
			if _, ok := seen_{{$rel.FieldName}}[key{{$idx}}]; !ok {
				seen_{{$rel.FieldName}}[key{{$idx}}] = struct{}{}
				child := c{{$idx}}
				{{if or (eq $rel.Type "HasMany") (eq $rel.Type "ManyToMany") -}}
				{{if $rel.IsPointer -}}
				parent.{{$rel.FieldName}} = append(parent.{{$rel.FieldName}}, &child)
				{{else -}}
				parent.{{$rel.FieldName}} = append(parent.{{$rel.FieldName}}, child)
				{{end -}}
				{{else if eq $rel.Type "BelongsTo" -}}
				{{if $rel.IsPointer -}}
				parent.{{$rel.FieldName}} = &child
				{{else -}}
				parent.{{$rel.FieldName}} = child
				{{end -}}
				{{end -}}
			}
		}
		{{end -}}
	}

	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("fetchAll{{.NamePlural}}WithRelations: iterating rows: %w", err)
	}

	return items, nil
}
{{else}}
func get{{.Name}}ByIDWithRelations(ctx context.Context, db DBTX, {{.PKParams .ModelPkgAlias}}, cfg QueryOptions) (*{{.ModelPkgAlias}}.{{.Name}}, error) {
	opts := []QueryOption{Preload(false)}
	if cfg.IncludeDeleted {
		opts = append(opts, IncludeDeleted())
	}

	m, err := Get{{.Name}}ByID(ctx, db, {{.PKArgs ""}}, opts...)
	if err != nil {
		return nil, err
	}

	{{range $idx, $rel := .Relations -}}
	{{$target := index $.AllKnownModels $rel.TargetModel -}}
	{{if eq $rel.Type "HasMany"}}
	{
		preloadOpts := []QueryOption{Where("{{$rel.ForeignKey}} = $1", m.{{$.FirstPK.Name}})}
		if cfg.IncludeDeleted {
			preloadOpts = append(preloadOpts, IncludeDeleted())
		}
		children, err := FetchAll{{$target.NamePlural}}(ctx, db, preloadOpts...)
		if err != nil {
			return nil, fmt.Errorf("get{{$.Name}}ByIDWithRelations: preloading {{$rel.FieldName}}: %w", err)
		}
		{{if $rel.IsPointer -}}
		m.{{$rel.FieldName}} = children
		{{else -}}
		m.{{$rel.FieldName}} = make([]{{$.ModelPkgAlias}}.{{$target.Name}}, len(children))
		for i, child := range children {
			m.{{$rel.FieldName}}[i] = *child
		}
		{{end -}}
	}
	{{else if eq $rel.Type "BelongsTo"}}
	{{$parentFK := $.FieldByColumn $rel.ForeignKey -}}
	{{if $parentFK -}}
	{{if $parentFK.IsPointer}}
	if m.{{$parentFK.Name}} != nil {
		preloadOpts := []QueryOption{}
		if cfg.IncludeDeleted {
			preloadOpts = append(preloadOpts, IncludeDeleted())
		}
		child, err := Get{{$target.Name}}ByID(ctx, db, *m.{{$parentFK.Name}}, preloadOpts...)
		if err != nil && !errors.Is(err, sql.ErrNoRows) {
			return nil, fmt.Errorf("get{{$.Name}}ByIDWithRelations: preloading {{$rel.FieldName}}: %w", err)
		}
		if child != nil {
			{{if $rel.IsPointer -}}
			m.{{$rel.FieldName}} = child
			{{else -}}
			m.{{$rel.FieldName}} = *child
			{{end -}}
		}
	}
	{{else}}
	if !IsZero(m.{{$parentFK.Name}}) {
		preloadOpts := []QueryOption{}
		if cfg.IncludeDeleted {
			preloadOpts = append(preloadOpts, IncludeDeleted())
		}
		child, err := Get{{$target.Name}}ByID(ctx, db, m.{{$parentFK.Name}}, preloadOpts...)
		if err != nil && !errors.Is(err, sql.ErrNoRows) {
			return nil, fmt.Errorf("get{{$.Name}}ByIDWithRelations: preloading {{$rel.FieldName}}: %w", err)
		}
		if child != nil {
			{{if $rel.IsPointer -}}
			m.{{$rel.FieldName}} = child
			{{else -}}
			m.{{$rel.FieldName}} = *child
			{{end -}}
		}
	}
	{{end -}}
	{{end -}}
	{{else if eq $rel.Type "ManyToMany"}}
	{
		query := "SELECT {{$target.AllColumns "t"}} FROM {{$target.Table}} t INNER JOIN {{$rel.JoinTable}} j ON t.{{$target.FirstPK.Column}} = j.{{$rel.JoinReferences}} WHERE j.{{$rel.JoinForeignKey}} = $1"
		{{if $target.HasDeletedAt -}}
		if !cfg.IncludeDeleted {
			query += " AND t.{{$target.DeletedAtField.Column}} IS NULL"
		}
		{{end -}}
		rows, err := db.QueryContext(ctx, query, m.{{$.FirstPK.Name}})
		if err != nil {
			return nil, fmt.Errorf("get{{$.Name}}ByIDWithRelations: preloading {{$rel.FieldName}}: %w", err)
		}
		defer rows.Close()
		var children []*{{$.ModelPkgAlias}}.{{$target.Name}}
		for rows.Next() {
			var child {{$.ModelPkgAlias}}.{{$target.Name}}
			if err := rows.Scan({{$target.AllScanArgs "child"}}); err != nil {
				return nil, fmt.Errorf("get{{$.Name}}ByIDWithRelations: scanning {{$rel.FieldName}}: %w", err)
			}
			children = append(children, &child)
		}
		if err := rows.Err(); err != nil {
			return nil, fmt.Errorf("get{{$.Name}}ByIDWithRelations: iterating {{$rel.FieldName}}: %w", err)
		}
		{{if $rel.IsPointer -}}
		m.{{$rel.FieldName}} = children
		{{else -}}
		m.{{$rel.FieldName}} = make([]{{$.ModelPkgAlias}}.{{$target.Name}}, len(children))
		for i, child := range children {
			m.{{$rel.FieldName}}[i] = *child
		}
		{{end -}}
	}
	{{end -}}
	{{end -}}

	return m, nil
}

func fetchAll{{.NamePlural}}WithRelations(ctx context.Context, db DBTX, clause string, args []any, cfg QueryOptions) ([]*{{.ModelPkgAlias}}.{{.Name}}, error) {
	query := "SELECT {{.AllColumns ""}} FROM {{.Table}}" + clause
	rows, err := db.QueryContext(ctx, query, args...)
	if err != nil {
		return nil, fmt.Errorf("fetchAll{{.NamePlural}}WithRelations: %w", err)
	}
	defer rows.Close()

	items := make([]*{{.ModelPkgAlias}}.{{.Name}}, 0, 16)
	for rows.Next() {
		var m {{.ModelPkgAlias}}.{{.Name}}
		if err := rows.Scan({{.AllScanArgs "m"}}); err != nil {
			return nil, fmt.Errorf("fetchAll{{.NamePlural}}WithRelations: scanning row: %w", err)
		}
		items = append(items, &m)
	}
	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("fetchAll{{.NamePlural}}WithRelations: iterating rows: %w", err)
	}
	if len(items) == 0 {
		return items, nil
	}

	{{if or .HasManyRelations .ManyToManyRelations -}}
	parentIDs := make([]any, 0, len(items))
	parentMap := make(map[{{.FirstPK.QualifiedType .ModelPkgAlias}}]*{{.ModelPkgAlias}}.{{.Name}}, len(items))
	for _, item := range items {
		pk := item.{{.FirstPK.Name}}
		if !IsZero(pk) {
			if _, exists := parentMap[pk]; !exists {
				parentMap[pk] = item
				parentIDs = append(parentIDs, pk)
			}
		}
	}
	{{end -}}

	{{range $idx, $rel := .Relations -}}
	{{$target := index $.AllKnownModels $rel.TargetModel -}}
	{{if eq $rel.Type "HasMany"}}
	{{$targetFK := $target.FieldByColumn $rel.ForeignKey -}}
	{{if $targetFK}}
	if len(parentIDs) > 0 {
		preloadOpts := []QueryOption{}
		if cfg.IncludeDeleted {
			preloadOpts = append(preloadOpts, IncludeDeleted())
		}
		children, err := batchIn(ctx, db, parentIDs, func(ctx context.Context, db DBTX, batch []any) ([]*{{$.ModelPkgAlias}}.{{$target.Name}}, error) {
			opts := append([]QueryOption{In("{{$rel.ForeignKey}}", batch...)}, preloadOpts...)
			return FetchAll{{$target.NamePlural}}(ctx, db, opts...)
		})
		if err != nil {
			return nil, fmt.Errorf("fetchAll{{$.NamePlural}}WithRelations: preloading {{$rel.FieldName}}: %w", err)
		}
		for _, child := range children {
			{{if $targetFK.IsPointer -}}
			if child.{{$targetFK.Name}} != nil {
				if parent, ok := parentMap[*child.{{$targetFK.Name}}]; ok {
					{{if $rel.IsPointer -}}
					parent.{{$rel.FieldName}} = append(parent.{{$rel.FieldName}}, child)
					{{else -}}
					parent.{{$rel.FieldName}} = append(parent.{{$rel.FieldName}}, *child)
					{{end -}}
				}
			}
			{{else -}}
			if parent, ok := parentMap[child.{{$targetFK.Name}}]; ok {
				{{if $rel.IsPointer -}}
				parent.{{$rel.FieldName}} = append(parent.{{$rel.FieldName}}, child)
				{{else -}}
				parent.{{$rel.FieldName}} = append(parent.{{$rel.FieldName}}, *child)
				{{end -}}
			}
			{{end -}}
		}
	}
	{{end -}}
	{{else if eq $rel.Type "BelongsTo"}}
	{{$parentFK := $.FieldByColumn $rel.ForeignKey -}}
	{{if $parentFK}}
	{
		fkIDs := make([]any, 0, len(items))
		fkMap := make(map[{{$target.FirstPK.QualifiedType $.ModelPkgAlias}}][]*{{$.ModelPkgAlias}}.{{$.Name}}, len(items))
		for _, item := range items {
			{{if $parentFK.IsPointer -}}
			if item.{{$parentFK.Name}} != nil {
				fk := *item.{{$parentFK.Name}}
				if _, exists := fkMap[fk]; !exists {
					fkIDs = append(fkIDs, fk)
				}
				fkMap[fk] = append(fkMap[fk], item)
			}
			{{else -}}
			fk := item.{{$parentFK.Name}}
			if !IsZero(fk) {
				if _, exists := fkMap[fk]; !exists {
					fkIDs = append(fkIDs, fk)
				}
				fkMap[fk] = append(fkMap[fk], item)
			}
			{{end -}}
		}

		if len(fkIDs) > 0 {
			preloadOpts := []QueryOption{}
			if cfg.IncludeDeleted {
				preloadOpts = append(preloadOpts, IncludeDeleted())
			}
			children, err := batchIn(ctx, db, fkIDs, func(ctx context.Context, db DBTX, batch []any) ([]*{{$.ModelPkgAlias}}.{{$target.Name}}, error) {
				opts := append([]QueryOption{In("{{$target.FirstPK.Column}}", batch...)}, preloadOpts...)
				return FetchAll{{$target.NamePlural}}(ctx, db, opts...)
			})
			if err != nil {
				return nil, fmt.Errorf("fetchAll{{$.NamePlural}}WithRelations: preloading {{$rel.FieldName}}: %w", err)
			}
			for _, child := range children {
				parents := fkMap[child.{{$target.FirstPK.Name}}]
				for _, parent := range parents {
					{{if $rel.IsPointer -}}
					parent.{{$rel.FieldName}} = child
					{{else -}}
					parent.{{$rel.FieldName}} = *child
					{{end -}}
				}
			}
		}
	}
	{{end -}}
	{{else if eq $rel.Type "ManyToMany"}}
	if len(parentIDs) > 0 {
		preloadOpts := []QueryOption{}
		if cfg.IncludeDeleted {
			preloadOpts = append(preloadOpts, IncludeDeleted())
		}
		type m2mPair struct {
			parentID {{$.FirstPK.QualifiedType $.ModelPkgAlias}}
			child    *{{$.ModelPkgAlias}}.{{$target.Name}}
		}
		pairs, err := batchIn(ctx, db, parentIDs, func(ctx context.Context, db DBTX, batch []any) ([]m2mPair, error) {
			whereClause := fmt.Sprintf("j.{{$rel.JoinForeignKey}} IN (%s)", strings.Join(func() []string {
				s := make([]string, len(batch))
				for i := range batch {
					s[i] = fmt.Sprintf("$%d", i+1)
				}
				return s
			}(), ", "))
			{{if $target.HasDeletedAt -}}
			if !cfg.IncludeDeleted {
				whereClause += " AND t.{{$target.DeletedAtField.Column}} IS NULL"
			}
			{{end -}}
			query := "SELECT j.{{$rel.JoinForeignKey}}, {{$target.AllColumns "t"}} FROM {{$rel.JoinTable}} j INNER JOIN {{$target.Table}} t ON t.{{$target.FirstPK.Column}} = j.{{$rel.JoinReferences}} WHERE " + whereClause
			rows, err := db.QueryContext(ctx, query, batch...)
			if err != nil {
				return nil, err
			}
			defer rows.Close()
			var res []m2mPair
			for rows.Next() {
				var pID {{$.FirstPK.QualifiedType $.ModelPkgAlias}}
				var child {{$.ModelPkgAlias}}.{{$target.Name}}
				scanArgs := append([]any{ScanNullable(&pID)}, {{$target.AllScanArgs "child"}})
				if err := rows.Scan(scanArgs...); err != nil {
					return nil, err
				}
				res = append(res, m2mPair{parentID: pID, child: &child})
			}
			return res, rows.Err()
		})
		if err != nil {
			return nil, fmt.Errorf("fetchAll{{$.NamePlural}}WithRelations: preloading {{$rel.FieldName}}: %w", err)
		}
		for _, pair := range pairs {
			if parent, ok := parentMap[pair.parentID]; ok {
				{{if $rel.IsPointer -}}
				parent.{{$rel.FieldName}} = append(parent.{{$rel.FieldName}}, pair.child)
				{{else -}}
				parent.{{$rel.FieldName}} = append(parent.{{$rel.FieldName}}, *pair.child)
				{{end -}}
			}
		}
	}
	{{end -}}
	{{end -}}

	return items, nil
}
{{end}}
{{end}}
`
