package main

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"
	"text/template"

	"golang.org/x/tools/imports"
)

// --- Runtime Helper Template ---

const runtimeTemplate = `// Code generated by query-gen. DO NOT EDIT.
package {{.Package}}

import (
	"context"
	"database/sql"
	"fmt"
	"math"
	"reflect"
	"strconv"
	"strings"
	"time"
)

type DBTX interface {
	ExecContext(ctx context.Context, query string, args ...any) (sql.Result, error)
	QueryContext(ctx context.Context, query string, args ...any) (*sql.Rows, error)
	QueryRowContext(ctx context.Context, query string, args ...any) *sql.Row
}

// inBatchSize sets the maximum number of bind parameters per IN clause batch.
// 999 is chosen to conform to SQLite3's default maximum limit (SQLITE_MAX_VARIABLE_NUMBER).
const inBatchSize = 999

// batchIn splits ids into chunks of at most inBatchSize and executes fetch for each batch,
// concatenating results to avoid exceeding database SQL parameter limits.
func batchIn[T, K any](ctx context.Context, db DBTX, ids []K, fetch func(ctx context.Context, db DBTX, batch []K) ([]T, error)) ([]T, error) {
	if len(ids) == 0 {
		return nil, nil
	}
	if len(ids) <= inBatchSize {
		return fetch(ctx, db, ids)
	}

	results := make([]T, 0, len(ids))
	for i := 0; i < len(ids); i += inBatchSize {
		end := min(i+inBatchSize, len(ids))
		batch, err := fetch(ctx, db, ids[i:end])
		if err != nil {
			return nil, fmt.Errorf("batchIn: batch [%d:%d]: %w", i, end, err)
		}
		results = append(results, batch...)
	}
	return results, nil
}

// QueryOptions provides optional filtering, ordering, grouping, having, pagination,
// association preloading, and soft-delete controls for queries.
type QueryOptions struct {
	Table string           // Dynamic table name passed at runtime.
	Where               string
	Args                []any
	Having              string
	OrderBy             string
	GroupBy             string
	Limit               int
	Offset              int
	PreloadAssociations bool
	IncludeDeleted      bool
	HardDelete          bool
}

type QueryOption func(*QueryOptions)

// staticPlaceholders pre-computes "$1" through "$1000" to eliminate string formatting
// allocations during query option construction and parameter binding.
var staticPlaceholders = func() [1001]string {
	var p [1001]string
	for i := 1; i <= 1000; i++ {
		p[i] = fmt.Sprintf("$%d", i)
	}
	return p
}()

// getPlaceholder returns a cached placeholder string for index <= 1000,
// falling back to fmt.Sprintf for higher indices.
func getPlaceholder(idx int) string {
	if idx >= 1 && idx <= 1000 {
		return staticPlaceholders[idx]
	}
	return fmt.Sprintf("$%d", idx)
}

// Where appends a raw WHERE clause to the query options.
//
// Placeholder Handling:
//   - '?' Placeholders (Recommended): Automatically replaced with dynamic dollar-indexed
//     placeholders ($1, $2, ...) based on the current total argument count. This is safest
//     for dynamic/conditional queries where the number or order of filters is unknown at runtime.
//   - '$n' Placeholders: Supported as-is. If you provide explicit placeholders (e.g. "$1", "$2"),
//     they will remain untouched, provided they match the expected argument index in your query.
func Where(where string, args ...any) QueryOption {
	return func(o *QueryOptions) {
		for _, arg := range args {
			o.Args = append(o.Args, arg)
			where = strings.Replace(where, "?", getPlaceholder(len(o.Args)), 1)
		}

		if o.Where != "" {
			o.Where += " AND " + where
		} else {
			o.Where = where
		}
	}
}

// Having appends a raw HAVING clause to the query options.
//
// Placeholder Handling:
//   - '?' Placeholders (Recommended): Automatically replaced with dynamic dollar-indexed
//     placeholders ($1, $2, ...) based on the current total argument count. This is safest
//     for dynamic/conditional queries where argument ordering is subject to change.
//   - '$n' Placeholders: Supported as-is. Explicit placeholders (e.g. "$1", "$2") remain
//     untouched in the resulting query string.
func Having(having string, args ...any) QueryOption {
	return func(o *QueryOptions) {
		for _, arg := range args {
			o.Args = append(o.Args, arg)
			having = strings.Replace(having, "?", getPlaceholder(len(o.Args)), 1)
		}
		if o.Having != "" {
			o.Having += " AND " + having
		} else {
			o.Having = having
		}
	}
}


// Table overrides the default table name for the query.
// Useful is you have multiple views that can be scanned with the same struct.
func Table(name string) QueryOption {
	return func(o *QueryOptions) {
		o.Table = name
	}
}

// Eq applies an equality filter (=).
func Eq(column string, val any) QueryOption {
	return func(o *QueryOptions) {
		o.Args = append(o.Args, val)
		clause := fmt.Sprintf("%s = %s", column, getPlaceholder(len(o.Args)))
		if o.Where != "" {
			o.Where += " AND " + clause
		} else {
			o.Where = clause
		}
	}
}

// ILIKE performs a case-insensitive pattern match using ILIKE (or LOWER for cross-dialect compatibility).
func ILIKE(column, value string) QueryOption {
	return func(o *QueryOptions) {
		if value == "" {
			return
		}

		o.Args = append(o.Args, "%"+strings.ToLower(value)+"%")
		clause := fmt.Sprintf("LOWER(%s) LIKE %s", column, getPlaceholder(len(o.Args)))

		if o.Where != "" {
			o.Where += " AND " + clause
		} else {
			o.Where = clause
		}
	}
}

// In filters a column matching any of the provided values.
func In(column string, values ...any) QueryOption {
	return func(o *QueryOptions) {
		n := len(values)
		if n == 0 {
			return
		}

		// Pre-allocate o.Args slice capacity
		if cap(o.Args)-len(o.Args) < n {
			newArgs := make([]any, len(o.Args), len(o.Args)+n)
			copy(newArgs, o.Args)
			o.Args = newArgs
		}

		var sb strings.Builder
		sb.Grow(len(column) + 6 + (n * 6))
		sb.WriteString(column)
		sb.WriteString(" IN (")

		for i, v := range values {
			if i > 0 {
				sb.WriteString(", ")
			}
			o.Args = append(o.Args, v)
			sb.WriteString(getPlaceholder(len(o.Args)))
		}
		sb.WriteByte(')')

		clause := sb.String()
		if o.Where != "" {
			o.Where += " AND " + clause
		} else {
			o.Where = clause
		}
	}
}

// NotIn filters a column not matching any of the provided values.
func NotIn(column string, values ...any) QueryOption {
	return func(o *QueryOptions) {
		if len(values) == 0 {
			return
		}

		placeholders := make([]string, 0, len(values))
		for _, v := range values {
			o.Args = append(o.Args, v)
			placeholders = append(placeholders, getPlaceholder(len(o.Args)))
		}

		clause := fmt.Sprintf("%s NOT IN (%s)", column, strings.Join(placeholders, ", "))
		if o.Where != "" {
			o.Where += " AND " + clause
		} else {
			o.Where = clause
		}
	}
}

// IsNull filters rows where the column is NULL.
func IsNull(column string) QueryOption {
	return func(o *QueryOptions) {
		clause := fmt.Sprintf("%s IS NULL", column)
		if o.Where != "" {
			o.Where += " AND " + clause
		} else {
			o.Where = clause
		}
	}
}

// IsNotNull filters rows where the column is NOT NULL.
func IsNotNull(column string) QueryOption {
	return func(o *QueryOptions) {
		clause := fmt.Sprintf("%s IS NOT NULL", column)
		if o.Where != "" {
			o.Where += " AND " + clause
		} else {
			o.Where = clause
		}
	}
}

// Between applies a BETWEEN min AND max filter on a column.
func Between(column string, min, max any) QueryOption {
	return func(o *QueryOptions) {
		o.Args = append(o.Args, min)
		p1 := getPlaceholder(len(o.Args))
		o.Args = append(o.Args, max)
		p2 := getPlaceholder(len(o.Args))

		clause := fmt.Sprintf("%s BETWEEN %s AND %s", column, p1, p2)
		if o.Where != "" {
			o.Where += " AND " + clause
		} else {
			o.Where = clause
		}
	}
}

// Search performs a pattern match across multiple columns.
func Search(query string, columns ...string) QueryOption {
	return func(o *QueryOptions) {
		if query == "" || len(columns) == 0 {
			return
		}

		o.Args = append(o.Args, "%"+query+"%")
		placeholder := getPlaceholder(len(o.Args))

		clauses := make([]string, 0, len(columns))
		for _, col := range columns {
			clauses = append(clauses, fmt.Sprintf("%s LIKE %s", col, placeholder))
		}

		groupClause := "(" + strings.Join(clauses, " OR ") + ")"
		if o.Where != "" {
			o.Where += " AND " + groupClause
		} else {
			o.Where = groupClause
		}
	}
}

// Gt applies a greater-than filter (>).
func Gt(column string, val any) QueryOption {
	return func(o *QueryOptions) {
		o.Args = append(o.Args, val)
		clause := fmt.Sprintf("%s > %s", column, getPlaceholder(len(o.Args)))
		if o.Where != "" {
			o.Where += " AND " + clause
		} else {
			o.Where = clause
		}
	}
}

// Gte applies a greater-than-or-equal filter (>=).
func Gte(column string, val any) QueryOption {
	return func(o *QueryOptions) {
		o.Args = append(o.Args, val)
		clause := fmt.Sprintf("%s >= %s", column, getPlaceholder(len(o.Args)))
		if o.Where != "" {
			o.Where += " AND " + clause
		} else {
			o.Where = clause
		}
	}
}

// Lt applies a less-than filter (<).
func Lt(column string, val any) QueryOption {
	return func(o *QueryOptions) {
		o.Args = append(o.Args, val)
		clause := fmt.Sprintf("%s < %s", column, getPlaceholder(len(o.Args)))
		if o.Where != "" {
			o.Where += " AND " + clause
		} else {
			o.Where = clause
		}
	}
}

// Lte applies a less-than-or-equal filter (<=).
func Lte(column string, val any) QueryOption {
	return func(o *QueryOptions) {
		o.Args = append(o.Args, val)
		clause := fmt.Sprintf("%s <= %s", column, getPlaceholder(len(o.Args)))
		if o.Where != "" {
			o.Where += " AND " + clause
		} else {
			o.Where = clause
		}
	}
}

// Order resultset by the specified column/columns (conditions).
func OrderBy(orderBy string) QueryOption {
	return func(o *QueryOptions) {
		o.OrderBy = orderBy
	}
}

// Group by the specified column/columns (conditions).
func GroupBy(groupBy string) QueryOption {
	return func(o *QueryOptions) {
		o.GroupBy = groupBy
	}
}

// Set pagination limit. Use together with Offsset to control pagination.
func Limit(limit int) QueryOption {
	return func(o *QueryOptions) {
		o.Limit = limit
	}
}

// Set pagination offset. Must be set together with limit.
func Offset(offset int) QueryOption {
	return func(o *QueryOptions) {
		o.Offset = offset
	}
}

// Preload enables or disables preloading associated model relations.
func Preload(preload bool) QueryOption {
	return func(o *QueryOptions) {
		o.PreloadAssociations = preload
	}
}

// IncludeDeleted includes soft-deleted records (where deleted_at IS NOT NULL) in query results.
func IncludeDeleted() QueryOption {
	return func(o *QueryOptions) {
		o.IncludeDeleted = true
	}
}

// HardDelete forces permanent SQL deletion on models supporting soft deletes.
func HardDelete() QueryOption {
	return func(o *QueryOptions) {
		o.HardDelete = true
	}
}

// DateRange applies date range filter on a date column.
// e.g DateRange("DATE(created_at)", "2021-01-01", "2021-12-31")
// It does nothing if start or end is empty.
func DateRange(column string, start, end string) QueryOption {
	return func(o *QueryOptions) {
		if start != "" && end != "" {
			o.Args = append(o.Args, start, end)
			placeholder1 := fmt.Sprintf("$%d", len(o.Args)-1)
			placeholder2 := fmt.Sprintf("$%d", len(o.Args))
			clause := fmt.Sprintf("%s BETWEEN %s AND %s", column, placeholder1, placeholder2)
			if o.Where != "" {
				o.Where += " AND " + clause
			} else {
				o.Where = clause
			}
		} else if start != "" {
			o.Args = append(o.Args, start)
			clause := fmt.Sprintf("%s >= $%d", column, len(o.Args))
			if o.Where != "" {
				o.Where += " AND " + clause
			} else {
				o.Where = clause
			}
		} else if end != "" {
			o.Args = append(o.Args, end)
			clause := fmt.Sprintf("%s <= $%d", column, len(o.Args))
			if o.Where != "" {
				o.Where += " AND " + clause
			} else {
				o.Where = clause
			}
		}
	}
}

// MonthRange is the same as DateRange but truncates the date to month.
// e.g MonthRange("DATE(created_at)", "2021-01-01", "2021-12-31")
// It does nothing if start or end is empty.
func MonthRange(column string, start, end string) QueryOption {
	return func(o *QueryOptions) {
		if start != "" && end != "" {
			o.Args = append(o.Args, start, end)
			p1 := fmt.Sprintf("$%d", len(o.Args)-1)
			p2 := fmt.Sprintf("$%d", len(o.Args))
			clause := fmt.Sprintf("%s BETWEEN DATE_TRUNC('month', %s::DATE) AND DATE_TRUNC('month', %s::DATE)", column, p1, p2)
			if o.Where != "" {
				o.Where += " AND " + clause
			} else {
				o.Where = clause
			}
		} else if start != "" {
			o.Args = append(o.Args, start)
			clause := fmt.Sprintf("%s >= DATE_TRUNC('month', $%d::DATE)", column, len(o.Args))
			if o.Where != "" {
				o.Where += " AND " + clause
			} else {
				o.Where = clause
			}
		} else if end != "" {
			o.Args = append(o.Args, end)
			clause := fmt.Sprintf("%s <= DATE_TRUNC('month', $%d::DATE)", column, len(o.Args))
			if o.Where != "" {
				o.Where += " AND " + clause
			} else {
				o.Where = clause
			}
		}
	}
}

// YearRange is the same as date range but truncates the date to year.
// e.g YearRange("DATE(created_at)", "2020-01-01", "2024-12-31")
// It does nothing if start or end is empty.
func YearRange(column string, start, end string) QueryOption {
	return func(o *QueryOptions) {
		if start != "" && end != "" {
			o.Args = append(o.Args, start, end)
			p1 := fmt.Sprintf("$%d", len(o.Args)-1)
			p2 := fmt.Sprintf("$%d", len(o.Args))
			clause := fmt.Sprintf("%s BETWEEN DATE_TRUNC('year', %s::DATE) AND DATE_TRUNC('year', %s::DATE)", column, p1, p2)
			if o.Where != "" {
				o.Where += " AND " + clause
			} else {
				o.Where = clause
			}
		} else if start != "" {
			o.Args = append(o.Args, start)
			clause := fmt.Sprintf("%s >= DATE_TRUNC('year', $%d::DATE)", column, len(o.Args))
			if o.Where != "" {
				o.Where += " AND " + clause
			} else {
				o.Where = clause
			}
		} else if end != "" {
			o.Args = append(o.Args, end)
			clause := fmt.Sprintf("%s <= DATE_TRUNC('year', $%d::DATE)", column, len(o.Args))
			if o.Where != "" {
				o.Where += " AND " + clause
			} else {
				o.Where = clause
			}
		}
	}
}

func parseQueryOptions(opts ...QueryOption) QueryOptions {
	var cfg QueryOptions
	for _, opt := range opts {
		if opt != nil {
			opt(&cfg)
		}
	}
	return cfg
}

func applyQueryOptions(defaultPK string, deletedAtCol string, opts ...QueryOption) (string, []any, QueryOptions) {
	cfg := parseQueryOptions(opts...)

	if deletedAtCol != "" && !cfg.IncludeDeleted {
		clause := deletedAtCol + " IS NULL"
		if cfg.Where != "" {
			cfg.Where = clause + " AND " + cfg.Where
		} else {
			cfg.Where = clause
		}
	}

	var sb strings.Builder
	args := cfg.Args

	if cfg.Where != "" {
		sb.WriteString(" WHERE ")
		sb.WriteString(cfg.Where)
	}

	if cfg.GroupBy != "" {
		sb.WriteString(" GROUP BY ")
		sb.WriteString(cfg.GroupBy)
	}

	if cfg.Having != "" {
		sb.WriteString(" HAVING ")
		sb.WriteString(cfg.Having)
	}

	if cfg.OrderBy != "" {
		sb.WriteString(" ORDER BY ")
		sb.WriteString(cfg.OrderBy)
	} else if defaultPK != "" {
		sb.WriteString(" ORDER BY ")
		sb.WriteString(defaultPK)
		sb.WriteString(" ASC")
	}

	if cfg.Limit > 0 {
		args = append(args, cfg.Limit)
		fmt.Fprintf(&sb, " LIMIT $%d", len(args))
	}

	if cfg.Offset > 0 {
		args = append(args, cfg.Offset)
		fmt.Fprintf(&sb, " OFFSET $%d", len(args))
	}

	return sb.String(), args, cfg
}

// PaginationResult holds the output of a paginated query.
type PaginationResult[T any] struct {
	Page       int   ` + "`" + `json:"page"` + "`" + `
	PageSize   int   ` + "`" + `json:"page_size"` + "`" + `
	TotalPages int64 ` + "`" + `json:"total_pages"` + "`" + `
	Count      int64 ` + "`" + `json:"count"` + "`" + `
	HasNext    bool  ` + "`" + `json:"has_next"` + "`" + `
	HasPrev    bool  ` + "`" + `json:"has_prev"` + "`" + `
	Results    []T   ` + "`" + `json:"results"` + "`" + `
}

// FetchFunc defines a function signature capable of fetching records using DBTX and QueryOptions.
type FetchFunc[T any] func(ctx context.Context, db DBTX, opts ...QueryOption) ([]T, error)

// CountFunc defines a function signature capable of counting total matching rows using DBTX and QueryOptions.
type CountFunc func(ctx context.Context, db DBTX, opts ...QueryOption) (int64, error)

// Paginate executes a paginated query using DBTX, counting total rows and retrieving the requested page.
// Page is constrained to (1, 10) if page < 1 or pageSize < 1.
func Paginate[T any](ctx context.Context, db DBTX, countFn CountFunc, fetchFn FetchFunc[T], page, pageSize int, opts ...QueryOption) (*PaginationResult[T], error) {
	if page < 1 {
		page = 1
	}
	if pageSize < 1 {
		pageSize = 10
	}

	totalCount, err := countFn(ctx, db, opts...)
	if err != nil {
		return nil, fmt.Errorf("paginate: counting total rows: %w", err)
	}

	// Append pagination limit and offset options
	pOpts := append([]QueryOption(nil), opts...)
	pOpts = append(pOpts, Limit(pageSize), Offset((page-1)*pageSize))

	results, err := fetchFn(ctx, db, pOpts...)
	if err != nil {
		return nil, fmt.Errorf("paginate: fetching page results: %w", err)
	}

	if results == nil {
		results = make([]T, 0)
	}

	return &PaginationResult[T]{
		Page:       page,
		PageSize:   pageSize,
		HasNext:    int64(page*pageSize) < totalCount,
		HasPrev:    page > 1,
		Results:    results,
		Count:      totalCount,
		TotalPages: int64(math.Ceil(float64(totalCount) / float64(pageSize))),
	}, nil
}

// nullableScanner adapts a *T destination to the sql.Scanner interface,
// handling NULL source values by zeroing dst, and falling back to
// sql.Scanner or convertAssign for types that don't directly assert to T.
type nullableScanner[T any] struct {
	dst *T // Destination field. Not owned; caller retains ownership.
}

// Scan implements sql.Scanner.
func (n nullableScanner[T]) Scan(src any) error {
	if src == nil {
		var zero T
		*n.dst = zero
		return nil
	}

	if v, ok := src.(T); ok {
		*n.dst = v
		return nil
	}

	if err := convertAssign(n.dst, src); err == nil {
		return nil
	}

	if scanner, ok := any(n.dst).(sql.Scanner); ok {
		return scanner.Scan(src)
	}

	// n.dst is like **string, so vDst is *string
	vDst := reflect.ValueOf(n.dst).Elem() 
	if vDst.Kind() == reflect.Pointer {
		if vDst.IsNil() {
			// Automatically allocates a new type: e.g new(string)
			vDst.Set(reflect.New(vDst.Type().Elem()))
		}
		// Passes the inner *string to convertAssign
		return convertAssign(vDst.Interface(), src)
	}
	return fmt.Errorf("ScanNullable: cannot scan %T into %T", src, n.dst)
}

// ScanNullable returns a value implementing sql.Scanner for dst.
func ScanNullable[T any](dst *T) nullableScanner[T] {
	return nullableScanner[T]{dst: dst}
}

// parseTimeString parses SQL and ISO 8601 timestamp strings.
func parseTimeString(s string) (time.Time, error) {
	formats := []string{
		"2006-01-02 15:04:05.999999999-07",
		"2006-01-02 15:04:05-07",
		"2006-01-02 15:04:05.999999999",
		"2006-01-02 15:04:05",
		time.RFC3339Nano,
		time.RFC3339,
		"2006-01-02",
		"Mon Jan 2 15:04:05 MST 2006",
		"Mon Jan  2 15:04:05 MST 2006",
	}

	for _, fmtStr := range formats {
		if t, err := time.Parse(fmtStr, s); err == nil {
			return t, nil
		}
	}
	return time.Time{}, fmt.Errorf("parseTimeString: failed to parse time string %q", s)
}

func convertAssign(dst any, src any) error {
	if src == nil {
		return nil
	}

	switch p := dst.(type) {
	case *string:
		switch s := src.(type) {
		case []byte:
			*p = string(s)
			return nil
		case string:
			*p = s
			return nil
		}
	case *[]byte:
		switch s := src.(type) {
		case string:
			*p = []byte(s)
			return nil
		case []byte:
			cp := make([]byte, len(s))
			copy(cp, s)
			*p = cp
			return nil
		}
	case *time.Time:
		switch s := src.(type) {
		case string:
			t, err := parseTimeString(s)
			if err != nil {
				return err
			}
			*p = t
			return nil
		case []byte:
			t, err := parseTimeString(string(s))
			if err != nil {
				return err
			}
			*p = t
			return nil
		}
	case *int:
		if i, ok := toInt64(src); ok {
			*p = int(i)
			return nil
		}
	case *int8:
		if i, ok := toInt64(src); ok {
			*p = int8(i)
			return nil
		}
	case *int16:
		if i, ok := toInt64(src); ok {
			*p = int16(i)
			return nil
		}
	case *int32:
		if i, ok := toInt64(src); ok {
			*p = int32(i)
			return nil
		}
	case *int64:
		if i, ok := toInt64(src); ok {
			*p = i
			return nil
		}
	case *uint:
		if u, ok := toUint64(src); ok {
			*p = uint(u)
			return nil
		}
	case *uint8:
		if u, ok := toUint64(src); ok {
			*p = uint8(u)
			return nil
		}
	case *uint16:
		if u, ok := toUint64(src); ok {
			*p = uint16(u)
			return nil
		}
	case *uint32:
		if u, ok := toUint64(src); ok {
			*p = uint32(u)
			return nil
		}
	case *uint64:
		if u, ok := toUint64(src); ok {
			*p = u
			return nil
		}
	case *float32:
		if f, ok := toFloat64(src); ok {
			*p = float32(f)
			return nil
		}
	case *float64:
		if f, ok := toFloat64(src); ok {
			*p = f
			return nil
		}
	case *time.Duration:
		if i, ok := toInt64(src); ok {
			*p = time.Duration(i)
			return nil
		}
		switch s := src.(type) {
		case []byte:
			i, err := strconv.ParseInt(string(s), 10, 64)
			if err != nil {
				return fmt.Errorf("convertAssign: failed to parse duration bytes %q: %w", s, err)
			}
			*p = time.Duration(i)
			return nil
		case string:
			i, err := strconv.ParseInt(s, 10, 64)
			if err != nil {
				return fmt.Errorf("convertAssign: failed to parse duration string %q: %w", s, err)
			}
			*p = time.Duration(i)
			return nil
		}
	}

	vDst := reflect.ValueOf(dst)
	if vDst.Kind() != reflect.Pointer || vDst.IsNil() {
		return fmt.Errorf("convertAssign: dst must be a non-nil pointer, got %T", dst)
	}

	vElem := vDst.Elem()
	vSrc := reflect.ValueOf(src)

	if vSrc.Type().ConvertibleTo(vElem.Type()) {
		vElem.Set(vSrc.Convert(vElem.Type()))
		return nil
	}

	return fmt.Errorf("ScanNullable: cannot convert %T (%v) to %T", src, src, dst)
}

func toInt64(src any) (int64, bool) {
	switch v := src.(type) {
	case int:
		return int64(v), true
	case int8:
		return int64(v), true
	case int16:
		return int64(v), true
	case int32:
		return int64(v), true
	case int64:
		return v, true
	case uint:
		return int64(v), true
	case uint8:
		return int64(v), true
	case uint16:
		return int64(v), true
	case uint32:
		return int64(v), true
	case uint64:
		return int64(v), true
	default:
		return 0, false
	}
}

func toUint64(src any) (uint64, bool) {
	switch v := src.(type) {
	case int:
		return uint64(v), true
	case int8:
		return uint64(v), true
	case int16:
		return uint64(v), true
	case int32:
		return uint64(v), true
	case int64:
		return uint64(v), true
	case uint:
		return uint64(v), true
	case uint8:
		return uint64(v), true
	case uint16:
		return uint64(v), true
	case uint32:
		return uint64(v), true
	case uint64:
		return v, true
	default:
		return 0, false
	}
}

func toFloat64(src any) (float64, bool) {
	switch v := src.(type) {
	case float32:
		return float64(v), true
	case float64:
		return v, true
	case int:
		return float64(v), true
	case int64:
		return float64(v), true
	case uint64:
		return float64(v), true
	default:
		return 0, false
	}
}

func IsZero(v any) bool {
	if v == nil {
		return true
	}

	switch t := v.(type) {
	case time.Time:
		return t.IsZero()
	case *time.Time:
		return t == nil || t.IsZero()
	}

	val := reflect.ValueOf(v)
	if val.Kind() == reflect.Pointer {
		if val.IsNil() {
			return true
		}
		return val.Elem().IsZero()
	}

	return val.IsZero()
}

func toPtr[T any](v T) *T {
	if IsZero(v) {
		return nil
	}
	return &v
}

// seenKey uniquely identifies a (parent, child) primary key pair.
type seenKey[P comparable, C comparable] struct {
	parent P
	child  C
}
`

func generateRuntimeFile(outDir, outPkg string) error {
	tmpl, err := template.New("runtime").Parse(runtimeTemplate)
	if err != nil {
		return fmt.Errorf("parsing runtime template: %w", err)
	}

	var buf bytes.Buffer
	data := map[string]string{"Package": outPkg}
	if err := tmpl.Execute(&buf, data); err != nil {
		return fmt.Errorf("executing runtime template: %w", err)
	}

	filePath := filepath.Join(outDir, "runtime_gen.go")

	formatted, err := imports.Process(filePath, buf.Bytes(), nil)
	if err != nil {
		formatted = buf.Bytes()
	}

	if err := os.WriteFile(filePath, formatted, 0o644); err != nil {
		return fmt.Errorf("writing runtime_gen.go: %w", err)
	}
	return nil
}
