// Code generated by query-gen. DO NOT EDIT.
package queries

import (
	"context"
	"database/sql"
	"errors"
	"fmt"
	"slices"
	"strings"

	"github.com/abiiranathan/query-gen/example/models"
)

// InsertCategory inserts a new Category record into the categories table.
func InsertCategory(ctx context.Context, db DBTX, m *models.Category) error {
	if db == nil {
		return errors.New("insertCategory: db is nil")
	}
	if m == nil {
		return errors.New("insertCategory: m is nil")
	}

	fields := []struct {
		col        string
		val        any
		omitIfZero bool
	}{
		{col: "project_id", val: m.ProjectID, omitIfZero: false},
		{col: "name", val: m.Name, omitIfZero: false},
	}

	cols := make([]string, 0, len(fields))
	args := make([]any, 0, len(fields))
	placeholders := make([]string, 0, len(fields))

	for _, f := range fields {
		if f.omitIfZero && IsZero(f.val) {
			continue
		}
		cols = append(cols, f.col)
		args = append(args, f.val)
		placeholders = append(placeholders, fmt.Sprintf("$%d", len(args)))
	}

	var query string
	if len(cols) == 0 {
		query = "INSERT INTO categories DEFAULT VALUES RETURNING id, project_id, name"
	} else {
		query = fmt.Sprintf("INSERT INTO categories (%s) VALUES (%s) RETURNING id, project_id, name",
			strings.Join(cols, ", "), strings.Join(placeholders, ", "))
	}

	if err := db.QueryRowContext(ctx, query, args...).
		Scan(&m.ID, &m.ProjectID, &m.Name); err != nil {
		return fmt.Errorf("insertCategory: %w", err)
	}
	return nil
}

// ============ Bulk insert ========================

// InsertCategories inserts multiple Category records into categories in efficient parameter-bounded batches.
// Automatically populates database-generated values (e.g., auto-increment primary keys, default values) back into input structs via RETURNING.
func InsertCategories(ctx context.Context, db DBTX, models []*models.Category) error {
	if db == nil {
		return errors.New("insertCategories: db is nil")
	}
	if len(models) == 0 {
		return nil
	}

	const batchSize = 499
	for i := 0; i < len(models); i += batchSize {
		end := min((i + batchSize), len(models))
		batch := models[i:end]
		if err := insertCategoriesBatch(ctx, db, batch); err != nil {
			return fmt.Errorf("insertCategories: batch [%d:%d]: %w", i, end, err)
		}
	}
	return nil
}

func insertCategoriesBatch(ctx context.Context, db DBTX, batch []*models.Category) error {
	if len(batch) == 0 {
		return nil
	}

	args := make([]any, 0, len(batch)*2)
	var sb strings.Builder
	sb.Grow(128 + len(batch)*2*8)
	sb.WriteString("INSERT INTO categories (project_id, name) VALUES ")

	paramIdx := 1
	for i, m := range batch {
		if m == nil {
			return fmt.Errorf("model at index %d is nil", i)
		}
		if i > 0 {
			sb.WriteString(", ")
		}
		sb.WriteByte('(')

		sb.WriteString(getPlaceholder(paramIdx))
		paramIdx++
		args = append(args, m.ProjectID)
		sb.WriteString(", ")
		sb.WriteString(getPlaceholder(paramIdx))
		paramIdx++
		args = append(args, m.Name)
		sb.WriteByte(')')
	}

	sb.WriteString(" RETURNING id, project_id, name")
	rows, err := db.QueryContext(ctx, sb.String(), args...)
	if err != nil {
		return fmt.Errorf("executing bulk insert: %w", err)
	}
	defer rows.Close()

	idx := 0
	for rows.Next() {
		if idx >= len(batch) {
			return errors.New("unexpected extra row returned from insert")
		}
		m := batch[idx]
		if err := rows.Scan(&m.ID, &m.ProjectID, &m.Name); err != nil {
			return fmt.Errorf("scanning row %d: %w", idx, err)
		}
		idx++
	}

	if err := rows.Err(); err != nil {
		return fmt.Errorf("iterating bulk insert rows: %w", err)
	}

	if idx < len(batch) {
		return fmt.Errorf("expected %d inserted rows, got %d", len(batch), idx)
	}

	return nil
}

// GetCategoryByID retrieves a single Category record from categories by its primary key.
func GetCategoryByID(ctx context.Context, db DBTX, id int64, opts ...QueryOption) (*models.Category, error) {
	if db == nil {
		return nil, errors.New("getCategoryByID: db is nil")
	}

	cfg := parseQueryOptions(opts...)

	if cfg.PreloadAssociations {
		return getCategoryByIDWithRelations(ctx, db, id, cfg)
	}

	const query = `
		SELECT id, project_id, name
		FROM categories
		WHERE id = $1
	`

	row := db.QueryRowContext(ctx, query, id)
	var m models.Category
	if err := row.Scan(&m.ID, &m.ProjectID, &m.Name); err != nil {
		return nil, fmt.Errorf("getCategoryByID(%v): %w", id, err)
	}

	return &m, nil
}

// GetCategory retrieves a single Category record matching mandatory query options/where clause.
// Returns sql.ErrNoRows if no matching record is found.
func GetCategory(ctx context.Context, db DBTX, opts ...QueryOption) (*models.Category, error) {
	if db == nil {
		return nil, errors.New("getCategory: db is nil")
	}

	cfg := parseQueryOptions(opts...)
	if cfg.Where == "" {
		return nil, errors.New("getCategory: query options/where clause required to prevent returning arbitrary row")
	}

	pOpts := append([]QueryOption(nil), opts...)
	pOpts = append(pOpts, Limit(1))

	items, err := FetchAllCategories(ctx, db, pOpts...)
	if err != nil {
		return nil, fmt.Errorf("getCategory: %w", err)
	}
	if len(items) == 0 {
		return nil, fmt.Errorf("getCategory: %w", sql.ErrNoRows)
	}
	return items[0], nil
}

// UpdateCategoryColumns updates only the specified updatable columns/fields for an existing Category record in categories.
// Column arguments can be database column names (e.g. "email") or Go field names (e.g. "Email").
func UpdateCategoryColumns(ctx context.Context, db DBTX, m *models.Category, cols ...string) error {
	if db == nil {
		return errors.New("updateCategoryColumns: db is nil")
	}
	if m == nil {
		return errors.New("updateCategoryColumns: m is nil")
	}
	if len(cols) == 0 {
		return errors.New("updateCategoryColumns: at least one column/field must be specified")
	}

	allowedColumns := []string{
		"project_id", "ProjectID",
		"name", "Name",
	}

	setClauses := make([]string, 0, len(cols))
	args := make([]any, 0, len(cols)+1)

	for _, col := range cols {
		if !slices.Contains(allowedColumns, col) {
			return fmt.Errorf("updateCategoryColumns: column or field %q is not updatable", col)
		}

		var dbCol string
		var val any

		switch col {
		case "project_id", "ProjectID":
			dbCol = "project_id"
			val = m.ProjectID
		case "name", "Name":
			dbCol = "name"
			val = m.Name
		}

		args = append(args, val)
		setClauses = append(setClauses, fmt.Sprintf("%s = $%d", dbCol, len(args)))
	}

	pkClauses := make([]string, 0, 1)
	pkClauses = append(pkClauses, fmt.Sprintf("%s = $%d", "id", len(args)+0+1))
	query := fmt.Sprintf("UPDATE categories SET %s WHERE %s",
		strings.Join(setClauses, ", "), strings.Join(pkClauses, " AND "))

	args = append(args, m.ID)

	res, err := db.ExecContext(ctx, query, args...)
	if err != nil {
		return fmt.Errorf("updateCategoryColumns(%v): %w", fmt.Sprint(m.ID), err)
	}

	n, err := res.RowsAffected()
	if err != nil {
		return fmt.Errorf("detect rows affected: %w", err)
	}
	if n == 0 {
		return fmt.Errorf("updateCategoryColumns(%v): %w", fmt.Sprint(m.ID), sql.ErrNoRows)
	}
	return nil
}

// ExistsCategoryByID reports whether a Category record with the given primary key exists.
func ExistsCategoryByID(ctx context.Context, db DBTX, id int64, opts ...QueryOption) (bool, error) {
	if db == nil {
		return false, errors.New("existsCategoryByID: db is nil")
	}

	const query = `SELECT EXISTS(SELECT 1 FROM categories WHERE id = $1)`

	var exists bool
	if err := db.QueryRowContext(ctx, query, id).Scan(&exists); err != nil {
		return false, fmt.Errorf("existsCategoryByID(%v): %w", id, err)
	}
	return exists, nil
}

// ExistsCategory reports whether a Category record matching the mandatory query options/where clause exists.
func ExistsCategory(ctx context.Context, db DBTX, opts ...QueryOption) (bool, error) {
	if db == nil {
		return false, errors.New("existsCategory: db is nil")
	}

	cfg := parseQueryOptions(opts...)
	if cfg.Where == "" {
		return false, errors.New("existsCategory: query options/where clause required")
	}

	var whereClause string
	if cfg.Where != "" {
		whereClause = " WHERE " + cfg.Where
	}

	tableName := "categories"
	if cfg.Table != "" {
		tableName = cfg.Table
	}

	query := "SELECT EXISTS(SELECT 1 FROM " + tableName + whereClause + ")"

	var exists bool
	if err := db.QueryRowContext(ctx, query, cfg.Args...).Scan(&exists); err != nil {
		return false, fmt.Errorf("existsCategory: %w", err)
	}
	return exists, nil
}

// CountCategories returns total records matching optional filter criteria.
func CountCategories(ctx context.Context, db DBTX, opts ...QueryOption) (int64, error) {
	if db == nil {
		return 0, errors.New("countCategories: db is nil")
	}

	cfg := parseQueryOptions(opts...)

	var whereClause string
	if cfg.Where != "" {
		whereClause = " WHERE " + cfg.Where
	}

	tableName := "categories"
	if cfg.Table != "" {
		tableName = cfg.Table
	}

	query := "SELECT COUNT(*) FROM " + tableName + whereClause

	var count int64
	if err := db.QueryRowContext(ctx, query, cfg.Args...).Scan(&count); err != nil {
		return 0, fmt.Errorf("countCategories: %w", err)
	}
	return count, nil
}

// FetchAllCategories retrieves a filtered/paginated slice of Category records.
func FetchAllCategories(ctx context.Context, db DBTX, opts ...QueryOption) ([]*models.Category, error) {
	if db == nil {
		return nil, errors.New("fetchAllCategories: db is nil")
	}

	clause, args, cfg := applyQueryOptions("id", "", opts...)
	if cfg.PreloadAssociations {
		return fetchAllCategoriesWithRelations(ctx, db, clause, args, cfg)
	}

	tableName := "categories"
	if cfg.Table != "" {
		tableName = cfg.Table
	}

	query := "SELECT id, project_id, name FROM " + tableName + clause

	rows, err := db.QueryContext(ctx, query, args...)
	if err != nil {
		return nil, fmt.Errorf("fetchAllCategories: %w", err)
	}
	defer rows.Close()

	items := make([]*models.Category, 0, 16)
	for rows.Next() {
		var m models.Category
		if err := rows.Scan(&m.ID, &m.ProjectID, &m.Name); err != nil {
			return nil, fmt.Errorf("fetchAllCategories: scanning row: %w", err)
		}
		items = append(items, &m)
	}

	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("fetchAllCategories: iterating rows: %w", err)
	}

	return items, nil
}

// UpdateCategory updates an existing Category record in categories.
func UpdateCategory(ctx context.Context, db DBTX, m *models.Category) error {
	if db == nil {
		return errors.New("updateCategory: db is nil")
	}
	if m == nil {
		return errors.New("updateCategory: m is nil")
	}

	const query = `
		UPDATE categories
		SET project_id = $1, name = $2
		WHERE id = $3
	`

	res, err := db.ExecContext(ctx, query, &m.ProjectID, &m.Name, m.ID)
	if err != nil {
		return fmt.Errorf("updateCategory(%v): %w", fmt.Sprint(m.ID), err)
	}

	n, err := res.RowsAffected()
	if err != nil {
		return fmt.Errorf("detect rows affected: %w", err)
	}
	if n == 0 {
		return fmt.Errorf("updateCategory(%v): %w", fmt.Sprint(m.ID), sql.ErrNoRows)
	}
	return nil
}

// DeleteCategory deletes the Category record identified by primary key from categories.
func DeleteCategory(ctx context.Context, db DBTX, id int64, opts ...QueryOption) error {
	if db == nil {
		return errors.New("deleteCategory: db is nil")
	}

	const query = `DELETE FROM categories WHERE id = $1`

	res, err := db.ExecContext(ctx, query, id)
	if err != nil {
		return fmt.Errorf("deleteCategory(%v): %w", id, err)
	}

	n, err := res.RowsAffected()
	if err != nil {
		return fmt.Errorf("detect rows affected: %w", err)
	}
	if n == 0 {
		return fmt.Errorf("deleteCategory(%v): %w", id, sql.ErrNoRows)
	}
	return nil
}

// DeleteCategories deletes records from categories matching the provided query options and returns the number of affected rows.
func DeleteCategories(ctx context.Context, db DBTX, opts ...QueryOption) (int64, error) {
	if db == nil {
		return 0, errors.New("deleteCategories: db is nil")
	}

	cfg := parseQueryOptions(opts...)
	if cfg.Where == "" {
		return 0, errors.New("deleteCategories: query options/where clause required to prevent accidental bulk deletion")
	}

	clause, args, cfg := applyQueryOptions("", "", opts...)

	tableName := "categories"
	if cfg.Table != "" {
		tableName = cfg.Table
	}

	var query string
	query = "DELETE FROM " + tableName + clause

	res, err := db.ExecContext(ctx, query, args...)
	if err != nil {
		return 0, fmt.Errorf("deleteCategories: %w", err)
	}

	n, err := res.RowsAffected()
	if err != nil {
		return 0, fmt.Errorf("deleteCategories: detecting rows affected: %w", err)
	}

	return n, nil
}

// ================= FETCHING RELATIONS ===============================
func getCategoryByIDWithRelations(ctx context.Context, db DBTX, id int64, cfg QueryOptions) (*models.Category, error) {
	const query = `
		SELECT 
			p.id, p.project_id, p.name, r0.id, r0.name, r0.description, r0.created_at, r0.deleted_at
		FROM categories p
		LEFT JOIN projects r0 ON r0.id = p.project_id AND r0.deleted_at IS NULL
		WHERE p.id = $1
	`

	rows, err := db.QueryContext(ctx, query, id)
	if err != nil {
		return nil, fmt.Errorf("getCategoryByIDWithRelations(%v): %w", id, err)
	}
	defer rows.Close()

	var parent *models.Category
	var p models.Category

	seen_Project := make(map[int64]struct{}, 4)
	var c0 models.Project
	scanArgs := []any{
		&p.ID, &p.ProjectID, &p.Name,
		ScanNullable(&c0.ID),
		ScanNullable(&c0.Name),
		ScanNullable(&c0.Description),
		ScanNullable(&c0.CreatedAt),
		ScanNullable(&c0.DeletedAt),
	}

	for rows.Next() {
		if err := rows.Scan(scanArgs...); err != nil {
			return nil, fmt.Errorf("getCategoryByIDWithRelations(%v): scanning row: %w", id, err)
		}

		if parent == nil {
			parent = &p
		}

		if !(IsZero(c0.ID)) {
			rPk0 := c0.ID
			if _, ok := seen_Project[rPk0]; !ok {
				seen_Project[rPk0] = struct{}{}
				child := c0
				parent.Project = &child
			}
		}
	}

	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("getCategoryByIDWithRelations(%v): iterating rows: %w", id, err)
	}
	if parent == nil {
		return nil, fmt.Errorf("getCategoryByIDWithRelations(%v): %w", id, sql.ErrNoRows)
	}

	return parent, nil
}

func fetchAllCategoriesWithRelations(ctx context.Context, db DBTX, clause string, args []any, cfg QueryOptions) ([]*models.Category, error) {
	query := `
		WITH p AS (
			SELECT p.id, p.project_id, p.name
			FROM categories p
	` + clause + `
		)
		SELECT 
			p.id, p.project_id, p.name, r0.id, r0.name, r0.description, r0.created_at, r0.deleted_at
		FROM p
		LEFT JOIN projects r0 ON r0.id = p.project_id AND r0.deleted_at IS NULL
		ORDER BY p.id ASC
	`

	rows, err := db.QueryContext(ctx, query, args...)
	if err != nil {
		return nil, fmt.Errorf("fetchAllCategoriesWithRelations: %w", err)
	}
	defer rows.Close()

	items := make([]*models.Category, 0, 16)
	itemsMap := make(map[int64]*models.Category, 16)

	seen_Project := make(map[seenKey[int64, int64]]struct{}, 64)
	for rows.Next() {
		var p models.Category
		var c0 models.Project
		scanArgs := []any{
			&p.ID, &p.ProjectID, &p.Name,
			ScanNullable(&c0.ID),
			ScanNullable(&c0.Name),
			ScanNullable(&c0.Description),
			ScanNullable(&c0.CreatedAt),
			ScanNullable(&c0.DeletedAt),
		}

		if err := rows.Scan(scanArgs...); err != nil {
			return nil, fmt.Errorf("fetchAllCategoriesWithRelations: scanning row: %w", err)
		}

		pPK := p.ID
		parent, exists := itemsMap[pPK]
		if !exists {
			parent = &p
			itemsMap[pPK] = parent
			items = append(items, parent)
		}

		if !(IsZero(c0.ID)) {
			rPk0 := c0.ID
			key0 := seenKey[int64, int64]{parent: pPK, child: rPk0}
			if _, ok := seen_Project[key0]; !ok {
				seen_Project[key0] = struct{}{}
				child := c0
				parent.Project = &child
			}
		}
	}

	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("fetchAllCategoriesWithRelations: iterating rows: %w", err)
	}

	return items, nil
}
