// Code generated by query-gen. DO NOT EDIT.
package queries

import (
	"context"
	"database/sql"
	"errors"
	"fmt"
	"strings"

	"github.com/abiiranathan/query-gen/example/models"
)

// InsertCategory inserts a new Category record into the categories table.
func InsertCategory(ctx context.Context, db DBTX, m *models.Category) error {
	if db == nil {
		return errors.New("insertCategory: db is nil")
	}
	if m == nil {
		return errors.New("insertCategory: m is nil")
	}

	fields := []struct {
		col        string
		val        any
		omitIfZero bool
	}{
		{col: "project_id", val: m.ProjectID, omitIfZero: false},
		{col: "name", val: m.Name, omitIfZero: false},
	}

	cols := make([]string, 0, len(fields))
	args := make([]any, 0, len(fields))
	placeholders := make([]string, 0, len(fields))

	for _, f := range fields {
		if f.omitIfZero && IsZero(f.val) {
			continue
		}
		cols = append(cols, f.col)
		args = append(args, f.val)
		placeholders = append(placeholders, fmt.Sprintf("$%d", len(args)))
	}

	var query string
	if len(cols) == 0 {
		query = "INSERT INTO categories DEFAULT VALUES RETURNING id, project_id, name"
	} else {
		query = fmt.Sprintf("INSERT INTO categories (%s) VALUES (%s) RETURNING id, project_id, name",
			strings.Join(cols, ", "), strings.Join(placeholders, ", "))
	}

	if err := db.QueryRowContext(ctx, query, args...).Scan(&m.ID, &m.ProjectID, &m.Name); err != nil {
		return fmt.Errorf("insertCategory: %w", err)
	}
	return nil
}

// GetCategoryByID retrieves a single Category record from categories by its primary key.
func GetCategoryByID(ctx context.Context, db DBTX, id int64, opts ...QueryOption) (*models.Category, error) {
	if db == nil {
		return nil, errors.New("getCategoryByID: db is nil")
	}

	const query = `
		SELECT id, project_id, name
		FROM categories
		WHERE id = $1
	`

	row := db.QueryRowContext(ctx, query, id)
	var m models.Category
	if err := row.Scan(&m.ID, &m.ProjectID, &m.Name); err != nil {
		return nil, fmt.Errorf("getCategoryByID(%v): %w", id, err)
	}

	return &m, nil
}

// ExistsCategoryByID reports whether a Category record with the given primary key exists.
func ExistsCategoryByID(ctx context.Context, db DBTX, id int64, opts ...QueryOption) (bool, error) {
	if db == nil {
		return false, errors.New("existsCategoryByID: db is nil")
	}

	const query = `SELECT EXISTS(SELECT 1 FROM categories WHERE id = $1)`

	var exists bool
	if err := db.QueryRowContext(ctx, query, id).Scan(&exists); err != nil {
		return false, fmt.Errorf("existsCategoryByID(%v): %w", id, err)
	}
	return exists, nil
}

// CountCategories returns total records matching optional filter criteria.
func CountCategories(ctx context.Context, db DBTX, opts ...QueryOption) (int64, error) {
	if db == nil {
		return 0, errors.New("countCategories: db is nil")
	}

	clause, args, _ := applyQueryOptions("", "", opts...)
	query := "SELECT COUNT(*) FROM categories" + clause

	var count int64
	if err := db.QueryRowContext(ctx, query, args...).Scan(&count); err != nil {
		return 0, fmt.Errorf("countCategories: %w", err)
	}
	return count, nil
}

// FetchAllCategories retrieves a filtered/paginated slice of Category records.
func FetchAllCategories(ctx context.Context, db DBTX, opts ...QueryOption) ([]*models.Category, error) {
	if db == nil {
		return nil, errors.New("fetchAllCategories: db is nil")
	}

	clause, args, _ := applyQueryOptions("id", "", opts...)

	query := "SELECT id, project_id, name FROM categories" + clause

	rows, err := db.QueryContext(ctx, query, args...)
	if err != nil {
		return nil, fmt.Errorf("fetchAllCategories: %w", err)
	}
	defer rows.Close()

	items := make([]*models.Category, 0, 16)
	for rows.Next() {
		var m models.Category
		if err := rows.Scan(&m.ID, &m.ProjectID, &m.Name); err != nil {
			return nil, fmt.Errorf("fetchAllCategories: scanning row: %w", err)
		}
		items = append(items, &m)
	}

	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("fetchAllCategories: iterating rows: %w", err)
	}

	return items, nil
}

// UpdateCategory updates an existing Category record in categories.
func UpdateCategory(ctx context.Context, db DBTX, m *models.Category) error {
	if db == nil {
		return errors.New("updateCategory: db is nil")
	}
	if m == nil {
		return errors.New("updateCategory: m is nil")
	}

	const query = `
		UPDATE categories
		SET project_id = $1, name = $2
		WHERE id = $3
	`

	res, err := db.ExecContext(ctx, query, &m.ProjectID, &m.Name, m.ID)
	if err != nil {
		return fmt.Errorf("updateCategory(%v): %w", m.ID, err)
	}

	n, err := res.RowsAffected()
	if err != nil {
		return fmt.Errorf("detect rows affected: %w", err)
	}
	if n == 0 {
		return fmt.Errorf("updateCategory(%v): %w", m.ID, sql.ErrNoRows)
	}
	return nil
}

// DeleteCategory deletes the Category record identified by id from categories.
// If the model contains a DeletedAt column, it soft-deletes by setting DeletedAt to current timestamp
// unless the HardDelete() query option is supplied.
func DeleteCategory(ctx context.Context, db DBTX, id int64, opts ...QueryOption) error {
	if db == nil {
		return errors.New("deleteCategory: db is nil")
	}

	const query = `DELETE FROM categories WHERE id = $1`

	res, err := db.ExecContext(ctx, query, id)
	if err != nil {
		return fmt.Errorf("deleteCategory(%v): %w", id, err)
	}

	n, err := res.RowsAffected()
	if err != nil {
		return fmt.Errorf("detect rows affected: %w", err)
	}
	if n == 0 {
		return fmt.Errorf("deleteCategory(%v): %w", id, sql.ErrNoRows)
	}
	return nil
}

// DeleteCategories deletes records from categories matching the provided query options and returns the number of affected rows.
// Requires at least one filtering option (e.g. Where, In, Lt) to prevent accidental bulk deletion.
// If the model contains a DeletedAt column, it soft-deletes records by default unless the HardDelete() option is supplied.
func DeleteCategories(ctx context.Context, db DBTX, opts ...QueryOption) (int64, error) {
	if db == nil {
		return 0, errors.New("deleteCategories: db is nil")
	}

	cfg := parseQueryOptions(opts...)
	if cfg.Where == "" {
		return 0, errors.New("deleteCategories: query options/where clause required to prevent accidental bulk deletion")
	}

	clause, args, _ := applyQueryOptions("", "", opts...)

	var query string

	query = "DELETE FROM categories" + clause

	res, err := db.ExecContext(ctx, query, args...)
	if err != nil {
		return 0, fmt.Errorf("deleteCategories: %w", err)
	}

	n, err := res.RowsAffected()
	if err != nil {
		return 0, fmt.Errorf("deleteCategories: detecting rows affected: %w", err)
	}

	return n, nil
}

// ================= FETCHING RELATIONS ===============================
