// Code generated by query-gen. DO NOT EDIT.
package queries

import (
	"context"
	"database/sql"
	"errors"
	"fmt"
	"slices"
	"strings"

	"github.com/abiiranathan/query-gen/example/models"
)

// InsertCourse inserts a new Course record into the courses table.
func InsertCourse(ctx context.Context, db DBTX, m *models.Course) error {
	if db == nil {
		return errors.New("insertCourse: db is nil")
	}
	if m == nil {
		return errors.New("insertCourse: m is nil")
	}

	fields := []struct {
		col        string
		val        any
		omitIfZero bool
	}{
		{col: "code", val: m.Code, omitIfZero: false},
		{col: "title", val: m.Title, omitIfZero: false},
		{col: "created_at", val: m.CreatedAt, omitIfZero: true},
	}

	cols := make([]string, 0, len(fields))
	args := make([]any, 0, len(fields))
	placeholders := make([]string, 0, len(fields))

	for _, f := range fields {
		if f.omitIfZero && IsZero(f.val) {
			continue
		}
		cols = append(cols, f.col)
		args = append(args, f.val)
		placeholders = append(placeholders, fmt.Sprintf("$%d", len(args)))
	}

	var query string
	if len(cols) == 0 {
		query = "INSERT INTO courses DEFAULT VALUES RETURNING id, code, title, created_at, deleted_at"
	} else {
		query = fmt.Sprintf("INSERT INTO courses (%s) VALUES (%s) RETURNING id, code, title, created_at, deleted_at",
			strings.Join(cols, ", "), strings.Join(placeholders, ", "))
	}

	if err := db.QueryRowContext(ctx, query, args...).
		Scan(&m.ID, &m.Code, &m.Title, scanNullable(&m.CreatedAt), scanNullable(&m.DeletedAt)); err != nil {
		return fmt.Errorf("insertCourse: %w", err)
	}
	return nil
}

// ============ Bulk insert ========================

// InsertCourses inserts multiple Course records into courses in efficient parameter-bounded batches.
// Automatically populates database-generated values (e.g., auto-increment primary keys, default values) back into input structs via RETURNING.
func InsertCourses(ctx context.Context, db DBTX, models []*models.Course) error {
	if db == nil {
		return errors.New("insertCourses: db is nil")
	}
	if len(models) == 0 {
		return nil
	}

	const batchSize = 333
	for i := 0; i < len(models); i += batchSize {
		end := min((i + batchSize), len(models))
		batch := models[i:end]
		if err := insertCoursesBatch(ctx, db, batch); err != nil {
			return fmt.Errorf("insertCourses: batch [%d:%d]: %w", i, end, err)
		}
	}
	return nil
}

func insertCoursesBatch(ctx context.Context, db DBTX, batch []*models.Course) error {
	if len(batch) == 0 {
		return nil
	}

	args := make([]any, 0, len(batch)*3)
	var sb strings.Builder
	sb.Grow(128 + len(batch)*3*8)
	sb.WriteString("INSERT INTO courses (code, title, created_at) VALUES ")

	paramIdx := 1
	for i, m := range batch {
		if m == nil {
			return fmt.Errorf("model at index %d is nil", i)
		}
		if i > 0 {
			sb.WriteString(", ")
		}
		sb.WriteByte('(')

		sb.WriteString(getPlaceholder(paramIdx))
		paramIdx++
		args = append(args, m.Code)
		sb.WriteString(", ")
		sb.WriteString(getPlaceholder(paramIdx))
		paramIdx++
		args = append(args, m.Title)
		sb.WriteString(", ")
		sb.WriteString(getPlaceholder(paramIdx))
		paramIdx++
		args = append(args, m.CreatedAt)
		sb.WriteByte(')')
	}

	sb.WriteString(" RETURNING id, code, title, created_at, deleted_at")
	rows, err := db.QueryContext(ctx, sb.String(), args...)
	if err != nil {
		return fmt.Errorf("executing bulk insert: %w", err)
	}
	defer rows.Close()

	idx := 0
	for rows.Next() {
		if idx >= len(batch) {
			return errors.New("unexpected extra row returned from insert")
		}
		m := batch[idx]
		if err := rows.Scan(&m.ID, &m.Code, &m.Title, scanNullable(&m.CreatedAt), scanNullable(&m.DeletedAt)); err != nil {
			return fmt.Errorf("scanning row %d: %w", idx, err)
		}
		idx++
	}

	if err := rows.Err(); err != nil {
		return fmt.Errorf("iterating bulk insert rows: %w", err)
	}

	if idx < len(batch) {
		return fmt.Errorf("expected %d inserted rows, got %d", len(batch), idx)
	}

	return nil
}

// GetCourseByID retrieves a single Course record from courses by its primary key.
func GetCourseByID(ctx context.Context, db DBTX, id int64, opts ...QueryOption) (*models.Course, error) {
	if db == nil {
		return nil, errors.New("getCourseByID: db is nil")
	}

	cfg := parseQueryOptions(opts...)

	query := `
		SELECT id, code, title, created_at, deleted_at
		FROM courses
		WHERE id = $1
	`
	if !cfg.IncludeDeleted {
		query += " AND deleted_at IS NULL"
	}

	row := db.QueryRowContext(ctx, query, id)
	var m models.Course
	if err := row.Scan(&m.ID, &m.Code, &m.Title, scanNullable(&m.CreatedAt), scanNullable(&m.DeletedAt)); err != nil {
		return nil, fmt.Errorf("getCourseByID(%v): %w", id, err)
	}

	return &m, nil
}

// GetCourse retrieves a single Course record matching mandatory query options/where clause.
// Returns sql.ErrNoRows if no matching record is found.
func GetCourse(ctx context.Context, db DBTX, opts ...QueryOption) (*models.Course, error) {
	if db == nil {
		return nil, errors.New("getCourse: db is nil")
	}

	cfg := parseQueryOptions(opts...)
	if cfg.Where == "" {
		return nil, errors.New("getCourse: query options/where clause required to prevent returning arbitrary row")
	}

	pOpts := append([]QueryOption(nil), opts...)
	pOpts = append(pOpts, Limit(1))

	items, err := FetchAllCourses(ctx, db, pOpts...)
	if err != nil {
		return nil, fmt.Errorf("getCourse: %w", err)
	}
	if len(items) == 0 {
		return nil, fmt.Errorf("getCourse: %w", sql.ErrNoRows)
	}
	return items[0], nil
}

// UpdateCourseColumns updates only the specified updatable columns/fields for an existing Course record in courses.
// Column arguments can be database column names (e.g. "email") or Go field names (e.g. "Email").
func UpdateCourseColumns(ctx context.Context, db DBTX, m *models.Course, cols ...string) error {
	if db == nil {
		return errors.New("updateCourseColumns: db is nil")
	}
	if m == nil {
		return errors.New("updateCourseColumns: m is nil")
	}
	if len(cols) == 0 {
		return errors.New("updateCourseColumns: at least one column/field must be specified")
	}

	allowedColumns := []string{
		"code", "Code",
		"title", "Title",
		"created_at", "CreatedAt",
	}

	setClauses := make([]string, 0, len(cols))
	args := make([]any, 0, len(cols)+1)

	for _, col := range cols {
		if !slices.Contains(allowedColumns, col) {
			return fmt.Errorf("updateCourseColumns: column or field %q is not updatable", col)
		}

		var dbCol string
		var val any

		switch col {
		case "code", "Code":
			dbCol = "code"
			val = m.Code
		case "title", "Title":
			dbCol = "title"
			val = m.Title
		case "created_at", "CreatedAt":
			dbCol = "created_at"
			val = m.CreatedAt
		}

		args = append(args, val)
		setClauses = append(setClauses, fmt.Sprintf("%s = $%d", dbCol, len(args)))
	}

	pkClauses := make([]string, 0, 1)
	pkClauses = append(pkClauses, fmt.Sprintf("%s = $%d", "id", len(args)+0+1))
	query := fmt.Sprintf("UPDATE courses SET %s WHERE %s",
		strings.Join(setClauses, ", "), strings.Join(pkClauses, " AND "))

	args = append(args, m.ID)

	res, err := db.ExecContext(ctx, query, args...)
	if err != nil {
		return fmt.Errorf("updateCourseColumns(%v): %w", fmt.Sprint(m.ID), err)
	}

	n, err := res.RowsAffected()
	if err != nil {
		return fmt.Errorf("detect rows affected: %w", err)
	}
	if n == 0 {
		return fmt.Errorf("updateCourseColumns(%v): %w", fmt.Sprint(m.ID), sql.ErrNoRows)
	}
	return nil
}

// ExistsCourseByID reports whether a Course record with the given primary key exists.
func ExistsCourseByID(ctx context.Context, db DBTX, id int64, opts ...QueryOption) (bool, error) {
	if db == nil {
		return false, errors.New("existsCourseByID: db is nil")
	}

	cfg := parseQueryOptions(opts...)
	query := `SELECT EXISTS(SELECT 1 FROM courses WHERE id = $1`
	if !cfg.IncludeDeleted {
		query += " AND deleted_at IS NULL"
	}
	query += ")"

	var exists bool
	if err := db.QueryRowContext(ctx, query, id).Scan(&exists); err != nil {
		return false, fmt.Errorf("existsCourseByID(%v): %w", id, err)
	}
	return exists, nil
}

// ExistsCourse reports whether a Course record matching the mandatory query options/where clause exists.
func ExistsCourse(ctx context.Context, db DBTX, opts ...QueryOption) (bool, error) {
	if db == nil {
		return false, errors.New("existsCourse: db is nil")
	}

	cfg := parseQueryOptions(opts...)
	if cfg.Where == "" {
		return false, errors.New("existsCourse: query options/where clause required")
	}

	var whereClause string
	if cfg.Where != "" {
		whereClause = " WHERE " + cfg.Where
	}

	if !cfg.IncludeDeleted {
		if whereClause != "" {
			whereClause += " AND deleted_at IS NULL"
		} else {
			whereClause = " WHERE deleted_at IS NULL"
		}
	}

	tableName := "courses"
	if cfg.Table != "" {
		tableName = cfg.Table
	}

	query := "SELECT EXISTS(SELECT 1 FROM " + tableName + whereClause + ")"

	var exists bool
	if err := db.QueryRowContext(ctx, query, cfg.Args...).Scan(&exists); err != nil {
		return false, fmt.Errorf("existsCourse: %w", err)
	}
	return exists, nil
}

// CountCourses returns total records matching optional filter criteria.
func CountCourses(ctx context.Context, db DBTX, opts ...QueryOption) (int64, error) {
	if db == nil {
		return 0, errors.New("countCourses: db is nil")
	}

	cfg := parseQueryOptions(opts...)

	var whereClause string
	if cfg.Where != "" {
		whereClause = " WHERE " + cfg.Where
	}

	if !cfg.IncludeDeleted {
		if whereClause != "" {
			whereClause += " AND deleted_at IS NULL"
		} else {
			whereClause = " WHERE deleted_at IS NULL"
		}
	}

	tableName := "courses"
	if cfg.Table != "" {
		tableName = cfg.Table
	}

	query := "SELECT COUNT(*) FROM " + tableName + whereClause

	var count int64
	if err := db.QueryRowContext(ctx, query, cfg.Args...).Scan(&count); err != nil {
		return 0, fmt.Errorf("countCourses: %w", err)
	}
	return count, nil
}

// FetchAllCourses retrieves a filtered/paginated slice of Course records.
func FetchAllCourses(ctx context.Context, db DBTX, opts ...QueryOption) ([]*models.Course, error) {
	if db == nil {
		return nil, errors.New("fetchAllCourses: db is nil")
	}

	clause, args, cfg := applyQueryOptions("id", "deleted_at", opts...)

	tableName := "courses"
	if cfg.Table != "" {
		tableName = cfg.Table
	}

	query := "SELECT id, code, title, created_at, deleted_at FROM " + tableName + clause

	rows, err := db.QueryContext(ctx, query, args...)
	if err != nil {
		return nil, fmt.Errorf("fetchAllCourses: %w", err)
	}
	defer rows.Close()

	items := make([]*models.Course, 0, 16)
	for rows.Next() {
		var m models.Course
		if err := rows.Scan(&m.ID, &m.Code, &m.Title, scanNullable(&m.CreatedAt), scanNullable(&m.DeletedAt)); err != nil {
			return nil, fmt.Errorf("fetchAllCourses: scanning row: %w", err)
		}
		items = append(items, &m)
	}

	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("fetchAllCourses: iterating rows: %w", err)
	}

	return items, nil
}

// UpdateCourse updates an existing Course record in courses.
func UpdateCourse(ctx context.Context, db DBTX, m *models.Course) error {
	if db == nil {
		return errors.New("updateCourse: db is nil")
	}
	if m == nil {
		return errors.New("updateCourse: m is nil")
	}

	const query = `
		UPDATE courses
		SET code = $1, title = $2, created_at = $3
		WHERE id = $4
	`

	res, err := db.ExecContext(ctx, query, &m.Code, &m.Title, &m.CreatedAt, m.ID)
	if err != nil {
		return fmt.Errorf("updateCourse(%v): %w", fmt.Sprint(m.ID), err)
	}

	n, err := res.RowsAffected()
	if err != nil {
		return fmt.Errorf("detect rows affected: %w", err)
	}
	if n == 0 {
		return fmt.Errorf("updateCourse(%v): %w", fmt.Sprint(m.ID), sql.ErrNoRows)
	}
	return nil
}

// DeleteCourse deletes the Course record identified by primary key from courses.
func DeleteCourse(ctx context.Context, db DBTX, id int64, opts ...QueryOption) error {
	if db == nil {
		return errors.New("deleteCourse: db is nil")
	}

	cfg := parseQueryOptions(opts...)
	if !cfg.HardDelete {
		const query = `UPDATE courses SET deleted_at = CURRENT_TIMESTAMP WHERE id = $1 AND deleted_at IS NULL`
		res, err := db.ExecContext(ctx, query, id)
		if err != nil {
			return fmt.Errorf("deleteCourse(%v): %w", id, err)
		}
		n, err := res.RowsAffected()
		if err != nil {
			return fmt.Errorf("detect rows affected: %w", err)
		}
		if n == 0 {
			return fmt.Errorf("deleteCourse(%v): %w", id, sql.ErrNoRows)
		}
		return nil
	}

	const query = `DELETE FROM courses WHERE id = $1`

	res, err := db.ExecContext(ctx, query, id)
	if err != nil {
		return fmt.Errorf("deleteCourse(%v): %w", id, err)
	}

	n, err := res.RowsAffected()
	if err != nil {
		return fmt.Errorf("detect rows affected: %w", err)
	}
	if n == 0 {
		return fmt.Errorf("deleteCourse(%v): %w", id, sql.ErrNoRows)
	}
	return nil
}

// DeleteCourses deletes records from courses matching the provided query options and returns the number of affected rows.
func DeleteCourses(ctx context.Context, db DBTX, opts ...QueryOption) (int64, error) {
	if db == nil {
		return 0, errors.New("deleteCourses: db is nil")
	}

	cfg := parseQueryOptions(opts...)
	if cfg.Where == "" {
		return 0, errors.New("deleteCourses: query options/where clause required to prevent accidental bulk deletion")
	}

	clause, args, cfg := applyQueryOptions("", "deleted_at", opts...)

	tableName := "courses"
	if cfg.Table != "" {
		tableName = cfg.Table
	}

	var query string
	if !cfg.HardDelete {
		query = "UPDATE " + tableName + " SET deleted_at = CURRENT_TIMESTAMP" + clause
	} else {
		query = "DELETE FROM " + tableName + clause
	}

	res, err := db.ExecContext(ctx, query, args...)
	if err != nil {
		return 0, fmt.Errorf("deleteCourses: %w", err)
	}

	n, err := res.RowsAffected()
	if err != nil {
		return 0, fmt.Errorf("deleteCourses: detecting rows affected: %w", err)
	}

	return n, nil
}

// ================= FETCHING RELATIONS ===============================
