// Code generated by query-gen. DO NOT EDIT.
package queries

import (
	"context"
	"database/sql"
	"errors"
	"fmt"
	"time"

	"github.com/abiiranathan/query-gen/example/models"
)

// InsertOrder inserts a new Order record into the orders table.
func InsertOrder(ctx context.Context, db DBTX, m *models.Order) error {
	if db == nil {
		return errors.New("insertOrder: db is nil")
	}
	if m == nil {
		return errors.New("insertOrder: m is nil")
	}

	const query = `
		INSERT INTO orders (user_id, amount)
		VALUES ($1, $2)
		RETURNING order_id
	`

	if err := db.QueryRowContext(ctx, query, &m.UserID, &m.Amount).Scan(&m.ID); err != nil {
		return fmt.Errorf("insertOrder: %w", err)
	}
	return nil
}

// GetOrderByID retrieves a single Order record from orders by its primary key.
func GetOrderByID(ctx context.Context, db DBTX, id int64) (*models.Order, error) {
	if db == nil {
		return nil, errors.New("getOrderByID: db is nil")
	}

	const query = `
		SELECT order_id, user_id, amount
		FROM orders
		WHERE order_id = $1
	`

	row := db.QueryRowContext(ctx, query, id)
	var m models.Order
	if err := row.Scan(&m.ID, &m.UserID, &m.Amount); err != nil {
		return nil, fmt.Errorf("getOrderByID(%v): %w", id, err)
	}
	return &m, nil
}

// ExistsOrderByID reports whether a Order record with the given primary key exists.
func ExistsOrderByID(ctx context.Context, db DBTX, id int64) (bool, error) {
	if db == nil {
		return false, errors.New("existsOrderByID: db is nil")
	}

	const query = `SELECT EXISTS(SELECT 1 FROM orders WHERE order_id = $1)`

	var exists bool
	if err := db.QueryRowContext(ctx, query, id).Scan(&exists); err != nil {
		return false, fmt.Errorf("existsOrderByID(%v): %w", id, err)
	}
	return exists, nil
}

// CountOrders returns total records matching optional filter criteria.
func CountOrders(ctx context.Context, db DBTX, opts ...QueryOption) (int64, error) {
	if db == nil {
		return 0, errors.New("countOrders: db is nil")
	}

	clause, args := applyQueryOptions("", opts...)
	query := "SELECT COUNT(*) FROM orders" + clause

	var count int64
	if err := db.QueryRowContext(ctx, query, args...).Scan(&count); err != nil {
		return 0, fmt.Errorf("countOrders: %w", err)
	}
	return count, nil
}

// FetchAllOrders retrieves a filtered/paginated slice of Order records without associations.
func FetchAllOrders(ctx context.Context, db DBTX, opts ...QueryOption) ([]*models.Order, error) {
	if db == nil {
		return nil, errors.New("fetchAllOrders: db is nil")
	}

	clause, args := applyQueryOptions("order_id", opts...)
	query := "SELECT order_id, user_id, amount FROM orders" + clause

	rows, err := db.QueryContext(ctx, query, args...)
	if err != nil {
		return nil, fmt.Errorf("fetchAllOrders: %w", err)
	}
	defer rows.Close()

	var items []*models.Order
	for rows.Next() {
		var m models.Order
		if err := rows.Scan(&m.ID, &m.UserID, &m.Amount); err != nil {
			return nil, fmt.Errorf("fetchAllOrders: scanning row: %w", err)
		}
		items = append(items, &m)
	}

	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("fetchAllOrders: iterating rows: %w", err)
	}

	return items, nil
}

// GetOrdersWithUserByID fetches a Order and populates its parent User (BelongsTo).
func GetOrdersWithUserByID(ctx context.Context, db DBTX, id int64) (*models.Order, error) {
	if db == nil {
		return nil, errors.New("getOrdersWithUserByID: db is nil")
	}

	const query = `
		SELECT 
			p.order_id, p.user_id, p.amount,
			c.id, c.name, c.email, c.created_at
		FROM orders p
		LEFT JOIN users c ON c.id = p.user_id
		WHERE p.order_id = $1
	`

	row := db.QueryRowContext(ctx, query, id)

	var p models.Order
	var child_ID int64
	var child_Name string
	var child_Email string
	var child_CreatedAt time.Time

	scanArgs := []any{
		&p.ID, &p.UserID, &p.Amount,
		scanNullable(&child_ID),
		scanNullable(&child_Name),
		scanNullable(&child_Email),
		scanNullable(&child_CreatedAt),
	}

	if err := row.Scan(scanArgs...); err != nil {
		return nil, fmt.Errorf("getOrdersWithUserByID(%v): %w", id, err)
	}

	if !isZero(child_ID) {
		child := models.User{
			ID:        child_ID,
			Name:      child_Name,
			Email:     child_Email,
			CreatedAt: child_CreatedAt,
		}

		p.User = &child

	}

	return &p, nil
}

// FetchAllOrdersWithUser retrieves Order records populated with their parent User (BelongsTo).
func FetchAllOrdersWithUser(ctx context.Context, db DBTX, opts ...QueryOption) ([]*models.Order, error) {
	if db == nil {
		return nil, errors.New("fetchAllOrdersWithUser: db is nil")
	}

	clause, args := applyQueryOptions("p."+"order_id", opts...)

	query := `
		SELECT 
			p.order_id, p.user_id, p.amount,
			c.id, c.name, c.email, c.created_at
		FROM orders p
		LEFT JOIN users c ON c.id = p.user_id
	` + clause

	rows, err := db.QueryContext(ctx, query, args...)
	if err != nil {
		return nil, fmt.Errorf("fetchAllOrdersWithUser: %w", err)
	}
	defer rows.Close()

	var items []*models.Order

	for rows.Next() {
		var p models.Order

		var child_ID int64
		var child_Name string
		var child_Email string
		var child_CreatedAt time.Time

		scanArgs := []any{
			&p.ID, &p.UserID, &p.Amount,
			scanNullable(&child_ID),
			scanNullable(&child_Name),
			scanNullable(&child_Email),
			scanNullable(&child_CreatedAt),
		}

		if err := rows.Scan(scanArgs...); err != nil {
			return nil, fmt.Errorf("fetchAllOrdersWithUser: scanning row: %w", err)
		}

		if !isZero(child_ID) {
			child := models.User{
				ID:        child_ID,
				Name:      child_Name,
				Email:     child_Email,
				CreatedAt: child_CreatedAt,
			}

			p.User = &child

		}

		items = append(items, &p)
	}

	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("fetchAllOrdersWithUser: iterating rows: %w", err)
	}

	return items, nil
}

// UpdateOrder updates an existing Order record in orders.
func UpdateOrder(ctx context.Context, db DBTX, m *models.Order) error {
	if db == nil {
		return errors.New("updateOrder: db is nil")
	}
	if m == nil {
		return errors.New("updateOrder: m is nil")
	}

	const query = `
		UPDATE orders
		SET user_id = $1, amount = $2
		WHERE order_id = $3
	`

	res, err := db.ExecContext(ctx, query, &m.UserID, &m.Amount, m.ID)
	if err != nil {
		return fmt.Errorf("updateOrder(%v): %w", m.ID, err)
	}

	n, err := res.RowsAffected()
	if err != nil {
		return nil
	}
	if n == 0 {
		return fmt.Errorf("updateOrder(%v): %w", m.ID, sql.ErrNoRows)
	}
	return nil
}

// DeleteOrder deletes the Order record identified by id from orders.
func DeleteOrder(ctx context.Context, db DBTX, id int64) error {
	if db == nil {
		return errors.New("deleteOrder: db is nil")
	}

	const query = `DELETE FROM orders WHERE order_id = $1`

	res, err := db.ExecContext(ctx, query, id)
	if err != nil {
		return fmt.Errorf("deleteOrder(%v): %w", id, err)
	}

	n, err := res.RowsAffected()
	if err != nil {
		return nil
	}
	if n == 0 {
		return fmt.Errorf("deleteOrder(%v): %w", id, sql.ErrNoRows)
	}
	return nil
}
