// Code generated by query-gen. DO NOT EDIT.
package queries

import (
	"context"
	"database/sql"
	"errors"
	"fmt"
	"time"

	"github.com/abiiranathan/query-gen/example/models"
)

// InsertOrder inserts a new Order record into the orders table.
func InsertOrder(ctx context.Context, db DBTX, m *models.Order) error {
	if db == nil {
		return errors.New("insertOrder: db is nil")
	}
	if m == nil {
		return errors.New("insertOrder: m is nil")
	}

	const query = `
		INSERT INTO orders (user_id, amount)
		VALUES ($1, $2)
		RETURNING order_id
	`

	if err := db.QueryRowContext(ctx, query, &m.UserID, &m.Amount).Scan(&m.ID); err != nil {
		return fmt.Errorf("insertOrder: %w", err)
	}
	return nil
}

// GetOrderByID retrieves a single Order record from orders by its primary key.
func GetOrderByID(ctx context.Context, db DBTX, id int64, opts ...QueryOption) (*models.Order, error) {
	if db == nil {
		return nil, errors.New("getOrderByID: db is nil")
	}

	cfg := parseQueryOptions(opts...)

	if cfg.PreloadAssociations {
		return getOrderByIDWithRelations(ctx, db, id, cfg)
	}

	const query = `
		SELECT order_id, user_id, amount
		FROM orders
		WHERE order_id = $1
	`

	row := db.QueryRowContext(ctx, query, id)
	var m models.Order
	if err := row.Scan(&m.ID, &m.UserID, &m.Amount); err != nil {
		return nil, fmt.Errorf("getOrderByID(%v): %w", id, err)
	}

	return &m, nil
}

// ExistsOrderByID reports whether a Order record with the given primary key exists.
func ExistsOrderByID(ctx context.Context, db DBTX, id int64) (bool, error) {
	if db == nil {
		return false, errors.New("existsOrderByID: db is nil")
	}

	const query = `SELECT EXISTS(SELECT 1 FROM orders WHERE order_id = $1)`

	var exists bool
	if err := db.QueryRowContext(ctx, query, id).Scan(&exists); err != nil {
		return false, fmt.Errorf("existsOrderByID(%v): %w", id, err)
	}
	return exists, nil
}

// CountOrders returns total records matching optional filter criteria.
func CountOrders(ctx context.Context, db DBTX, opts ...QueryOption) (int64, error) {
	if db == nil {
		return 0, errors.New("countOrders: db is nil")
	}

	clause, args, _ := applyQueryOptions("", opts...)
	query := "SELECT COUNT(*) FROM orders" + clause

	var count int64
	if err := db.QueryRowContext(ctx, query, args...).Scan(&count); err != nil {
		return 0, fmt.Errorf("countOrders: %w", err)
	}
	return count, nil
}

// FetchAllOrders retrieves a filtered/paginated slice of Order records.
func FetchAllOrders(ctx context.Context, db DBTX, opts ...QueryOption) ([]*models.Order, error) {
	if db == nil {
		return nil, errors.New("fetchAllOrders: db is nil")
	}

	clause, args, cfg := applyQueryOptions("order_id", opts...)

	if cfg.PreloadAssociations {
		return fetchAllOrdersWithRelations(ctx, db, clause, args)
	}

	query := "SELECT order_id, user_id, amount FROM orders" + clause

	rows, err := db.QueryContext(ctx, query, args...)
	if err != nil {
		return nil, fmt.Errorf("fetchAllOrders: %w", err)
	}
	defer rows.Close()

	items := make([]*models.Order, 0, 16)
	for rows.Next() {
		var m models.Order
		if err := rows.Scan(&m.ID, &m.UserID, &m.Amount); err != nil {
			return nil, fmt.Errorf("fetchAllOrders: scanning row: %w", err)
		}
		items = append(items, &m)
	}

	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("fetchAllOrders: iterating rows: %w", err)
	}

	return items, nil
}

func getOrderByIDWithRelations(ctx context.Context, db DBTX, id int64, cfg QueryOptions) (*models.Order, error) {
	const query = `
		SELECT 
			p.order_id, p.user_id, p.amount, r0.id, r0.name, r0.email, r0.created_at
		FROM orders p
		LEFT JOIN users r0 ON r0.id = p.user_id
		WHERE p.order_id = $1
	`

	rows, err := db.QueryContext(ctx, query, id)
	if err != nil {
		return nil, fmt.Errorf("getOrderByIDWithRelations(%v): %w", id, err)
	}
	defer rows.Close()

	var parent *models.Order

	seen_User := make(map[int64]bool, 4)

	for rows.Next() {
		var p models.Order

		var r0_ID int64
		var r0_Name string
		var r0_Email string
		var r0_CreatedAt time.Time

		scanArgs := []any{
			&p.ID, &p.UserID, &p.Amount,

			scanNullable(&r0_ID),
			scanNullable(&r0_Name),
			scanNullable(&r0_Email),
			scanNullable(&r0_CreatedAt),
		}

		if err := rows.Scan(scanArgs...); err != nil {
			return nil, fmt.Errorf("getOrderByIDWithRelations(%v): scanning row: %w", id, err)
		}

		if parent == nil {
			parent = &p
		}

		rPk0 := r0_ID
		if !isZero(rPk0) {
			if !seen_User[rPk0] {
				seen_User[rPk0] = true
				child := models.User{
					ID:        r0_ID,
					Name:      r0_Name,
					Email:     r0_Email,
					CreatedAt: r0_CreatedAt,
				}

				parent.User = &child

			}
		}

	}

	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("getOrderByIDWithRelations(%v): iterating rows: %w", id, err)
	}
	if parent == nil {
		return nil, fmt.Errorf("getOrderByIDWithRelations(%v): %w", id, sql.ErrNoRows)
	}

	return parent, nil
}

func fetchAllOrdersWithRelations(ctx context.Context, db DBTX, clause string, args []any) ([]*models.Order, error) {
	query := `
		WITH p AS (
			SELECT p.order_id, p.user_id, p.amount
			FROM orders p
	` + clause + `
		)
		SELECT 
			p.order_id, p.user_id, p.amount, r0.id, r0.name, r0.email, r0.created_at
		FROM p
		LEFT JOIN users r0 ON r0.id = p.user_id
		ORDER BY p.order_id ASC
	`

	rows, err := db.QueryContext(ctx, query, args...)
	if err != nil {
		return nil, fmt.Errorf("fetchAllOrdersWithRelations: %w", err)
	}
	defer rows.Close()

	items := make([]*models.Order, 0, 16)
	itemsMap := make(map[int64]*models.Order, 16)

	seen_User := make(map[int64]map[int64]bool, 16)

	for rows.Next() {
		var p models.Order

		var r0_ID int64
		var r0_Name string
		var r0_Email string
		var r0_CreatedAt time.Time

		scanArgs := []any{
			&p.ID, &p.UserID, &p.Amount,

			scanNullable(&r0_ID),
			scanNullable(&r0_Name),
			scanNullable(&r0_Email),
			scanNullable(&r0_CreatedAt),
		}

		if err := rows.Scan(scanArgs...); err != nil {
			return nil, fmt.Errorf("fetchAllOrdersWithRelations: scanning row: %w", err)
		}

		pPK := p.ID
		parent, exists := itemsMap[pPK]
		if !exists {
			parent = &p
			itemsMap[pPK] = parent
			items = append(items, parent)

			seen_User[pPK] = make(map[int64]bool, 4)

		}

		rPk0 := r0_ID
		if !isZero(rPk0) {
			if !seen_User[pPK][rPk0] {
				seen_User[pPK][rPk0] = true
				child := models.User{
					ID:        r0_ID,
					Name:      r0_Name,
					Email:     r0_Email,
					CreatedAt: r0_CreatedAt,
				}

				parent.User = &child

			}
		}

	}

	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("fetchAllOrdersWithRelations: iterating rows: %w", err)
	}

	return items, nil
}

// UpdateOrder updates an existing Order record in orders.
func UpdateOrder(ctx context.Context, db DBTX, m *models.Order) error {
	if db == nil {
		return errors.New("updateOrder: db is nil")
	}
	if m == nil {
		return errors.New("updateOrder: m is nil")
	}

	const query = `
		UPDATE orders
		SET user_id = $1, amount = $2
		WHERE order_id = $3
	`

	res, err := db.ExecContext(ctx, query, &m.UserID, &m.Amount, m.ID)
	if err != nil {
		return fmt.Errorf("updateOrder(%v): %w", m.ID, err)
	}

	n, err := res.RowsAffected()
	if err != nil {
		return nil
	}
	if n == 0 {
		return fmt.Errorf("updateOrder(%v): %w", m.ID, sql.ErrNoRows)
	}
	return nil
}

// DeleteOrder deletes the Order record identified by id from orders.
func DeleteOrder(ctx context.Context, db DBTX, id int64) error {
	if db == nil {
		return errors.New("deleteOrder: db is nil")
	}

	const query = `DELETE FROM orders WHERE order_id = $1`

	res, err := db.ExecContext(ctx, query, id)
	if err != nil {
		return fmt.Errorf("deleteOrder(%v): %w", id, err)
	}

	n, err := res.RowsAffected()
	if err != nil {
		return nil
	}
	if n == 0 {
		return fmt.Errorf("deleteOrder(%v): %w", id, sql.ErrNoRows)
	}
	return nil
}
