// Code generated by query-gen. DO NOT EDIT.
package queries

import (
	"context"
	"database/sql"
	"errors"
	"fmt"
	"slices"
	"strings"

	"github.com/abiiranathan/query-gen/example/models"
)

// InsertOrder inserts a new Order record into the orders table.
func InsertOrder(ctx context.Context, db DBTX, m *models.Order) error {
	if db == nil {
		return errors.New("insertOrder: db is nil")
	}
	if m == nil {
		return errors.New("insertOrder: m is nil")
	}

	fields := []struct {
		col        string
		val        any
		omitIfZero bool
	}{
		{col: "user_id", val: m.UserID, omitIfZero: false},
		{col: "amount", val: m.Amount, omitIfZero: false},
	}

	cols := make([]string, 0, len(fields))
	args := make([]any, 0, len(fields))
	placeholders := make([]string, 0, len(fields))

	for _, f := range fields {
		if f.omitIfZero && IsZero(f.val) {
			continue
		}
		cols = append(cols, f.col)
		args = append(args, f.val)
		placeholders = append(placeholders, fmt.Sprintf("$%d", len(args)))
	}

	var query string
	if len(cols) == 0 {
		query = "INSERT INTO orders DEFAULT VALUES RETURNING order_id, user_id, amount"
	} else {
		query = fmt.Sprintf("INSERT INTO orders (%s) VALUES (%s) RETURNING order_id, user_id, amount",
			strings.Join(cols, ", "), strings.Join(placeholders, ", "))
	}

	if err := db.QueryRowContext(ctx, query, args...).
		Scan(&m.ID, &m.UserID, &m.Amount); err != nil {
		return fmt.Errorf("insertOrder: %w", err)
	}
	return nil
}

// ============ Bulk insert ========================

// InsertOrders inserts multiple Order records into orders in efficient parameter-bounded batches.
// Automatically populates database-generated values (e.g., auto-increment primary keys, default values) back into input structs via RETURNING.
func InsertOrders(ctx context.Context, db DBTX, models []*models.Order) error {
	if db == nil {
		return errors.New("insertOrders: db is nil")
	}
	if len(models) == 0 {
		return nil
	}

	const batchSize = 499
	for i := 0; i < len(models); i += batchSize {
		end := min((i + batchSize), len(models))
		batch := models[i:end]
		if err := insertOrdersBatch(ctx, db, batch); err != nil {
			return fmt.Errorf("insertOrders: batch [%d:%d]: %w", i, end, err)
		}
	}
	return nil
}

func insertOrdersBatch(ctx context.Context, db DBTX, batch []*models.Order) error {
	if len(batch) == 0 {
		return nil
	}

	args := make([]any, 0, len(batch)*2)
	var sb strings.Builder
	sb.Grow(128 + len(batch)*2*8)
	sb.WriteString("INSERT INTO orders (user_id, amount) VALUES ")

	paramIdx := 1
	for i, m := range batch {
		if m == nil {
			return fmt.Errorf("model at index %d is nil", i)
		}
		if i > 0 {
			sb.WriteString(", ")
		}
		sb.WriteByte('(')

		sb.WriteString(getPlaceholder(paramIdx))
		paramIdx++
		args = append(args, m.UserID)
		sb.WriteString(", ")
		sb.WriteString(getPlaceholder(paramIdx))
		paramIdx++
		args = append(args, m.Amount)
		sb.WriteByte(')')
	}

	sb.WriteString(" RETURNING order_id, user_id, amount")
	rows, err := db.QueryContext(ctx, sb.String(), args...)
	if err != nil {
		return fmt.Errorf("executing bulk insert: %w", err)
	}
	defer rows.Close()

	idx := 0
	for rows.Next() {
		if idx >= len(batch) {
			return errors.New("unexpected extra row returned from insert")
		}
		m := batch[idx]
		if err := rows.Scan(&m.ID, &m.UserID, &m.Amount); err != nil {
			return fmt.Errorf("scanning row %d: %w", idx, err)
		}
		idx++
	}

	if err := rows.Err(); err != nil {
		return fmt.Errorf("iterating bulk insert rows: %w", err)
	}

	if idx < len(batch) {
		return fmt.Errorf("expected %d inserted rows, got %d", len(batch), idx)
	}

	return nil
}

// GetOrderByID retrieves a single Order record from orders by its primary key.
func GetOrderByID(ctx context.Context, db DBTX, id int64, opts ...QueryOption) (*models.Order, error) {
	if db == nil {
		return nil, errors.New("getOrderByID: db is nil")
	}

	cfg := parseQueryOptions(opts...)

	if cfg.PreloadAssociations {
		return getOrderByIDWithRelations(ctx, db, id, cfg)
	}

	const query = `
		SELECT order_id, user_id, amount
		FROM orders
		WHERE order_id = $1
	`

	row := db.QueryRowContext(ctx, query, id)
	var m models.Order
	if err := row.Scan(&m.ID, &m.UserID, &m.Amount); err != nil {
		return nil, fmt.Errorf("getOrderByID(%v): %w", id, err)
	}

	return &m, nil
}

// GetOrder retrieves a single Order record matching mandatory query options/where clause.
// Returns sql.ErrNoRows if no matching record is found.
func GetOrder(ctx context.Context, db DBTX, opts ...QueryOption) (*models.Order, error) {
	if db == nil {
		return nil, errors.New("getOrder: db is nil")
	}

	cfg := parseQueryOptions(opts...)
	if cfg.Where == "" {
		return nil, errors.New("getOrder: query options/where clause required to prevent returning arbitrary row")
	}

	pOpts := append([]QueryOption(nil), opts...)
	pOpts = append(pOpts, Limit(1))

	items, err := FetchAllOrders(ctx, db, pOpts...)
	if err != nil {
		return nil, fmt.Errorf("getOrder: %w", err)
	}
	if len(items) == 0 {
		return nil, fmt.Errorf("getOrder: %w", sql.ErrNoRows)
	}
	return items[0], nil
}

// UpdateOrderColumns updates only the specified updatable columns/fields for an existing Order record in orders.
// Column arguments can be database column names (e.g. "email") or Go field names (e.g. "Email").
func UpdateOrderColumns(ctx context.Context, db DBTX, m *models.Order, cols ...string) error {
	if db == nil {
		return errors.New("updateOrderColumns: db is nil")
	}
	if m == nil {
		return errors.New("updateOrderColumns: m is nil")
	}
	if len(cols) == 0 {
		return errors.New("updateOrderColumns: at least one column/field must be specified")
	}

	allowedColumns := []string{
		"user_id", "UserID",
		"amount", "Amount",
	}

	setClauses := make([]string, 0, len(cols))
	args := make([]any, 0, len(cols)+1)

	for _, col := range cols {
		if !slices.Contains(allowedColumns, col) {
			return fmt.Errorf("updateOrderColumns: column or field %q is not updatable", col)
		}

		var dbCol string
		var val any

		switch col {
		case "user_id", "UserID":
			dbCol = "user_id"
			val = m.UserID
		case "amount", "Amount":
			dbCol = "amount"
			val = m.Amount
		}

		args = append(args, val)
		setClauses = append(setClauses, fmt.Sprintf("%s = $%d", dbCol, len(args)))
	}

	pkClauses := make([]string, 0, 1)
	pkClauses = append(pkClauses, fmt.Sprintf("%s = $%d", "order_id", len(args)+0+1))
	query := fmt.Sprintf("UPDATE orders SET %s WHERE %s",
		strings.Join(setClauses, ", "), strings.Join(pkClauses, " AND "))

	args = append(args, m.ID)

	res, err := db.ExecContext(ctx, query, args...)
	if err != nil {
		return fmt.Errorf("updateOrderColumns(%v): %w", fmt.Sprint(m.ID), err)
	}

	n, err := res.RowsAffected()
	if err != nil {
		return fmt.Errorf("detect rows affected: %w", err)
	}
	if n == 0 {
		return fmt.Errorf("updateOrderColumns(%v): %w", fmt.Sprint(m.ID), sql.ErrNoRows)
	}
	return nil
}

// ExistsOrderByID reports whether a Order record with the given primary key exists.
func ExistsOrderByID(ctx context.Context, db DBTX, id int64, opts ...QueryOption) (bool, error) {
	if db == nil {
		return false, errors.New("existsOrderByID: db is nil")
	}

	const query = `SELECT EXISTS(SELECT 1 FROM orders WHERE order_id = $1)`

	var exists bool
	if err := db.QueryRowContext(ctx, query, id).Scan(&exists); err != nil {
		return false, fmt.Errorf("existsOrderByID(%v): %w", id, err)
	}
	return exists, nil
}

// ExistsOrder reports whether a Order record matching the mandatory query options/where clause exists.
func ExistsOrder(ctx context.Context, db DBTX, opts ...QueryOption) (bool, error) {
	if db == nil {
		return false, errors.New("existsOrder: db is nil")
	}

	cfg := parseQueryOptions(opts...)
	if cfg.Where == "" {
		return false, errors.New("existsOrder: query options/where clause required")
	}

	var whereClause string
	if cfg.Where != "" {
		whereClause = " WHERE " + cfg.Where
	}

	query := "SELECT EXISTS(SELECT 1 FROM orders" + whereClause + ")"

	var exists bool
	if err := db.QueryRowContext(ctx, query, cfg.Args...).Scan(&exists); err != nil {
		return false, fmt.Errorf("existsOrder: %w", err)
	}
	return exists, nil
}

// CountOrders returns total records matching optional filter criteria.
func CountOrders(ctx context.Context, db DBTX, opts ...QueryOption) (int64, error) {
	if db == nil {
		return 0, errors.New("countOrders: db is nil")
	}

	cfg := parseQueryOptions(opts...)

	var whereClause string
	if cfg.Where != "" {
		whereClause = " WHERE " + cfg.Where
	}

	query := "SELECT COUNT(*) FROM orders" + whereClause

	var count int64
	if err := db.QueryRowContext(ctx, query, cfg.Args...).Scan(&count); err != nil {
		return 0, fmt.Errorf("countOrders: %w", err)
	}
	return count, nil
}

// FetchAllOrders retrieves a filtered/paginated slice of Order records.
func FetchAllOrders(ctx context.Context, db DBTX, opts ...QueryOption) ([]*models.Order, error) {
	if db == nil {
		return nil, errors.New("fetchAllOrders: db is nil")
	}

	clause, args, cfg := applyQueryOptions("order_id", "", opts...)
	if cfg.PreloadAssociations {
		return fetchAllOrdersWithRelations(ctx, db, clause, args, cfg)
	}

	query := "SELECT order_id, user_id, amount FROM orders" + clause

	rows, err := db.QueryContext(ctx, query, args...)
	if err != nil {
		return nil, fmt.Errorf("fetchAllOrders: %w", err)
	}
	defer rows.Close()

	items := make([]*models.Order, 0, 16)
	for rows.Next() {
		var m models.Order
		if err := rows.Scan(&m.ID, &m.UserID, &m.Amount); err != nil {
			return nil, fmt.Errorf("fetchAllOrders: scanning row: %w", err)
		}
		items = append(items, &m)
	}

	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("fetchAllOrders: iterating rows: %w", err)
	}

	return items, nil
}

// UpdateOrder updates an existing Order record in orders.
func UpdateOrder(ctx context.Context, db DBTX, m *models.Order) error {
	if db == nil {
		return errors.New("updateOrder: db is nil")
	}
	if m == nil {
		return errors.New("updateOrder: m is nil")
	}

	const query = `
		UPDATE orders
		SET user_id = $1, amount = $2
		WHERE order_id = $3
	`

	res, err := db.ExecContext(ctx, query, &m.UserID, &m.Amount, m.ID)
	if err != nil {
		return fmt.Errorf("updateOrder(%v): %w", fmt.Sprint(m.ID), err)
	}

	n, err := res.RowsAffected()
	if err != nil {
		return fmt.Errorf("detect rows affected: %w", err)
	}
	if n == 0 {
		return fmt.Errorf("updateOrder(%v): %w", fmt.Sprint(m.ID), sql.ErrNoRows)
	}
	return nil
}

// DeleteOrder deletes the Order record identified by primary key from orders.
func DeleteOrder(ctx context.Context, db DBTX, id int64, opts ...QueryOption) error {
	if db == nil {
		return errors.New("deleteOrder: db is nil")
	}

	const query = `DELETE FROM orders WHERE order_id = $1`

	res, err := db.ExecContext(ctx, query, id)
	if err != nil {
		return fmt.Errorf("deleteOrder(%v): %w", id, err)
	}

	n, err := res.RowsAffected()
	if err != nil {
		return fmt.Errorf("detect rows affected: %w", err)
	}
	if n == 0 {
		return fmt.Errorf("deleteOrder(%v): %w", id, sql.ErrNoRows)
	}
	return nil
}

// DeleteOrders deletes records from orders matching the provided query options and returns the number of affected rows.
func DeleteOrders(ctx context.Context, db DBTX, opts ...QueryOption) (int64, error) {
	if db == nil {
		return 0, errors.New("deleteOrders: db is nil")
	}

	cfg := parseQueryOptions(opts...)
	if cfg.Where == "" {
		return 0, errors.New("deleteOrders: query options/where clause required to prevent accidental bulk deletion")
	}

	clause, args, _ := applyQueryOptions("", "", opts...)

	var query string
	query = "DELETE FROM orders" + clause

	res, err := db.ExecContext(ctx, query, args...)
	if err != nil {
		return 0, fmt.Errorf("deleteOrders: %w", err)
	}

	n, err := res.RowsAffected()
	if err != nil {
		return 0, fmt.Errorf("deleteOrders: detecting rows affected: %w", err)
	}

	return n, nil
}

// ================= FETCHING RELATIONS ===============================
func getOrderByIDWithRelations(ctx context.Context, db DBTX, id int64, cfg QueryOptions) (*models.Order, error) {
	const query = `
		SELECT 
			p.order_id, p.user_id, p.amount, r0.id, r0.name, r0.email, r0.created_at, r0.deleted_at, r0.age, r0.permissions
		FROM orders p
		LEFT JOIN users r0 ON r0.id = p.user_id AND r0.deleted_at IS NULL
		WHERE p.order_id = $1
	`

	rows, err := db.QueryContext(ctx, query, id)
	if err != nil {
		return nil, fmt.Errorf("getOrderByIDWithRelations(%v): %w", id, err)
	}
	defer rows.Close()

	var parent *models.Order
	var p models.Order

	seen_User := make(map[int64]struct{}, 4)
	var c0 models.User
	scanArgs := []any{
		&p.ID, &p.UserID, &p.Amount,
		scanNullable(&c0.ID),
		scanNullable(&c0.Name),
		scanNullable(&c0.Email),
		scanNullable(&c0.CreatedAt),
		scanNullable(&c0.DeletedAt),
		scanNullable(&c0.Age),
		scanNullable(&c0.Permissions),
	}

	for rows.Next() {
		if err := rows.Scan(scanArgs...); err != nil {
			return nil, fmt.Errorf("getOrderByIDWithRelations(%v): scanning row: %w", id, err)
		}

		if parent == nil {
			parent = &p
		}

		if !(IsZero(c0.ID)) {
			rPk0 := c0.ID
			if _, ok := seen_User[rPk0]; !ok {
				seen_User[rPk0] = struct{}{}
				child := c0
				parent.User = &child
			}
		}
	}

	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("getOrderByIDWithRelations(%v): iterating rows: %w", id, err)
	}
	if parent == nil {
		return nil, fmt.Errorf("getOrderByIDWithRelations(%v): %w", id, sql.ErrNoRows)
	}

	return parent, nil
}

func fetchAllOrdersWithRelations(ctx context.Context, db DBTX, clause string, args []any, cfg QueryOptions) ([]*models.Order, error) {
	query := `
		WITH p AS (
			SELECT p.order_id, p.user_id, p.amount
			FROM orders p
	` + clause + `
		)
		SELECT 
			p.order_id, p.user_id, p.amount, r0.id, r0.name, r0.email, r0.created_at, r0.deleted_at, r0.age, r0.permissions
		FROM p
		LEFT JOIN users r0 ON r0.id = p.user_id AND r0.deleted_at IS NULL
		ORDER BY p.order_id ASC
	`

	rows, err := db.QueryContext(ctx, query, args...)
	if err != nil {
		return nil, fmt.Errorf("fetchAllOrdersWithRelations: %w", err)
	}
	defer rows.Close()

	items := make([]*models.Order, 0, 16)
	itemsMap := make(map[int64]*models.Order, 16)

	seen_User := make(map[seenKey[int64, int64]]struct{}, 64)
	for rows.Next() {
		var p models.Order
		var c0 models.User
		scanArgs := []any{
			&p.ID, &p.UserID, &p.Amount,
			scanNullable(&c0.ID),
			scanNullable(&c0.Name),
			scanNullable(&c0.Email),
			scanNullable(&c0.CreatedAt),
			scanNullable(&c0.DeletedAt),
			scanNullable(&c0.Age),
			scanNullable(&c0.Permissions),
		}

		if err := rows.Scan(scanArgs...); err != nil {
			return nil, fmt.Errorf("fetchAllOrdersWithRelations: scanning row: %w", err)
		}

		pPK := p.ID
		parent, exists := itemsMap[pPK]
		if !exists {
			parent = &p
			itemsMap[pPK] = parent
			items = append(items, parent)
		}

		if !(IsZero(c0.ID)) {
			rPk0 := c0.ID
			key0 := seenKey[int64, int64]{parent: pPK, child: rPk0}
			if _, ok := seen_User[key0]; !ok {
				seen_User[key0] = struct{}{}
				child := c0
				parent.User = &child
			}
		}
	}

	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("fetchAllOrdersWithRelations: iterating rows: %w", err)
	}

	return items, nil
}
