// Code generated by query-gen. DO NOT EDIT.
package queries

import (
	"context"
	"database/sql"
	"errors"
	"fmt"
	"strings"

	"github.com/abiiranathan/query-gen/example/models"
)

// InsertProject inserts a new Project record into the projects table.
func InsertProject(ctx context.Context, db DBTX, m *models.Project) error {
	if db == nil {
		return errors.New("insertProject: db is nil")
	}
	if m == nil {
		return errors.New("insertProject: m is nil")
	}

	fields := []struct {
		col        string
		val        any
		omitIfZero bool
	}{
		{col: "name", val: m.Name, omitIfZero: false},
		{col: "description", val: m.Description, omitIfZero: false},
		{col: "created_at", val: m.CreatedAt, omitIfZero: true},
		{col: "deleted_at", val: m.DeletedAt, omitIfZero: false},
	}

	cols := make([]string, 0, len(fields))
	args := make([]any, 0, len(fields))
	placeholders := make([]string, 0, len(fields))

	for _, f := range fields {
		if f.omitIfZero && IsZero(f.val) {
			continue
		}
		cols = append(cols, f.col)
		args = append(args, f.val)
		placeholders = append(placeholders, fmt.Sprintf("$%d", len(args)))
	}

	var query string
	if len(cols) == 0 {
		query = "INSERT INTO projects DEFAULT VALUES RETURNING id, name, description, created_at, deleted_at"
	} else {
		query = fmt.Sprintf("INSERT INTO projects (%s) VALUES (%s) RETURNING id, name, description, created_at, deleted_at",
			strings.Join(cols, ", "), strings.Join(placeholders, ", "))
	}

	if err := db.QueryRowContext(ctx, query, args...).
		Scan(&m.ID, &m.Name, &m.Description, scanNullable(&m.CreatedAt), scanNullable(&m.DeletedAt)); err != nil {
		return fmt.Errorf("insertProject: %w", err)
	}
	return nil
}

// GetProjectByID retrieves a single Project record from projects by its primary key.
func GetProjectByID(ctx context.Context, db DBTX, id int64, opts ...QueryOption) (*models.Project, error) {
	if db == nil {
		return nil, errors.New("getProjectByID: db is nil")
	}

	cfg := parseQueryOptions(opts...)

	if cfg.PreloadAssociations {
		return getProjectByIDWithRelations(ctx, db, id, cfg)
	}

	query := `
		SELECT id, name, description, created_at, deleted_at
		FROM projects
		WHERE id = $1
	`
	if !cfg.IncludeDeleted {
		query += " AND deleted_at IS NULL"
	}

	row := db.QueryRowContext(ctx, query, id)
	var m models.Project
	if err := row.Scan(&m.ID, &m.Name, &m.Description, scanNullable(&m.CreatedAt), scanNullable(&m.DeletedAt)); err != nil {
		return nil, fmt.Errorf("getProjectByID(%v): %w", id, err)
	}

	return &m, nil
}

// ExistsProjectByID reports whether a Project record with the given primary key exists.
func ExistsProjectByID(ctx context.Context, db DBTX, id int64, opts ...QueryOption) (bool, error) {
	if db == nil {
		return false, errors.New("existsProjectByID: db is nil")
	}

	cfg := parseQueryOptions(opts...)
	query := `SELECT EXISTS(SELECT 1 FROM projects WHERE id = $1`
	if !cfg.IncludeDeleted {
		query += " AND deleted_at IS NULL"
	}
	query += ")"

	var exists bool
	if err := db.QueryRowContext(ctx, query, id).Scan(&exists); err != nil {
		return false, fmt.Errorf("existsProjectByID(%v): %w", id, err)
	}
	return exists, nil
}

// CountProjects returns total records matching optional filter criteria.
func CountProjects(ctx context.Context, db DBTX, opts ...QueryOption) (int64, error) {
	if db == nil {
		return 0, errors.New("countProjects: db is nil")
	}

	cfg := parseQueryOptions(opts...)

	var whereClause string
	if cfg.Where != "" {
		whereClause = " WHERE " + cfg.Where
	}

	if !cfg.IncludeDeleted {
		if whereClause != "" {
			whereClause += " AND deleted_at IS NULL"
		} else {
			whereClause = " WHERE deleted_at IS NULL"
		}
	}

	query := "SELECT COUNT(*) FROM projects" + whereClause

	var count int64
	if err := db.QueryRowContext(ctx, query, cfg.Args...).Scan(&count); err != nil {
		return 0, fmt.Errorf("countProjects: %w", err)
	}
	return count, nil
}

// FetchAllProjects retrieves a filtered/paginated slice of Project records.
func FetchAllProjects(ctx context.Context, db DBTX, opts ...QueryOption) ([]*models.Project, error) {
	if db == nil {
		return nil, errors.New("fetchAllProjects: db is nil")
	}

	clause, args, cfg := applyQueryOptions("id", "deleted_at", opts...)
	if cfg.PreloadAssociations {
		return fetchAllProjectsWithRelations(ctx, db, clause, args, cfg)
	}

	query := "SELECT id, name, description, created_at, deleted_at FROM projects" + clause

	rows, err := db.QueryContext(ctx, query, args...)
	if err != nil {
		return nil, fmt.Errorf("fetchAllProjects: %w", err)
	}
	defer rows.Close()

	items := make([]*models.Project, 0, 16)
	for rows.Next() {
		var m models.Project
		if err := rows.Scan(&m.ID, &m.Name, &m.Description, scanNullable(&m.CreatedAt), scanNullable(&m.DeletedAt)); err != nil {
			return nil, fmt.Errorf("fetchAllProjects: scanning row: %w", err)
		}
		items = append(items, &m)
	}

	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("fetchAllProjects: iterating rows: %w", err)
	}

	return items, nil
}

// UpdateProject updates an existing Project record in projects.
func UpdateProject(ctx context.Context, db DBTX, m *models.Project) error {
	if db == nil {
		return errors.New("updateProject: db is nil")
	}
	if m == nil {
		return errors.New("updateProject: m is nil")
	}

	const query = `
		UPDATE projects
		SET name = $1, description = $2, created_at = $3, deleted_at = $4
		WHERE id = $5
	`

	res, err := db.ExecContext(ctx, query, &m.Name, &m.Description, &m.CreatedAt, &m.DeletedAt, m.ID)
	if err != nil {
		return fmt.Errorf("updateProject(%v): %w", m.ID, err)
	}

	n, err := res.RowsAffected()
	if err != nil {
		return fmt.Errorf("detect rows affected: %w", err)
	}
	if n == 0 {
		return fmt.Errorf("updateProject(%v): %w", m.ID, sql.ErrNoRows)
	}
	return nil
}

// DeleteProject deletes the Project record identified by id from projects.
func DeleteProject(ctx context.Context, db DBTX, id int64, opts ...QueryOption) error {
	if db == nil {
		return errors.New("deleteProject: db is nil")
	}

	cfg := parseQueryOptions(opts...)
	if !cfg.HardDelete {
		const query = `UPDATE projects SET deleted_at = CURRENT_TIMESTAMP WHERE id = $1 AND deleted_at IS NULL`
		res, err := db.ExecContext(ctx, query, id)
		if err != nil {
			return fmt.Errorf("deleteProject(%v): %w", id, err)
		}
		n, err := res.RowsAffected()
		if err != nil {
			return fmt.Errorf("detect rows affected: %w", err)
		}
		if n == 0 {
			return fmt.Errorf("deleteProject(%v): %w", id, sql.ErrNoRows)
		}
		return nil
	}

	const query = `DELETE FROM projects WHERE id = $1`

	res, err := db.ExecContext(ctx, query, id)
	if err != nil {
		return fmt.Errorf("deleteProject(%v): %w", id, err)
	}

	n, err := res.RowsAffected()
	if err != nil {
		return fmt.Errorf("detect rows affected: %w", err)
	}
	if n == 0 {
		return fmt.Errorf("deleteProject(%v): %w", id, sql.ErrNoRows)
	}
	return nil
}

// DeleteProjects deletes records from projects matching the provided query options and returns the number of affected rows.
func DeleteProjects(ctx context.Context, db DBTX, opts ...QueryOption) (int64, error) {
	if db == nil {
		return 0, errors.New("deleteProjects: db is nil")
	}

	cfg := parseQueryOptions(opts...)
	if cfg.Where == "" {
		return 0, errors.New("deleteProjects: query options/where clause required to prevent accidental bulk deletion")
	}

	clause, args, cfg := applyQueryOptions("", "deleted_at", opts...)

	var query string
	if !cfg.HardDelete {
		query = "UPDATE projects SET deleted_at = CURRENT_TIMESTAMP" + clause
	} else {
		query = "DELETE FROM projects" + clause
	}

	res, err := db.ExecContext(ctx, query, args...)
	if err != nil {
		return 0, fmt.Errorf("deleteProjects: %w", err)
	}

	n, err := res.RowsAffected()
	if err != nil {
		return 0, fmt.Errorf("deleteProjects: detecting rows affected: %w", err)
	}

	return n, nil
}

// ================= FETCHING RELATIONS ===============================
func getProjectByIDWithRelations(ctx context.Context, db DBTX, id int64, cfg QueryOptions) (*models.Project, error) {
	opts := []QueryOption{PreloadAssociations(false)}
	if cfg.IncludeDeleted {
		opts = append(opts, IncludeDeleted())
	}

	m, err := GetProjectByID(ctx, db, id, opts...)
	if err != nil {
		return nil, err
	}

	{
		preloadOpts := []QueryOption{Where("project_id = $1", m.ID)}
		if cfg.IncludeDeleted {
			preloadOpts = append(preloadOpts, IncludeDeleted())
		}
		children, err := FetchAllTags(ctx, db, preloadOpts...)
		if err != nil {
			return nil, fmt.Errorf("getProjectByIDWithRelations: preloading Tags: %w", err)
		}
		m.Tags = make([]models.Tag, len(children))
		for i, child := range children {
			m.Tags[i] = *child
		}
	}

	{
		preloadOpts := []QueryOption{Where("project_id = $1", m.ID)}
		if cfg.IncludeDeleted {
			preloadOpts = append(preloadOpts, IncludeDeleted())
		}
		children, err := FetchAllCategories(ctx, db, preloadOpts...)
		if err != nil {
			return nil, fmt.Errorf("getProjectByIDWithRelations: preloading Categories: %w", err)
		}
		m.Categories = make([]models.Category, len(children))
		for i, child := range children {
			m.Categories[i] = *child
		}
	}

	{
		preloadOpts := []QueryOption{Where("project_id = $1", m.ID)}
		if cfg.IncludeDeleted {
			preloadOpts = append(preloadOpts, IncludeDeleted())
		}
		children, err := FetchAllTasks(ctx, db, preloadOpts...)
		if err != nil {
			return nil, fmt.Errorf("getProjectByIDWithRelations: preloading Tasks: %w", err)
		}
		m.Tasks = make([]models.Task, len(children))
		for i, child := range children {
			m.Tasks[i] = *child
		}
	}
	return m, nil
}

func fetchAllProjectsWithRelations(ctx context.Context, db DBTX, clause string, args []any, cfg QueryOptions) ([]*models.Project, error) {
	query := "SELECT id, name, description, created_at, deleted_at FROM projects" + clause
	rows, err := db.QueryContext(ctx, query, args...)
	if err != nil {
		return nil, fmt.Errorf("fetchAllProjectsWithRelations: %w", err)
	}
	defer rows.Close()

	items := make([]*models.Project, 0, 16)
	for rows.Next() {
		var m models.Project
		if err := rows.Scan(&m.ID, &m.Name, &m.Description, scanNullable(&m.CreatedAt), scanNullable(&m.DeletedAt)); err != nil {
			return nil, fmt.Errorf("fetchAllProjectsWithRelations: scanning row: %w", err)
		}
		items = append(items, &m)
	}
	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("fetchAllProjectsWithRelations: iterating rows: %w", err)
	}
	if len(items) == 0 {
		return items, nil
	}

	parentIDs := make([]any, 0, len(items))
	parentMap := make(map[int64]*models.Project, len(items))
	for _, item := range items {
		pk := item.ID
		if !IsZero(pk) {
			if _, exists := parentMap[pk]; !exists {
				parentMap[pk] = item
				parentIDs = append(parentIDs, pk)
			}
		}
	}

	if len(parentIDs) > 0 {
		preloadOpts := []QueryOption{}
		if cfg.IncludeDeleted {
			preloadOpts = append(preloadOpts, IncludeDeleted())
		}
		children, err := batchIn(ctx, db, parentIDs, func(ctx context.Context, db DBTX, batch []any) ([]*models.Tag, error) {
			opts := append([]QueryOption{In("project_id", batch...)}, preloadOpts...)
			return FetchAllTags(ctx, db, opts...)
		})
		if err != nil {
			return nil, fmt.Errorf("fetchAllProjectsWithRelations: preloading Tags: %w", err)
		}
		for _, child := range children {
			if parent, ok := parentMap[child.ProjectID]; ok {
				parent.Tags = append(parent.Tags, *child)
			}
		}
	}

	if len(parentIDs) > 0 {
		preloadOpts := []QueryOption{}
		if cfg.IncludeDeleted {
			preloadOpts = append(preloadOpts, IncludeDeleted())
		}
		children, err := batchIn(ctx, db, parentIDs, func(ctx context.Context, db DBTX, batch []any) ([]*models.Category, error) {
			opts := append([]QueryOption{In("project_id", batch...)}, preloadOpts...)
			return FetchAllCategories(ctx, db, opts...)
		})
		if err != nil {
			return nil, fmt.Errorf("fetchAllProjectsWithRelations: preloading Categories: %w", err)
		}
		for _, child := range children {
			if parent, ok := parentMap[child.ProjectID]; ok {
				parent.Categories = append(parent.Categories, *child)
			}
		}
	}

	if len(parentIDs) > 0 {
		preloadOpts := []QueryOption{}
		if cfg.IncludeDeleted {
			preloadOpts = append(preloadOpts, IncludeDeleted())
		}
		children, err := batchIn(ctx, db, parentIDs, func(ctx context.Context, db DBTX, batch []any) ([]*models.Task, error) {
			opts := append([]QueryOption{In("project_id", batch...)}, preloadOpts...)
			return FetchAllTasks(ctx, db, opts...)
		})
		if err != nil {
			return nil, fmt.Errorf("fetchAllProjectsWithRelations: preloading Tasks: %w", err)
		}
		for _, child := range children {
			if parent, ok := parentMap[child.ProjectID]; ok {
				parent.Tasks = append(parent.Tasks, *child)
			}
		}
	}
	return items, nil
}
