// Code generated by query-gen. DO NOT EDIT.
package queries

import (
	"context"
	"database/sql"
	"fmt"
	"math"
	"reflect"
	"strings"
	"time"
)

type DBTX interface {
	ExecContext(ctx context.Context, query string, args ...any) (sql.Result, error)
	QueryContext(ctx context.Context, query string, args ...any) (*sql.Rows, error)
	QueryRowContext(ctx context.Context, query string, args ...any) *sql.Row
}

// QueryOptions provides optional filtering, ordering, grouping, having, pagination, and association preloading for queries.
type QueryOptions struct {
	Where               string
	Args                []any
	Having              string
	OrderBy             string
	GroupBy             string
	Limit               int
	Offset              int
	PreloadAssociations bool
}

type QueryOption func(*QueryOptions)

func Where(where string, args ...any) QueryOption {
	return func(o *QueryOptions) {
		if o.Where != "" {
			o.Where += " AND " + where
		} else {
			o.Where = where
		}
		o.Args = append(o.Args, args...)
	}
}

// ILIKE performs a case-insensitive pattern match on a column using PostgreSQL ILIKE.
// It wraps the provided value with wildcard characters ("%<value>%").
// It does nothing if value is empty.
func ILIKE(column, value string) QueryOption {
	return func(o *QueryOptions) {
		if value == "" {
			return
		}

		o.Args = append(o.Args, "%"+value+"%")
		clause := fmt.Sprintf("%s LIKE $%d", column, len(o.Args))

		if o.Where != "" {
			o.Where += " AND " + clause
		} else {
			o.Where = clause
		}
	}
}

// In filters a column matching any of the provided values.
// It does nothing if values is empty.
func In(column string, values ...any) QueryOption {
	return func(o *QueryOptions) {
		if len(values) == 0 {
			return
		}

		placeholders := make([]string, 0, len(values))
		for _, v := range values {
			o.Args = append(o.Args, v)
			placeholders = append(placeholders, fmt.Sprintf("$%d", len(o.Args)))
		}

		clause := fmt.Sprintf("%s IN (%s)", column, strings.Join(placeholders, ", "))
		if o.Where != "" {
			o.Where += " AND " + clause
		} else {
			o.Where = clause
		}
	}
}

// NotIn filters a column not matching any of the provided values.
// It does nothing if values is empty.
func NotIn(column string, values ...any) QueryOption {
	return func(o *QueryOptions) {
		if len(values) == 0 {
			return
		}

		placeholders := make([]string, 0, len(values))
		for _, v := range values {
			o.Args = append(o.Args, v)
			placeholders = append(placeholders, fmt.Sprintf("$%d", len(o.Args)))
		}

		clause := fmt.Sprintf("%s NOT IN (%s)", column, strings.Join(placeholders, ", "))
		if o.Where != "" {
			o.Where += " AND " + clause
		} else {
			o.Where = clause
		}
	}
}

// IsNull filters rows where the column is NULL.
func IsNull(column string) QueryOption {
	return func(o *QueryOptions) {
		clause := fmt.Sprintf("%s IS NULL", column)
		if o.Where != "" {
			o.Where += " AND " + clause
		} else {
			o.Where = clause
		}
	}
}

// IsNotNull filters rows where the column is NOT NULL.
func IsNotNull(column string) QueryOption {
	return func(o *QueryOptions) {
		clause := fmt.Sprintf("%s IS NOT NULL", column)
		if o.Where != "" {
			o.Where += " AND " + clause
		} else {
			o.Where = clause
		}
	}
}

// Between applies a BETWEEN min AND max filter on a column.
func Between(column string, min, max any) QueryOption {
	return func(o *QueryOptions) {
		o.Args = append(o.Args, min, max)
		p1 := fmt.Sprintf("$%d", len(o.Args)-1)
		p2 := fmt.Sprintf("$%d", len(o.Args))

		clause := fmt.Sprintf("%s BETWEEN %s AND %s", column, p1, p2)
		if o.Where != "" {
			o.Where += " AND " + clause
		} else {
			o.Where = clause
		}
	}
}

// Search performs a pattern match across multiple columns.
// It does nothing if query or columns is empty.
func Search(query string, columns ...string) QueryOption {
	return func(o *QueryOptions) {
		if query == "" || len(columns) == 0 {
			return
		}

		o.Args = append(o.Args, "%"+query+"%")
		placeholder := fmt.Sprintf("$%d", len(o.Args))

		clauses := make([]string, 0, len(columns))
		for _, col := range columns {
			clauses = append(clauses, fmt.Sprintf("%s LIKE %s", col, placeholder))
		}

		groupClause := "(" + strings.Join(clauses, " OR ") + ")"
		if o.Where != "" {
			o.Where += " AND " + groupClause
		} else {
			o.Where = groupClause
		}
	}
}

// Gt applies a greater-than filter (>).
func Gt(column string, val any) QueryOption {
	return func(o *QueryOptions) {
		o.Args = append(o.Args, val)
		clause := fmt.Sprintf("%s > $%d", column, len(o.Args))
		if o.Where != "" {
			o.Where += " AND " + clause
		} else {
			o.Where = clause
		}
	}
}

// Gte applies a greater-than-or-equal filter (>=).
func Gte(column string, val any) QueryOption {
	return func(o *QueryOptions) {
		o.Args = append(o.Args, val)
		clause := fmt.Sprintf("%s >= $%d", column, len(o.Args))
		if o.Where != "" {
			o.Where += " AND " + clause
		} else {
			o.Where = clause
		}
	}
}

// Lt applies a less-than filter (<).
func Lt(column string, val any) QueryOption {
	return func(o *QueryOptions) {
		o.Args = append(o.Args, val)
		clause := fmt.Sprintf("%s < $%d", column, len(o.Args))
		if o.Where != "" {
			o.Where += " AND " + clause
		} else {
			o.Where = clause
		}
	}
}

// Lte applies a less-than-or-equal filter (<=).
func Lte(column string, val any) QueryOption {
	return func(o *QueryOptions) {
		o.Args = append(o.Args, val)
		clause := fmt.Sprintf("%s <= $%d", column, len(o.Args))
		if o.Where != "" {
			o.Where += " AND " + clause
		} else {
			o.Where = clause
		}
	}
}

func Having(having string, args ...any) QueryOption {
	return func(o *QueryOptions) {
		if o.Having != "" {
			o.Having += " AND " + having
		} else {
			o.Having = having
		}
		o.Args = append(o.Args, args...)
	}
}

func OrderBy(orderBy string) QueryOption {
	return func(o *QueryOptions) {
		o.OrderBy = orderBy
	}
}

func GroupBy(groupBy string) QueryOption {
	return func(o *QueryOptions) {
		o.GroupBy = groupBy
	}
}

func Limit(limit int) QueryOption {
	return func(o *QueryOptions) {
		o.Limit = limit
	}
}

func Offset(offset int) QueryOption {
	return func(o *QueryOptions) {
		o.Offset = offset
	}
}

// WithPreloadAssociations enables or disables preloading associated model relations.
func PreloadAssociations(preload bool) QueryOption {
	return func(o *QueryOptions) {
		o.PreloadAssociations = preload
	}
}

// DateRange applies date range filter on a date column.
// e.g DateRange("DATE(created_at)", "2021-01-01", "2021-12-31")
// It does nothing if start or end is empty.
func DateRange(column string, start, end string) QueryOption {
	return func(o *QueryOptions) {
		if start != "" && end != "" {
			o.Args = append(o.Args, start, end)
			placeholder1 := fmt.Sprintf("$%d", len(o.Args)-1)
			placeholder2 := fmt.Sprintf("$%d", len(o.Args))
			clause := fmt.Sprintf("%s BETWEEN %s AND %s", column, placeholder1, placeholder2)
			if o.Where != "" {
				o.Where += " AND " + clause
			} else {
				o.Where = clause
			}
		} else if start != "" {
			o.Args = append(o.Args, start)
			clause := fmt.Sprintf("%s >= $%d", column, len(o.Args))
			if o.Where != "" {
				o.Where += " AND " + clause
			} else {
				o.Where = clause
			}
		} else if end != "" {
			o.Args = append(o.Args, end)
			clause := fmt.Sprintf("%s <= $%d", column, len(o.Args))
			if o.Where != "" {
				o.Where += " AND " + clause
			} else {
				o.Where = clause
			}
		}
	}
}

// MonthRange is the same as DateRange but truncates the date to month.
// e.g MonthRange("DATE(created_at)", "2021-01-01", "2021-12-31")
// It does nothing if start or end is empty.
func MonthRange(column string, start, end string) QueryOption {
	return func(o *QueryOptions) {
		if start != "" && end != "" {
			o.Args = append(o.Args, start, end)
			p1 := fmt.Sprintf("$%d", len(o.Args)-1)
			p2 := fmt.Sprintf("$%d", len(o.Args))
			clause := fmt.Sprintf("%s BETWEEN DATE_TRUNC('month', %s::DATE) AND DATE_TRUNC('month', %s::DATE)", column, p1, p2)
			if o.Where != "" {
				o.Where += " AND " + clause
			} else {
				o.Where = clause
			}
		} else if start != "" {
			o.Args = append(o.Args, start)
			clause := fmt.Sprintf("%s >= DATE_TRUNC('month', $%d::DATE)", column, len(o.Args))
			if o.Where != "" {
				o.Where += " AND " + clause
			} else {
				o.Where = clause
			}
		} else if end != "" {
			o.Args = append(o.Args, end)
			clause := fmt.Sprintf("%s <= DATE_TRUNC('month', $%d::DATE)", column, len(o.Args))
			if o.Where != "" {
				o.Where += " AND " + clause
			} else {
				o.Where = clause
			}
		}
	}
}

// YearRange is the same as date range but truncates the date to year.
// e.g YearRange("DATE(created_at)", "2021-01-01", "2024-12-31")
// It does nothing if start or end is empty.
func YearRange(column string, start, end string) QueryOption {
	return func(o *QueryOptions) {
		if start != "" && end != "" {
			o.Args = append(o.Args, start, end)
			p1 := fmt.Sprintf("$%d", len(o.Args)-1)
			p2 := fmt.Sprintf("$%d", len(o.Args))
			clause := fmt.Sprintf("%s BETWEEN DATE_TRUNC('year', %s::DATE) AND DATE_TRUNC('year', %s::DATE)", column, p1, p2)
			if o.Where != "" {
				o.Where += " AND " + clause
			} else {
				o.Where = clause
			}
		} else if start != "" {
			o.Args = append(o.Args, start)
			clause := fmt.Sprintf("%s >= DATE_TRUNC('year', $%d::DATE)", column, len(o.Args))
			if o.Where != "" {
				o.Where += " AND " + clause
			} else {
				o.Where = clause
			}
		} else if end != "" {
			o.Args = append(o.Args, end)
			clause := fmt.Sprintf("%s <= DATE_TRUNC('year', $%d::DATE)", column, len(o.Args))
			if o.Where != "" {
				o.Where += " AND " + clause
			} else {
				o.Where = clause
			}
		}
	}
}

func parseQueryOptions(opts ...QueryOption) QueryOptions {
	var cfg QueryOptions
	for _, opt := range opts {
		if opt != nil {
			opt(&cfg)
		}
	}
	return cfg
}

func applyQueryOptions(defaultPK string, opts ...QueryOption) (string, []any, QueryOptions) {
	cfg := parseQueryOptions(opts...)

	var sb strings.Builder
	args := cfg.Args

	if cfg.Where != "" {
		sb.WriteString(" WHERE ")
		sb.WriteString(cfg.Where)
	}

	if cfg.GroupBy != "" {
		sb.WriteString(" GROUP BY ")
		sb.WriteString(cfg.GroupBy)
	}

	if cfg.Having != "" {
		sb.WriteString(" HAVING ")
		sb.WriteString(cfg.Having)
	}

	if cfg.OrderBy != "" {
		sb.WriteString(" ORDER BY ")
		sb.WriteString(cfg.OrderBy)
	} else if defaultPK != "" {
		sb.WriteString(" ORDER BY ")
		sb.WriteString(defaultPK)
		sb.WriteString(" ASC")
	}

	if cfg.Limit > 0 {
		args = append(args, cfg.Limit)
		fmt.Fprintf(&sb, " LIMIT $%d", len(args))
	}

	if cfg.Offset > 0 {
		args = append(args, cfg.Offset)
		fmt.Fprintf(&sb, " OFFSET $%d", len(args))
	}

	return sb.String(), args, cfg
}

// PaginationResult holds the output of a paginated query.
type PaginationResult[T any] struct {
	Page       int   `json:"page"`
	PageSize   int   `json:"page_size"`
	TotalPages int64 `json:"total_pages"`
	Count      int64 `json:"count"`
	HasNext    bool  `json:"has_next"`
	HasPrev    bool  `json:"has_prev"`
	Results    []T   `json:"results"`
}

// FetchFunc defines a function signature capable of fetching records using DBTX and QueryOptions.
type FetchFunc[T any] func(ctx context.Context, db DBTX, opts ...QueryOption) ([]T, error)

// CountFunc defines a function signature capable of counting total matching rows using DBTX and QueryOptions.
type CountFunc func(ctx context.Context, db DBTX, opts ...QueryOption) (int64, error)

// Paginate executes a paginated query using DBTX, counting total rows and retrieving the requested page.
func Paginate[T any](ctx context.Context, db DBTX, countFn CountFunc, fetchFn FetchFunc[T], page, pageSize int, opts ...QueryOption) (*PaginationResult[T], error) {
	if page < 1 {
		page = 1
	}
	if pageSize < 1 {
		pageSize = 10
	}

	totalCount, err := countFn(ctx, db, opts...)
	if err != nil {
		return nil, fmt.Errorf("paginate: counting total rows: %w", err)
	}

	// Append pagination limit and offset options
	pOpts := append([]QueryOption(nil), opts...)
	pOpts = append(pOpts, Limit(pageSize), Offset((page-1)*pageSize))

	results, err := fetchFn(ctx, db, pOpts...)
	if err != nil {
		return nil, fmt.Errorf("paginate: fetching page results: %w", err)
	}

	if results == nil {
		results = make([]T, 0)
	}

	return &PaginationResult[T]{
		Page:       page,
		PageSize:   pageSize,
		HasNext:    int64(page*pageSize) < totalCount,
		HasPrev:    page > 1,
		Results:    results,
		Count:      totalCount,
		TotalPages: int64(math.Ceil(float64(totalCount) / float64(pageSize))),
	}, nil
}

func scanNullable[T any](dst *T) *nullableScanner[T] {
	return &nullableScanner[T]{dst: dst}
}

type nullableScanner[T any] struct {
	dst *T
}

func (n *nullableScanner[T]) Scan(src any) error {
	if src == nil {
		var zero T
		*n.dst = zero
		return nil
	}

	if v, ok := src.(T); ok {
		*n.dst = v
		return nil
	}

	if scanner, ok := any(n.dst).(sql.Scanner); ok {
		return scanner.Scan(src)
	}

	return convertAssign(n.dst, src)
}

func convertAssign[T any](dst *T, src any) error {
	if src == nil {
		var zero T
		*dst = zero
		return nil
	}

	if v, ok := src.(T); ok {
		*dst = v
		return nil
	}

	switch p := any(dst).(type) {
	case *string:
		switch s := src.(type) {
		case []byte:
			*p = string(s)
			return nil
		case string:
			*p = s
			return nil
		}
	case *[]byte:
		switch s := src.(type) {
		case string:
			*p = []byte(s)
			return nil
		case []byte:
			cp := make([]byte, len(s))
			copy(cp, s)
			*p = cp
			return nil
		}
	case *time.Time:
		switch s := src.(type) {
		case string:
			t, err := time.Parse(time.RFC3339, s)
			if err != nil {
				return fmt.Errorf("convertAssign: failed to parse time string %q: %w", s, err)
			}
			*p = t
			return nil
		case []byte:
			t, err := time.Parse(time.RFC3339, string(s))
			if err != nil {
				return fmt.Errorf("convertAssign: failed to parse time bytes %q: %w", s, err)
			}
			*p = t
			return nil
		}
	case *int:
		if i, ok := toInt64(src); ok {
			*p = int(i)
			return nil
		}
	case *int8:
		if i, ok := toInt64(src); ok {
			*p = int8(i)
			return nil
		}
	case *int16:
		if i, ok := toInt64(src); ok {
			*p = int16(i)
			return nil
		}
	case *int32:
		if i, ok := toInt64(src); ok {
			*p = int32(i)
			return nil
		}
	case *int64:
		if i, ok := toInt64(src); ok {
			*p = i
			return nil
		}
	case *uint:
		if u, ok := toUint64(src); ok {
			*p = uint(u)
			return nil
		}
	case *uint8:
		if u, ok := toUint64(src); ok {
			*p = uint8(u)
			return nil
		}
	case *uint16:
		if u, ok := toUint64(src); ok {
			*p = uint16(u)
			return nil
		}
	case *uint32:
		if u, ok := toUint64(src); ok {
			*p = uint32(u)
			return nil
		}
	case *uint64:
		if u, ok := toUint64(src); ok {
			*p = u
			return nil
		}
	case *float32:
		if f, ok := toFloat64(src); ok {
			*p = float32(f)
			return nil
		}
	case *float64:
		if f, ok := toFloat64(src); ok {
			*p = f
			return nil
		}
	}

	vDst := reflect.ValueOf(dst).Elem()
	vSrc := reflect.ValueOf(src)

	if vSrc.Type().ConvertibleTo(vDst.Type()) {
		vDst.Set(vSrc.Convert(vDst.Type()))
		return nil
	}

	return fmt.Errorf("scanNullable: cannot convert %T (%v) to %T", src, src, dst)
}

func toInt64(src any) (int64, bool) {
	switch v := src.(type) {
	case int:
		return int64(v), true
	case int8:
		return int64(v), true
	case int16:
		return int64(v), true
	case int32:
		return int64(v), true
	case int64:
		return v, true
	case uint:
		return int64(v), true
	case uint8:
		return int64(v), true
	case uint16:
		return int64(v), true
	case uint32:
		return int64(v), true
	case uint64:
		return int64(v), true
	default:
		return 0, false
	}
}

func toUint64(src any) (uint64, bool) {
	switch v := src.(type) {
	case int:
		return uint64(v), true
	case int8:
		return uint64(v), true
	case int16:
		return uint64(v), true
	case int32:
		return uint64(v), true
	case int64:
		return uint64(v), true
	case uint:
		return uint64(v), true
	case uint8:
		return uint64(v), true
	case uint16:
		return uint64(v), true
	case uint32:
		return uint64(v), true
	case uint64:
		return v, true
	default:
		return 0, false
	}
}

func toFloat64(src any) (float64, bool) {
	switch v := src.(type) {
	case float32:
		return float64(v), true
	case float64:
		return v, true
	case int:
		return float64(v), true
	case int64:
		return float64(v), true
	case uint64:
		return float64(v), true
	default:
		return 0, false
	}
}

func isZero[T comparable](v T) bool {
	var zero T
	return v == zero
}
