// Code generated by query-gen. DO NOT EDIT.
package queries

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strings"
	"time"
)

type DBTX interface {
	ExecContext(ctx context.Context, query string, args ...any) (sql.Result, error)
	QueryContext(ctx context.Context, query string, args ...any) (*sql.Rows, error)
	QueryRowContext(ctx context.Context, query string, args ...any) *sql.Row
}

// QueryOptions provides optional filtering, ordering, grouping, and pagination for queries.
type QueryOptions struct {
	Where   string
	Args    []any
	OrderBy string
	GroupBy string
	Limit   int
	Offset  int
}

type QueryOption func(*QueryOptions)

func WithWhere(where string, args ...any) QueryOption {
	return func(o *QueryOptions) {
		o.Where = where
		o.Args = append(o.Args, args...)
	}
}

func WithOrderBy(orderBy string) QueryOption {
	return func(o *QueryOptions) {
		o.OrderBy = orderBy
	}
}

func WithGroupBy(groupBy string) QueryOption {
	return func(o *QueryOptions) {
		o.GroupBy = groupBy
	}
}

func WithLimit(limit int) QueryOption {
	return func(o *QueryOptions) {
		o.Limit = limit
	}
}

func WithOffset(offset int) QueryOption {
	return func(o *QueryOptions) {
		o.Offset = offset
	}
}

func applyQueryOptions(defaultPK string, opts ...QueryOption) (string, []any) {
	var cfg QueryOptions
	for _, opt := range opts {
		if opt != nil {
			opt(&cfg)
		}
	}

	var sb strings.Builder
	args := cfg.Args

	if cfg.Where != "" {
		sb.WriteString(" WHERE ")
		sb.WriteString(cfg.Where)
	}

	if cfg.GroupBy != "" {
		sb.WriteString(" GROUP BY ")
		sb.WriteString(cfg.GroupBy)
	}

	if cfg.OrderBy != "" {
		sb.WriteString(" ORDER BY ")
		sb.WriteString(cfg.OrderBy)
	} else if defaultPK != "" {
		sb.WriteString(" ORDER BY ")
		sb.WriteString(defaultPK)
		sb.WriteString(" ASC")
	}

	if cfg.Limit > 0 {
		args = append(args, cfg.Limit)
		fmt.Fprintf(&sb, " LIMIT $%d", len(args))
	}

	if cfg.Offset > 0 {
		args = append(args, cfg.Offset)
		fmt.Fprintf(&sb, " OFFSET $%d", len(args))
	}

	return sb.String(), args
}

func scanNullable[T any](dst *T) *nullableScanner[T] {
	return &nullableScanner[T]{dst: dst}
}

type nullableScanner[T any] struct {
	dst *T
}

func (n *nullableScanner[T]) Scan(src any) error {
	if src == nil {
		var zero T
		*n.dst = zero
		return nil
	}

	if scanner, ok := any(n.dst).(sql.Scanner); ok {
		return scanner.Scan(src)
	}

	if v, ok := src.(T); ok {
		*n.dst = v
		return nil
	}

	return convertAssign(n.dst, src)
}

func convertAssign[T any](dst *T, src any) error {
	if src == nil {
		var zero T
		*dst = zero
		return nil
	}

	if v, ok := src.(T); ok {
		*dst = v
		return nil
	}

	vDst := reflect.ValueOf(dst).Elem()
	vSrc := reflect.ValueOf(src)

	if vSrc.Type().ConvertibleTo(vDst.Type()) {
		vDst.Set(vSrc.Convert(vDst.Type()))
		return nil
	}

	if vDst.Kind() == reflect.String && vSrc.Kind() == reflect.Slice && vSrc.Type().Elem().Kind() == reflect.Uint8 {
		vDst.SetString(string(vSrc.Bytes()))
		return nil
	}
	if vDst.Kind() == reflect.Slice && vDst.Type().Elem().Kind() == reflect.Uint8 && vSrc.Kind() == reflect.String {
		vDst.SetBytes([]byte(vSrc.String()))
		return nil
	}

	if _, ok := any(dst).(*time.Time); ok {
		switch s := src.(type) {
		case string:
			t, err := time.Parse(time.RFC3339, s)
			if err != nil {
				return fmt.Errorf("convertAssign: failed to parse time string %q: %w", s, err)
			}
			vDst.Set(reflect.ValueOf(t))
			return nil
		case []byte:
			t, err := time.Parse(time.RFC3339, string(s))
			if err != nil {
				return fmt.Errorf("convertAssign: failed to parse time bytes %q: %w", s, err)
			}
			vDst.Set(reflect.ValueOf(t))
			return nil
		}
	}

	if isNumeric(vDst.Kind()) && isNumeric(vSrc.Kind()) {
		if vDst.Kind() >= reflect.Int && vDst.Kind() <= reflect.Int64 {
			vDst.SetInt(vSrc.Int())
			return nil
		}
		if vDst.Kind() >= reflect.Uint && vDst.Kind() <= reflect.Uint64 {
			vDst.SetUint(vSrc.Uint())
			return nil
		}
		if vDst.Kind() == reflect.Float32 || vDst.Kind() == reflect.Float64 {
			vDst.SetFloat(vSrc.Float())
			return nil
		}
	}

	return fmt.Errorf("scanNullable: cannot convert %T (%v) to %T", src, src, dst)
}

func isNumeric(k reflect.Kind) bool {
	return (k >= reflect.Int && k <= reflect.Complex128)
}

func isZero[T comparable](v T) bool {
	var zero T
	return v == zero
}
