// Code generated by query-gen. DO NOT EDIT.
package queries

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strings"
	"time"
)

type DBTX interface {
	ExecContext(ctx context.Context, query string, args ...any) (sql.Result, error)
	QueryContext(ctx context.Context, query string, args ...any) (*sql.Rows, error)
	QueryRowContext(ctx context.Context, query string, args ...any) *sql.Row
}

// QueryOptions provides optional filtering, ordering, grouping, pagination, and association preloading for queries.
type QueryOptions struct {
	Where               string
	Args                []any
	OrderBy             string
	GroupBy             string
	Limit               int
	Offset              int
	PreloadAssociations bool
}

type QueryOption func(*QueryOptions)

func WithWhere(where string, args ...any) QueryOption {
	return func(o *QueryOptions) {
		o.Where = where
		o.Args = append(o.Args, args...)
	}
}

func WithOrderBy(orderBy string) QueryOption {
	return func(o *QueryOptions) {
		o.OrderBy = orderBy
	}
}

func WithGroupBy(groupBy string) QueryOption {
	return func(o *QueryOptions) {
		o.GroupBy = groupBy
	}
}

func WithLimit(limit int) QueryOption {
	return func(o *QueryOptions) {
		o.Limit = limit
	}
}

func WithOffset(offset int) QueryOption {
	return func(o *QueryOptions) {
		o.Offset = offset
	}
}

// WithPreloadAssociations enables or disables preloading associated model relations.
func WithPreloadAssociations(preload bool) QueryOption {
	return func(o *QueryOptions) {
		o.PreloadAssociations = preload
	}
}

func parseQueryOptions(opts ...QueryOption) QueryOptions {
	var cfg QueryOptions
	for _, opt := range opts {
		if opt != nil {
			opt(&cfg)
		}
	}
	return cfg
}

func applyQueryOptions(defaultPK string, opts ...QueryOption) (string, []any, QueryOptions) {
	cfg := parseQueryOptions(opts...)

	var sb strings.Builder
	args := cfg.Args

	if cfg.Where != "" {
		sb.WriteString(" WHERE ")
		sb.WriteString(cfg.Where)
	}

	if cfg.GroupBy != "" {
		sb.WriteString(" GROUP BY ")
		sb.WriteString(cfg.GroupBy)
	}

	if cfg.OrderBy != "" {
		sb.WriteString(" ORDER BY ")
		sb.WriteString(cfg.OrderBy)
	} else if defaultPK != "" {
		sb.WriteString(" ORDER BY ")
		sb.WriteString(defaultPK)
		sb.WriteString(" ASC")
	}

	if cfg.Limit > 0 {
		args = append(args, cfg.Limit)
		fmt.Fprintf(&sb, " LIMIT $%d", len(args))
	}

	if cfg.Offset > 0 {
		args = append(args, cfg.Offset)
		fmt.Fprintf(&sb, " OFFSET $%d", len(args))
	}

	return sb.String(), args, cfg
}

func scanNullable[T any](dst *T) *nullableScanner[T] {
	return &nullableScanner[T]{dst: dst}
}

type nullableScanner[T any] struct {
	dst *T
}

func (n *nullableScanner[T]) Scan(src any) error {
	if src == nil {
		var zero T
		*n.dst = zero
		return nil
	}

	if v, ok := src.(T); ok {
		*n.dst = v
		return nil
	}

	if scanner, ok := any(n.dst).(sql.Scanner); ok {
		return scanner.Scan(src)
	}

	return convertAssign(n.dst, src)
}

func convertAssign[T any](dst *T, src any) error {
	if src == nil {
		var zero T
		*dst = zero
		return nil
	}

	if v, ok := src.(T); ok {
		*dst = v
		return nil
	}

	switch p := any(dst).(type) {
	case *string:
		switch s := src.(type) {
		case []byte:
			*p = string(s)
			return nil
		case string:
			*p = s
			return nil
		}
	case *[]byte:
		switch s := src.(type) {
		case string:
			*p = []byte(s)
			return nil
		case []byte:
			cp := make([]byte, len(s))
			copy(cp, s)
			*p = cp
			return nil
		}
	case *time.Time:
		switch s := src.(type) {
		case string:
			t, err := time.Parse(time.RFC3339, s)
			if err != nil {
				return fmt.Errorf("convertAssign: failed to parse time string %q: %w", s, err)
			}
			*p = t
			return nil
		case []byte:
			t, err := time.Parse(time.RFC3339, string(s))
			if err != nil {
				return fmt.Errorf("convertAssign: failed to parse time bytes %q: %w", s, err)
			}
			*p = t
			return nil
		}
	case *int:
		if i, ok := toInt64(src); ok {
			*p = int(i)
			return nil
		}
	case *int8:
		if i, ok := toInt64(src); ok {
			*p = int8(i)
			return nil
		}
	case *int16:
		if i, ok := toInt64(src); ok {
			*p = int16(i)
			return nil
		}
	case *int32:
		if i, ok := toInt64(src); ok {
			*p = int32(i)
			return nil
		}
	case *int64:
		if i, ok := toInt64(src); ok {
			*p = i
			return nil
		}
	case *uint:
		if u, ok := toUint64(src); ok {
			*p = uint(u)
			return nil
		}
	case *uint8:
		if u, ok := toUint64(src); ok {
			*p = uint8(u)
			return nil
		}
	case *uint16:
		if u, ok := toUint64(src); ok {
			*p = uint16(u)
			return nil
		}
	case *uint32:
		if u, ok := toUint64(src); ok {
			*p = uint32(u)
			return nil
		}
	case *uint64:
		if u, ok := toUint64(src); ok {
			*p = u
			return nil
		}
	case *float32:
		if f, ok := toFloat64(src); ok {
			*p = float32(f)
			return nil
		}
	case *float64:
		if f, ok := toFloat64(src); ok {
			*p = f
			return nil
		}
	}

	vDst := reflect.ValueOf(dst).Elem()
	vSrc := reflect.ValueOf(src)

	if vSrc.Type().ConvertibleTo(vDst.Type()) {
		vDst.Set(vSrc.Convert(vDst.Type()))
		return nil
	}

	return fmt.Errorf("scanNullable: cannot convert %T (%v) to %T", src, src, dst)
}

func toInt64(src any) (int64, bool) {
	switch v := src.(type) {
	case int:
		return int64(v), true
	case int8:
		return int64(v), true
	case int16:
		return int64(v), true
	case int32:
		return int64(v), true
	case int64:
		return v, true
	case uint:
		return int64(v), true
	case uint8:
		return int64(v), true
	case uint16:
		return int64(v), true
	case uint32:
		return int64(v), true
	case uint64:
		return int64(v), true
	default:
		return 0, false
	}
}

func toUint64(src any) (uint64, bool) {
	switch v := src.(type) {
	case int:
		return uint64(v), true
	case int8:
		return uint64(v), true
	case int16:
		return uint64(v), true
	case int32:
		return uint64(v), true
	case int64:
		return uint64(v), true
	case uint:
		return uint64(v), true
	case uint8:
		return uint64(v), true
	case uint16:
		return uint64(v), true
	case uint32:
		return uint64(v), true
	case uint64:
		return v, true
	default:
		return 0, false
	}
}

func toFloat64(src any) (float64, bool) {
	switch v := src.(type) {
	case float32:
		return float64(v), true
	case float64:
		return v, true
	case int:
		return float64(v), true
	case int64:
		return float64(v), true
	case uint64:
		return float64(v), true
	default:
		return 0, false
	}
}

func isZero[T comparable](v T) bool {
	var zero T
	return v == zero
}
