// Code generated by query-gen. DO NOT EDIT.
package queries

import (
	"context"
	"database/sql"
	"errors"
	"fmt"
	"slices"
	"strings"

	"github.com/abiiranathan/query-gen/example/models"
)

// InsertStudent inserts a new Student record into the students table.
func InsertStudent(ctx context.Context, db DBTX, m *models.Student) error {
	if db == nil {
		return errors.New("insertStudent: db is nil")
	}
	if m == nil {
		return errors.New("insertStudent: m is nil")
	}

	fields := []struct {
		col        string
		val        any
		omitIfZero bool
	}{
		{col: "name", val: m.Name, omitIfZero: false},
		{col: "email", val: m.Email, omitIfZero: false},
		{col: "created_at", val: m.CreatedAt, omitIfZero: true},
	}

	cols := make([]string, 0, len(fields))
	args := make([]any, 0, len(fields))
	placeholders := make([]string, 0, len(fields))

	for _, f := range fields {
		if f.omitIfZero && IsZero(f.val) {
			continue
		}
		cols = append(cols, f.col)
		args = append(args, f.val)
		placeholders = append(placeholders, fmt.Sprintf("$%d", len(args)))
	}

	var query string
	if len(cols) == 0 {
		query = "INSERT INTO students DEFAULT VALUES RETURNING id, name, email, created_at, deleted_at"
	} else {
		query = fmt.Sprintf("INSERT INTO students (%s) VALUES (%s) RETURNING id, name, email, created_at, deleted_at",
			strings.Join(cols, ", "), strings.Join(placeholders, ", "))
	}

	if err := db.QueryRowContext(ctx, query, args...).
		Scan(&m.ID, &m.Name, &m.Email, scanNullable(&m.CreatedAt), scanNullable(&m.DeletedAt)); err != nil {
		return fmt.Errorf("insertStudent: %w", err)
	}
	return nil
}

// ============ Bulk insert ========================

// InsertStudents inserts multiple Student records into students in efficient parameter-bounded batches.
// Automatically populates database-generated values (e.g., auto-increment primary keys, default values) back into input structs via RETURNING.
func InsertStudents(ctx context.Context, db DBTX, models []*models.Student) error {
	if db == nil {
		return errors.New("insertStudents: db is nil")
	}
	if len(models) == 0 {
		return nil
	}

	const batchSize = 333
	for i := 0; i < len(models); i += batchSize {
		end := min((i + batchSize), len(models))
		batch := models[i:end]
		if err := insertStudentsBatch(ctx, db, batch); err != nil {
			return fmt.Errorf("insertStudents: batch [%d:%d]: %w", i, end, err)
		}
	}
	return nil
}

func insertStudentsBatch(ctx context.Context, db DBTX, batch []*models.Student) error {
	if len(batch) == 0 {
		return nil
	}

	args := make([]any, 0, len(batch)*3)
	var sb strings.Builder
	sb.Grow(128 + len(batch)*3*8)
	sb.WriteString("INSERT INTO students (name, email, created_at) VALUES ")

	paramIdx := 1
	for i, m := range batch {
		if m == nil {
			return fmt.Errorf("model at index %d is nil", i)
		}
		if i > 0 {
			sb.WriteString(", ")
		}
		sb.WriteByte('(')

		sb.WriteString(getPlaceholder(paramIdx))
		paramIdx++
		args = append(args, m.Name)
		sb.WriteString(", ")
		sb.WriteString(getPlaceholder(paramIdx))
		paramIdx++
		args = append(args, m.Email)
		sb.WriteString(", ")
		sb.WriteString(getPlaceholder(paramIdx))
		paramIdx++
		args = append(args, m.CreatedAt)
		sb.WriteByte(')')
	}

	sb.WriteString(" RETURNING id, name, email, created_at, deleted_at")
	rows, err := db.QueryContext(ctx, sb.String(), args...)
	if err != nil {
		return fmt.Errorf("executing bulk insert: %w", err)
	}
	defer rows.Close()

	idx := 0
	for rows.Next() {
		if idx >= len(batch) {
			return errors.New("unexpected extra row returned from insert")
		}
		m := batch[idx]
		if err := rows.Scan(&m.ID, &m.Name, &m.Email, scanNullable(&m.CreatedAt), scanNullable(&m.DeletedAt)); err != nil {
			return fmt.Errorf("scanning row %d: %w", idx, err)
		}
		idx++
	}

	if err := rows.Err(); err != nil {
		return fmt.Errorf("iterating bulk insert rows: %w", err)
	}

	if idx < len(batch) {
		return fmt.Errorf("expected %d inserted rows, got %d", len(batch), idx)
	}

	return nil
}

// GetStudentByID retrieves a single Student record from students by its primary key.
func GetStudentByID(ctx context.Context, db DBTX, id int64, opts ...QueryOption) (*models.Student, error) {
	if db == nil {
		return nil, errors.New("getStudentByID: db is nil")
	}

	cfg := parseQueryOptions(opts...)

	if cfg.PreloadAssociations {
		return getStudentByIDWithRelations(ctx, db, id, cfg)
	}

	query := `
		SELECT id, name, email, created_at, deleted_at
		FROM students
		WHERE id = $1
	`
	if !cfg.IncludeDeleted {
		query += " AND deleted_at IS NULL"
	}

	row := db.QueryRowContext(ctx, query, id)
	var m models.Student
	if err := row.Scan(&m.ID, &m.Name, &m.Email, scanNullable(&m.CreatedAt), scanNullable(&m.DeletedAt)); err != nil {
		return nil, fmt.Errorf("getStudentByID(%v): %w", id, err)
	}

	return &m, nil
}

// GetStudent retrieves a single Student record matching mandatory query options/where clause.
// Returns sql.ErrNoRows if no matching record is found.
func GetStudent(ctx context.Context, db DBTX, opts ...QueryOption) (*models.Student, error) {
	if db == nil {
		return nil, errors.New("getStudent: db is nil")
	}

	cfg := parseQueryOptions(opts...)
	if cfg.Where == "" {
		return nil, errors.New("getStudent: query options/where clause required to prevent returning arbitrary row")
	}

	pOpts := append([]QueryOption(nil), opts...)
	pOpts = append(pOpts, Limit(1))

	items, err := FetchAllStudents(ctx, db, pOpts...)
	if err != nil {
		return nil, fmt.Errorf("getStudent: %w", err)
	}
	if len(items) == 0 {
		return nil, fmt.Errorf("getStudent: %w", sql.ErrNoRows)
	}
	return items[0], nil
}

// UpdateStudentColumns updates only the specified updatable columns/fields for an existing Student record in students.
// Column arguments can be database column names (e.g. "email") or Go field names (e.g. "Email").
func UpdateStudentColumns(ctx context.Context, db DBTX, m *models.Student, cols ...string) error {
	if db == nil {
		return errors.New("updateStudentColumns: db is nil")
	}
	if m == nil {
		return errors.New("updateStudentColumns: m is nil")
	}
	if len(cols) == 0 {
		return errors.New("updateStudentColumns: at least one column/field must be specified")
	}

	allowedColumns := []string{
		"name", "Name",
		"email", "Email",
		"created_at", "CreatedAt",
	}

	setClauses := make([]string, 0, len(cols))
	args := make([]any, 0, len(cols)+1)

	for _, col := range cols {
		if !slices.Contains(allowedColumns, col) {
			return fmt.Errorf("updateStudentColumns: column or field %q is not updatable", col)
		}

		var dbCol string
		var val any

		switch col {
		case "name", "Name":
			dbCol = "name"
			val = m.Name
		case "email", "Email":
			dbCol = "email"
			val = m.Email
		case "created_at", "CreatedAt":
			dbCol = "created_at"
			val = m.CreatedAt
		}

		args = append(args, val)
		setClauses = append(setClauses, fmt.Sprintf("%s = $%d", dbCol, len(args)))
	}

	pkClauses := make([]string, 0, 1)
	pkClauses = append(pkClauses, fmt.Sprintf("%s = $%d", "id", len(args)+0+1))
	query := fmt.Sprintf("UPDATE students SET %s WHERE %s",
		strings.Join(setClauses, ", "), strings.Join(pkClauses, " AND "))

	args = append(args, m.ID)

	res, err := db.ExecContext(ctx, query, args...)
	if err != nil {
		return fmt.Errorf("updateStudentColumns(%v): %w", fmt.Sprint(m.ID), err)
	}

	n, err := res.RowsAffected()
	if err != nil {
		return fmt.Errorf("detect rows affected: %w", err)
	}
	if n == 0 {
		return fmt.Errorf("updateStudentColumns(%v): %w", fmt.Sprint(m.ID), sql.ErrNoRows)
	}
	return nil
}

// ExistsStudentByID reports whether a Student record with the given primary key exists.
func ExistsStudentByID(ctx context.Context, db DBTX, id int64, opts ...QueryOption) (bool, error) {
	if db == nil {
		return false, errors.New("existsStudentByID: db is nil")
	}

	cfg := parseQueryOptions(opts...)
	query := `SELECT EXISTS(SELECT 1 FROM students WHERE id = $1`
	if !cfg.IncludeDeleted {
		query += " AND deleted_at IS NULL"
	}
	query += ")"

	var exists bool
	if err := db.QueryRowContext(ctx, query, id).Scan(&exists); err != nil {
		return false, fmt.Errorf("existsStudentByID(%v): %w", id, err)
	}
	return exists, nil
}

// ExistsStudent reports whether a Student record matching the mandatory query options/where clause exists.
func ExistsStudent(ctx context.Context, db DBTX, opts ...QueryOption) (bool, error) {
	if db == nil {
		return false, errors.New("existsStudent: db is nil")
	}

	cfg := parseQueryOptions(opts...)
	if cfg.Where == "" {
		return false, errors.New("existsStudent: query options/where clause required")
	}

	var whereClause string
	if cfg.Where != "" {
		whereClause = " WHERE " + cfg.Where
	}

	if !cfg.IncludeDeleted {
		if whereClause != "" {
			whereClause += " AND deleted_at IS NULL"
		} else {
			whereClause = " WHERE deleted_at IS NULL"
		}
	}

	tableName := "students"
	if cfg.Table != "" {
		tableName = cfg.Table
	}

	query := "SELECT EXISTS(SELECT 1 FROM " + tableName + whereClause + ")"

	var exists bool
	if err := db.QueryRowContext(ctx, query, cfg.Args...).Scan(&exists); err != nil {
		return false, fmt.Errorf("existsStudent: %w", err)
	}
	return exists, nil
}

// CountStudents returns total records matching optional filter criteria.
func CountStudents(ctx context.Context, db DBTX, opts ...QueryOption) (int64, error) {
	if db == nil {
		return 0, errors.New("countStudents: db is nil")
	}

	cfg := parseQueryOptions(opts...)

	var whereClause string
	if cfg.Where != "" {
		whereClause = " WHERE " + cfg.Where
	}

	if !cfg.IncludeDeleted {
		if whereClause != "" {
			whereClause += " AND deleted_at IS NULL"
		} else {
			whereClause = " WHERE deleted_at IS NULL"
		}
	}

	tableName := "students"
	if cfg.Table != "" {
		tableName = cfg.Table
	}

	query := "SELECT COUNT(*) FROM " + tableName + whereClause

	var count int64
	if err := db.QueryRowContext(ctx, query, cfg.Args...).Scan(&count); err != nil {
		return 0, fmt.Errorf("countStudents: %w", err)
	}
	return count, nil
}

// FetchAllStudents retrieves a filtered/paginated slice of Student records.
func FetchAllStudents(ctx context.Context, db DBTX, opts ...QueryOption) ([]*models.Student, error) {
	if db == nil {
		return nil, errors.New("fetchAllStudents: db is nil")
	}

	clause, args, cfg := applyQueryOptions("id", "deleted_at", opts...)
	if cfg.PreloadAssociations {
		return fetchAllStudentsWithRelations(ctx, db, clause, args, cfg)
	}

	tableName := "students"
	if cfg.Table != "" {
		tableName = cfg.Table
	}

	query := "SELECT id, name, email, created_at, deleted_at FROM " + tableName + clause

	rows, err := db.QueryContext(ctx, query, args...)
	if err != nil {
		return nil, fmt.Errorf("fetchAllStudents: %w", err)
	}
	defer rows.Close()

	items := make([]*models.Student, 0, 16)
	for rows.Next() {
		var m models.Student
		if err := rows.Scan(&m.ID, &m.Name, &m.Email, scanNullable(&m.CreatedAt), scanNullable(&m.DeletedAt)); err != nil {
			return nil, fmt.Errorf("fetchAllStudents: scanning row: %w", err)
		}
		items = append(items, &m)
	}

	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("fetchAllStudents: iterating rows: %w", err)
	}

	return items, nil
}

// UpdateStudent updates an existing Student record in students.
func UpdateStudent(ctx context.Context, db DBTX, m *models.Student) error {
	if db == nil {
		return errors.New("updateStudent: db is nil")
	}
	if m == nil {
		return errors.New("updateStudent: m is nil")
	}

	const query = `
		UPDATE students
		SET name = $1, email = $2, created_at = $3
		WHERE id = $4
	`

	res, err := db.ExecContext(ctx, query, &m.Name, &m.Email, &m.CreatedAt, m.ID)
	if err != nil {
		return fmt.Errorf("updateStudent(%v): %w", fmt.Sprint(m.ID), err)
	}

	n, err := res.RowsAffected()
	if err != nil {
		return fmt.Errorf("detect rows affected: %w", err)
	}
	if n == 0 {
		return fmt.Errorf("updateStudent(%v): %w", fmt.Sprint(m.ID), sql.ErrNoRows)
	}
	return nil
}

// DeleteStudent deletes the Student record identified by primary key from students.
func DeleteStudent(ctx context.Context, db DBTX, id int64, opts ...QueryOption) error {
	if db == nil {
		return errors.New("deleteStudent: db is nil")
	}

	cfg := parseQueryOptions(opts...)
	if !cfg.HardDelete {
		const query = `UPDATE students SET deleted_at = CURRENT_TIMESTAMP WHERE id = $1 AND deleted_at IS NULL`
		res, err := db.ExecContext(ctx, query, id)
		if err != nil {
			return fmt.Errorf("deleteStudent(%v): %w", id, err)
		}
		n, err := res.RowsAffected()
		if err != nil {
			return fmt.Errorf("detect rows affected: %w", err)
		}
		if n == 0 {
			return fmt.Errorf("deleteStudent(%v): %w", id, sql.ErrNoRows)
		}
		return nil
	}

	const query = `DELETE FROM students WHERE id = $1`

	res, err := db.ExecContext(ctx, query, id)
	if err != nil {
		return fmt.Errorf("deleteStudent(%v): %w", id, err)
	}

	n, err := res.RowsAffected()
	if err != nil {
		return fmt.Errorf("detect rows affected: %w", err)
	}
	if n == 0 {
		return fmt.Errorf("deleteStudent(%v): %w", id, sql.ErrNoRows)
	}
	return nil
}

// DeleteStudents deletes records from students matching the provided query options and returns the number of affected rows.
func DeleteStudents(ctx context.Context, db DBTX, opts ...QueryOption) (int64, error) {
	if db == nil {
		return 0, errors.New("deleteStudents: db is nil")
	}

	cfg := parseQueryOptions(opts...)
	if cfg.Where == "" {
		return 0, errors.New("deleteStudents: query options/where clause required to prevent accidental bulk deletion")
	}

	clause, args, cfg := applyQueryOptions("", "deleted_at", opts...)

	tableName := "students"
	if cfg.Table != "" {
		tableName = cfg.Table
	}

	var query string
	if !cfg.HardDelete {
		query = "UPDATE " + tableName + " SET deleted_at = CURRENT_TIMESTAMP" + clause
	} else {
		query = "DELETE FROM " + tableName + clause
	}

	res, err := db.ExecContext(ctx, query, args...)
	if err != nil {
		return 0, fmt.Errorf("deleteStudents: %w", err)
	}

	n, err := res.RowsAffected()
	if err != nil {
		return 0, fmt.Errorf("deleteStudents: detecting rows affected: %w", err)
	}

	return n, nil
}

// ================= FETCHING RELATIONS ===============================
func getStudentByIDWithRelations(ctx context.Context, db DBTX, id int64, cfg QueryOptions) (*models.Student, error) {
	query := `
		SELECT 
			p.id, p.name, p.email, p.created_at, p.deleted_at, r0.id, r0.code, r0.title, r0.created_at, r0.deleted_at
		FROM students p
		LEFT JOIN student_courses j0 ON j0.student_id = p.id
		LEFT JOIN courses r0 ON r0.id = j0.course_id AND r0.deleted_at IS NULL
		WHERE p.id = $1
	`
	if !cfg.IncludeDeleted {
		query += " AND p.deleted_at IS NULL"
	}

	rows, err := db.QueryContext(ctx, query, id)
	if err != nil {
		return nil, fmt.Errorf("getStudentByIDWithRelations(%v): %w", id, err)
	}
	defer rows.Close()

	var parent *models.Student
	var p models.Student

	seen_Courses := make(map[int64]struct{}, 4)
	var c0 models.Course
	scanArgs := []any{
		&p.ID, &p.Name, &p.Email, scanNullable(&p.CreatedAt), scanNullable(&p.DeletedAt),
		scanNullable(&c0.ID),
		scanNullable(&c0.Code),
		scanNullable(&c0.Title),
		scanNullable(&c0.CreatedAt),
		scanNullable(&c0.DeletedAt),
	}

	for rows.Next() {
		if err := rows.Scan(scanArgs...); err != nil {
			return nil, fmt.Errorf("getStudentByIDWithRelations(%v): scanning row: %w", id, err)
		}

		if parent == nil {
			parent = &p
		}

		if !(IsZero(c0.ID)) {
			rPk0 := c0.ID
			if _, ok := seen_Courses[rPk0]; !ok {
				seen_Courses[rPk0] = struct{}{}
				child := c0
				parent.Courses = append(parent.Courses, child)
			}
		}
	}

	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("getStudentByIDWithRelations(%v): iterating rows: %w", id, err)
	}
	if parent == nil {
		return nil, fmt.Errorf("getStudentByIDWithRelations(%v): %w", id, sql.ErrNoRows)
	}

	return parent, nil
}

func fetchAllStudentsWithRelations(ctx context.Context, db DBTX, clause string, args []any, cfg QueryOptions) ([]*models.Student, error) {
	query := `
		WITH p AS (
			SELECT p.id, p.name, p.email, p.created_at, p.deleted_at
			FROM students p
	` + clause + `
		)
		SELECT 
			p.id, p.name, p.email, p.created_at, p.deleted_at, r0.id, r0.code, r0.title, r0.created_at, r0.deleted_at
		FROM p
		LEFT JOIN student_courses j0 ON j0.student_id = p.id
		LEFT JOIN courses r0 ON r0.id = j0.course_id AND r0.deleted_at IS NULL
		ORDER BY p.id ASC
	`

	rows, err := db.QueryContext(ctx, query, args...)
	if err != nil {
		return nil, fmt.Errorf("fetchAllStudentsWithRelations: %w", err)
	}
	defer rows.Close()

	items := make([]*models.Student, 0, 16)
	itemsMap := make(map[int64]*models.Student, 16)

	seen_Courses := make(map[seenKey[int64, int64]]struct{}, 64)
	for rows.Next() {
		var p models.Student
		var c0 models.Course
		scanArgs := []any{
			&p.ID, &p.Name, &p.Email, scanNullable(&p.CreatedAt), scanNullable(&p.DeletedAt),
			scanNullable(&c0.ID),
			scanNullable(&c0.Code),
			scanNullable(&c0.Title),
			scanNullable(&c0.CreatedAt),
			scanNullable(&c0.DeletedAt),
		}

		if err := rows.Scan(scanArgs...); err != nil {
			return nil, fmt.Errorf("fetchAllStudentsWithRelations: scanning row: %w", err)
		}

		pPK := p.ID
		parent, exists := itemsMap[pPK]
		if !exists {
			parent = &p
			itemsMap[pPK] = parent
			items = append(items, parent)
		}

		if !(IsZero(c0.ID)) {
			rPk0 := c0.ID
			key0 := seenKey[int64, int64]{parent: pPK, child: rPk0}
			if _, ok := seen_Courses[key0]; !ok {
				seen_Courses[key0] = struct{}{}
				child := c0
				parent.Courses = append(parent.Courses, child)
			}
		}
	}

	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("fetchAllStudentsWithRelations: iterating rows: %w", err)
	}

	return items, nil
}
