// Code generated by query-gen. DO NOT EDIT.
package queries

import (
	"context"
	"database/sql"
	"errors"
	"fmt"
	"strings"

	"github.com/abiiranathan/query-gen/example/models"
)

// InsertTag inserts a new Tag record into the tags table.
func InsertTag(ctx context.Context, db DBTX, m *models.Tag) error {
	if db == nil {
		return errors.New("insertTag: db is nil")
	}
	if m == nil {
		return errors.New("insertTag: m is nil")
	}

	fields := []struct {
		col        string
		val        any
		omitIfZero bool
	}{
		{col: "project_id", val: m.ProjectID, omitIfZero: false},
		{col: "name", val: m.Name, omitIfZero: false},
	}

	cols := make([]string, 0, len(fields))
	args := make([]any, 0, len(fields))
	placeholders := make([]string, 0, len(fields))

	for _, f := range fields {
		if f.omitIfZero && IsZero(f.val) {
			continue
		}
		cols = append(cols, f.col)
		args = append(args, f.val)
		placeholders = append(placeholders, fmt.Sprintf("$%d", len(args)))
	}

	var query string
	if len(cols) == 0 {
		query = "INSERT INTO tags DEFAULT VALUES RETURNING id, project_id, name"
	} else {
		query = fmt.Sprintf("INSERT INTO tags (%s) VALUES (%s) RETURNING id, project_id, name",
			strings.Join(cols, ", "), strings.Join(placeholders, ", "))
	}

	if err := db.QueryRowContext(ctx, query, args...).
		Scan(&m.ID, &m.ProjectID, &m.Name); err != nil {
		return fmt.Errorf("insertTag: %w", err)
	}
	return nil
}

// GetTagByID retrieves a single Tag record from tags by its primary key.
func GetTagByID(ctx context.Context, db DBTX, id int64, opts ...QueryOption) (*models.Tag, error) {
	if db == nil {
		return nil, errors.New("getTagByID: db is nil")
	}

	const query = `
		SELECT id, project_id, name
		FROM tags
		WHERE id = $1
	`

	row := db.QueryRowContext(ctx, query, id)
	var m models.Tag
	if err := row.Scan(&m.ID, &m.ProjectID, &m.Name); err != nil {
		return nil, fmt.Errorf("getTagByID(%v): %w", id, err)
	}

	return &m, nil
}

// ExistsTagByID reports whether a Tag record with the given primary key exists.
func ExistsTagByID(ctx context.Context, db DBTX, id int64, opts ...QueryOption) (bool, error) {
	if db == nil {
		return false, errors.New("existsTagByID: db is nil")
	}

	const query = `SELECT EXISTS(SELECT 1 FROM tags WHERE id = $1)`

	var exists bool
	if err := db.QueryRowContext(ctx, query, id).Scan(&exists); err != nil {
		return false, fmt.Errorf("existsTagByID(%v): %w", id, err)
	}
	return exists, nil
}

// CountTags returns total records matching optional filter criteria.
func CountTags(ctx context.Context, db DBTX, opts ...QueryOption) (int64, error) {
	if db == nil {
		return 0, errors.New("countTags: db is nil")
	}

	cfg := parseQueryOptions(opts...)

	var whereClause string
	if cfg.Where != "" {
		whereClause = " WHERE " + cfg.Where
	}

	query := "SELECT COUNT(*) FROM tags" + whereClause

	var count int64
	if err := db.QueryRowContext(ctx, query, cfg.Args...).Scan(&count); err != nil {
		return 0, fmt.Errorf("countTags: %w", err)
	}
	return count, nil
}

// FetchAllTags retrieves a filtered/paginated slice of Tag records.
func FetchAllTags(ctx context.Context, db DBTX, opts ...QueryOption) ([]*models.Tag, error) {
	if db == nil {
		return nil, errors.New("fetchAllTags: db is nil")
	}

	clause, args, _ := applyQueryOptions("id", "", opts...)

	query := "SELECT id, project_id, name FROM tags" + clause

	rows, err := db.QueryContext(ctx, query, args...)
	if err != nil {
		return nil, fmt.Errorf("fetchAllTags: %w", err)
	}
	defer rows.Close()

	items := make([]*models.Tag, 0, 16)
	for rows.Next() {
		var m models.Tag
		if err := rows.Scan(&m.ID, &m.ProjectID, &m.Name); err != nil {
			return nil, fmt.Errorf("fetchAllTags: scanning row: %w", err)
		}
		items = append(items, &m)
	}

	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("fetchAllTags: iterating rows: %w", err)
	}

	return items, nil
}

// UpdateTag updates an existing Tag record in tags.
func UpdateTag(ctx context.Context, db DBTX, m *models.Tag) error {
	if db == nil {
		return errors.New("updateTag: db is nil")
	}
	if m == nil {
		return errors.New("updateTag: m is nil")
	}

	const query = `
		UPDATE tags
		SET project_id = $1, name = $2
		WHERE id = $3
	`

	res, err := db.ExecContext(ctx, query, &m.ProjectID, &m.Name, m.ID)
	if err != nil {
		return fmt.Errorf("updateTag(%v): %w", fmt.Sprint(m.ID), err)
	}

	n, err := res.RowsAffected()
	if err != nil {
		return fmt.Errorf("detect rows affected: %w", err)
	}
	if n == 0 {
		return fmt.Errorf("updateTag(%v): %w", fmt.Sprint(m.ID), sql.ErrNoRows)
	}
	return nil
}

// DeleteTag deletes the Tag record identified by primary key from tags.
func DeleteTag(ctx context.Context, db DBTX, id int64, opts ...QueryOption) error {
	if db == nil {
		return errors.New("deleteTag: db is nil")
	}

	const query = `DELETE FROM tags WHERE id = $1`

	res, err := db.ExecContext(ctx, query, id)
	if err != nil {
		return fmt.Errorf("deleteTag(%v): %w", id, err)
	}

	n, err := res.RowsAffected()
	if err != nil {
		return fmt.Errorf("detect rows affected: %w", err)
	}
	if n == 0 {
		return fmt.Errorf("deleteTag(%v): %w", id, sql.ErrNoRows)
	}
	return nil
}

// DeleteTags deletes records from tags matching the provided query options and returns the number of affected rows.
func DeleteTags(ctx context.Context, db DBTX, opts ...QueryOption) (int64, error) {
	if db == nil {
		return 0, errors.New("deleteTags: db is nil")
	}

	cfg := parseQueryOptions(opts...)
	if cfg.Where == "" {
		return 0, errors.New("deleteTags: query options/where clause required to prevent accidental bulk deletion")
	}

	clause, args, _ := applyQueryOptions("", "", opts...)

	var query string
	query = "DELETE FROM tags" + clause

	res, err := db.ExecContext(ctx, query, args...)
	if err != nil {
		return 0, fmt.Errorf("deleteTags: %w", err)
	}

	n, err := res.RowsAffected()
	if err != nil {
		return 0, fmt.Errorf("deleteTags: detecting rows affected: %w", err)
	}

	return n, nil
}

// ================= FETCHING RELATIONS ===============================
