// Code generated by query-gen. DO NOT EDIT.
package queries

import (
	"context"
	"database/sql"
	"errors"
	"fmt"
	"slices"
	"strings"

	"github.com/abiiranathan/query-gen/example/models"
)

// InsertTask inserts a new Task record into the tasks table.
func InsertTask(ctx context.Context, db DBTX, m *models.Task) error {
	if db == nil {
		return errors.New("insertTask: db is nil")
	}
	if m == nil {
		return errors.New("insertTask: m is nil")
	}

	fields := []struct {
		col        string
		val        any
		omitIfZero bool
	}{
		{col: "project_id", val: m.ProjectID, omitIfZero: false},
		{col: "title", val: m.Title, omitIfZero: false},
	}

	cols := make([]string, 0, len(fields))
	args := make([]any, 0, len(fields))
	placeholders := make([]string, 0, len(fields))

	for _, f := range fields {
		if f.omitIfZero && IsZero(f.val) {
			continue
		}
		cols = append(cols, f.col)
		args = append(args, f.val)
		placeholders = append(placeholders, fmt.Sprintf("$%d", len(args)))
	}

	var query string
	if len(cols) == 0 {
		query = "INSERT INTO tasks DEFAULT VALUES RETURNING id, project_id, title"
	} else {
		query = fmt.Sprintf("INSERT INTO tasks (%s) VALUES (%s) RETURNING id, project_id, title",
			strings.Join(cols, ", "), strings.Join(placeholders, ", "))
	}

	if err := db.QueryRowContext(ctx, query, args...).
		Scan(&m.ID, &m.ProjectID, &m.Title); err != nil {
		return fmt.Errorf("insertTask: %w", err)
	}
	return nil
}

// ============ Bulk insert ========================

// InsertTasks inserts multiple Task records into tasks in efficient parameter-bounded batches.
// Automatically populates database-generated values (e.g., auto-increment primary keys, default values) back into input structs via RETURNING.
func InsertTasks(ctx context.Context, db DBTX, models []*models.Task) error {
	if db == nil {
		return errors.New("insertTasks: db is nil")
	}
	if len(models) == 0 {
		return nil
	}

	const batchSize = 499
	for i := 0; i < len(models); i += batchSize {
		end := min((i + batchSize), len(models))
		batch := models[i:end]
		if err := insertTasksBatch(ctx, db, batch); err != nil {
			return fmt.Errorf("insertTasks: batch [%d:%d]: %w", i, end, err)
		}
	}
	return nil
}

func insertTasksBatch(ctx context.Context, db DBTX, batch []*models.Task) error {
	if len(batch) == 0 {
		return nil
	}

	args := make([]any, 0, len(batch)*2)
	var sb strings.Builder
	sb.Grow(128 + len(batch)*2*8)
	sb.WriteString("INSERT INTO tasks (project_id, title) VALUES ")

	paramIdx := 1
	for i, m := range batch {
		if m == nil {
			return fmt.Errorf("model at index %d is nil", i)
		}
		if i > 0 {
			sb.WriteString(", ")
		}
		sb.WriteByte('(')

		sb.WriteString(getPlaceholder(paramIdx))
		paramIdx++
		args = append(args, m.ProjectID)
		sb.WriteString(", ")
		sb.WriteString(getPlaceholder(paramIdx))
		paramIdx++
		args = append(args, m.Title)
		sb.WriteByte(')')
	}

	sb.WriteString(" RETURNING id, project_id, title")
	rows, err := db.QueryContext(ctx, sb.String(), args...)
	if err != nil {
		return fmt.Errorf("executing bulk insert: %w", err)
	}
	defer rows.Close()

	idx := 0
	for rows.Next() {
		if idx >= len(batch) {
			return errors.New("unexpected extra row returned from insert")
		}
		m := batch[idx]
		if err := rows.Scan(&m.ID, &m.ProjectID, &m.Title); err != nil {
			return fmt.Errorf("scanning row %d: %w", idx, err)
		}
		idx++
	}

	if err := rows.Err(); err != nil {
		return fmt.Errorf("iterating bulk insert rows: %w", err)
	}

	if idx < len(batch) {
		return fmt.Errorf("expected %d inserted rows, got %d", len(batch), idx)
	}

	return nil
}

// GetTaskByID retrieves a single Task record from tasks by its primary key.
func GetTaskByID(ctx context.Context, db DBTX, id int64, opts ...QueryOption) (*models.Task, error) {
	if db == nil {
		return nil, errors.New("getTaskByID: db is nil")
	}

	cfg := parseQueryOptions(opts...)

	if cfg.PreloadAssociations {
		return getTaskByIDWithRelations(ctx, db, id, cfg)
	}

	const query = `
		SELECT id, project_id, title
		FROM tasks
		WHERE id = $1
	`

	row := db.QueryRowContext(ctx, query, id)
	var m models.Task
	if err := row.Scan(&m.ID, &m.ProjectID, &m.Title); err != nil {
		return nil, fmt.Errorf("getTaskByID(%v): %w", id, err)
	}

	return &m, nil
}

// GetTask retrieves a single Task record matching mandatory query options/where clause.
// Returns sql.ErrNoRows if no matching record is found.
func GetTask(ctx context.Context, db DBTX, opts ...QueryOption) (*models.Task, error) {
	if db == nil {
		return nil, errors.New("getTask: db is nil")
	}

	cfg := parseQueryOptions(opts...)
	if cfg.Where == "" {
		return nil, errors.New("getTask: query options/where clause required to prevent returning arbitrary row")
	}

	pOpts := append([]QueryOption(nil), opts...)
	pOpts = append(pOpts, Limit(1))

	items, err := FetchAllTasks(ctx, db, pOpts...)
	if err != nil {
		return nil, fmt.Errorf("getTask: %w", err)
	}
	if len(items) == 0 {
		return nil, fmt.Errorf("getTask: %w", sql.ErrNoRows)
	}
	return items[0], nil
}

// UpdateTaskColumns updates only the specified updatable columns/fields for an existing Task record in tasks.
// Column arguments can be database column names (e.g. "email") or Go field names (e.g. "Email").
func UpdateTaskColumns(ctx context.Context, db DBTX, m *models.Task, cols ...string) error {
	if db == nil {
		return errors.New("updateTaskColumns: db is nil")
	}
	if m == nil {
		return errors.New("updateTaskColumns: m is nil")
	}
	if len(cols) == 0 {
		return errors.New("updateTaskColumns: at least one column/field must be specified")
	}

	allowedColumns := []string{
		"project_id", "ProjectID",
		"title", "Title",
	}

	setClauses := make([]string, 0, len(cols))
	args := make([]any, 0, len(cols)+1)

	for _, col := range cols {
		if !slices.Contains(allowedColumns, col) {
			return fmt.Errorf("updateTaskColumns: column or field %q is not updatable", col)
		}

		var dbCol string
		var val any

		switch col {
		case "project_id", "ProjectID":
			dbCol = "project_id"
			val = m.ProjectID
		case "title", "Title":
			dbCol = "title"
			val = m.Title
		}

		args = append(args, val)
		setClauses = append(setClauses, fmt.Sprintf("%s = $%d", dbCol, len(args)))
	}

	pkClauses := make([]string, 0, 1)
	pkClauses = append(pkClauses, fmt.Sprintf("%s = $%d", "id", len(args)+0+1))
	query := fmt.Sprintf("UPDATE tasks SET %s WHERE %s",
		strings.Join(setClauses, ", "), strings.Join(pkClauses, " AND "))

	args = append(args, m.ID)

	res, err := db.ExecContext(ctx, query, args...)
	if err != nil {
		return fmt.Errorf("updateTaskColumns(%v): %w", fmt.Sprint(m.ID), err)
	}

	n, err := res.RowsAffected()
	if err != nil {
		return fmt.Errorf("detect rows affected: %w", err)
	}
	if n == 0 {
		return fmt.Errorf("updateTaskColumns(%v): %w", fmt.Sprint(m.ID), sql.ErrNoRows)
	}
	return nil
}

// ExistsTaskByID reports whether a Task record with the given primary key exists.
func ExistsTaskByID(ctx context.Context, db DBTX, id int64, opts ...QueryOption) (bool, error) {
	if db == nil {
		return false, errors.New("existsTaskByID: db is nil")
	}

	const query = `SELECT EXISTS(SELECT 1 FROM tasks WHERE id = $1)`

	var exists bool
	if err := db.QueryRowContext(ctx, query, id).Scan(&exists); err != nil {
		return false, fmt.Errorf("existsTaskByID(%v): %w", id, err)
	}
	return exists, nil
}

// ExistsTask reports whether a Task record matching the mandatory query options/where clause exists.
func ExistsTask(ctx context.Context, db DBTX, opts ...QueryOption) (bool, error) {
	if db == nil {
		return false, errors.New("existsTask: db is nil")
	}

	cfg := parseQueryOptions(opts...)
	if cfg.Where == "" {
		return false, errors.New("existsTask: query options/where clause required")
	}

	var whereClause string
	if cfg.Where != "" {
		whereClause = " WHERE " + cfg.Where
	}

	tableName := "tasks"
	if cfg.Table != "" {
		tableName = cfg.Table
	}

	query := "SELECT EXISTS(SELECT 1 FROM " + tableName + whereClause + ")"

	var exists bool
	if err := db.QueryRowContext(ctx, query, cfg.Args...).Scan(&exists); err != nil {
		return false, fmt.Errorf("existsTask: %w", err)
	}
	return exists, nil
}

// CountTasks returns total records matching optional filter criteria.
func CountTasks(ctx context.Context, db DBTX, opts ...QueryOption) (int64, error) {
	if db == nil {
		return 0, errors.New("countTasks: db is nil")
	}

	cfg := parseQueryOptions(opts...)

	var whereClause string
	if cfg.Where != "" {
		whereClause = " WHERE " + cfg.Where
	}

	tableName := "tasks"
	if cfg.Table != "" {
		tableName = cfg.Table
	}

	query := "SELECT COUNT(*) FROM " + tableName + whereClause

	var count int64
	if err := db.QueryRowContext(ctx, query, cfg.Args...).Scan(&count); err != nil {
		return 0, fmt.Errorf("countTasks: %w", err)
	}
	return count, nil
}

// FetchAllTasks retrieves a filtered/paginated slice of Task records.
func FetchAllTasks(ctx context.Context, db DBTX, opts ...QueryOption) ([]*models.Task, error) {
	if db == nil {
		return nil, errors.New("fetchAllTasks: db is nil")
	}

	clause, args, cfg := applyQueryOptions("id", "", opts...)
	if cfg.PreloadAssociations {
		return fetchAllTasksWithRelations(ctx, db, clause, args, cfg)
	}

	tableName := "tasks"
	if cfg.Table != "" {
		tableName = cfg.Table
	}

	query := "SELECT id, project_id, title FROM " + tableName + clause

	rows, err := db.QueryContext(ctx, query, args...)
	if err != nil {
		return nil, fmt.Errorf("fetchAllTasks: %w", err)
	}
	defer rows.Close()

	items := make([]*models.Task, 0, 16)
	for rows.Next() {
		var m models.Task
		if err := rows.Scan(&m.ID, &m.ProjectID, &m.Title); err != nil {
			return nil, fmt.Errorf("fetchAllTasks: scanning row: %w", err)
		}
		items = append(items, &m)
	}

	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("fetchAllTasks: iterating rows: %w", err)
	}

	return items, nil
}

// UpdateTask updates an existing Task record in tasks.
func UpdateTask(ctx context.Context, db DBTX, m *models.Task) error {
	if db == nil {
		return errors.New("updateTask: db is nil")
	}
	if m == nil {
		return errors.New("updateTask: m is nil")
	}

	const query = `
		UPDATE tasks
		SET project_id = $1, title = $2
		WHERE id = $3
	`

	res, err := db.ExecContext(ctx, query, &m.ProjectID, &m.Title, m.ID)
	if err != nil {
		return fmt.Errorf("updateTask(%v): %w", fmt.Sprint(m.ID), err)
	}

	n, err := res.RowsAffected()
	if err != nil {
		return fmt.Errorf("detect rows affected: %w", err)
	}
	if n == 0 {
		return fmt.Errorf("updateTask(%v): %w", fmt.Sprint(m.ID), sql.ErrNoRows)
	}
	return nil
}

// DeleteTask deletes the Task record identified by primary key from tasks.
func DeleteTask(ctx context.Context, db DBTX, id int64, opts ...QueryOption) error {
	if db == nil {
		return errors.New("deleteTask: db is nil")
	}

	const query = `DELETE FROM tasks WHERE id = $1`

	res, err := db.ExecContext(ctx, query, id)
	if err != nil {
		return fmt.Errorf("deleteTask(%v): %w", id, err)
	}

	n, err := res.RowsAffected()
	if err != nil {
		return fmt.Errorf("detect rows affected: %w", err)
	}
	if n == 0 {
		return fmt.Errorf("deleteTask(%v): %w", id, sql.ErrNoRows)
	}
	return nil
}

// DeleteTasks deletes records from tasks matching the provided query options and returns the number of affected rows.
func DeleteTasks(ctx context.Context, db DBTX, opts ...QueryOption) (int64, error) {
	if db == nil {
		return 0, errors.New("deleteTasks: db is nil")
	}

	cfg := parseQueryOptions(opts...)
	if cfg.Where == "" {
		return 0, errors.New("deleteTasks: query options/where clause required to prevent accidental bulk deletion")
	}

	clause, args, cfg := applyQueryOptions("", "", opts...)

	tableName := "tasks"
	if cfg.Table != "" {
		tableName = cfg.Table
	}

	var query string
	query = "DELETE FROM " + tableName + clause

	res, err := db.ExecContext(ctx, query, args...)
	if err != nil {
		return 0, fmt.Errorf("deleteTasks: %w", err)
	}

	n, err := res.RowsAffected()
	if err != nil {
		return 0, fmt.Errorf("deleteTasks: detecting rows affected: %w", err)
	}

	return n, nil
}

// ================= FETCHING RELATIONS ===============================
func getTaskByIDWithRelations(ctx context.Context, db DBTX, id int64, cfg QueryOptions) (*models.Task, error) {
	const query = `
		SELECT 
			p.id, p.project_id, p.title, r0.id, r0.name, r0.description, r0.created_at, r0.deleted_at
		FROM tasks p
		LEFT JOIN projects r0 ON r0.id = p.project_id AND r0.deleted_at IS NULL
		WHERE p.id = $1
	`

	rows, err := db.QueryContext(ctx, query, id)
	if err != nil {
		return nil, fmt.Errorf("getTaskByIDWithRelations(%v): %w", id, err)
	}
	defer rows.Close()

	var parent *models.Task
	var p models.Task

	seen_Project := make(map[int64]struct{}, 4)
	var c0 models.Project
	scanArgs := []any{
		&p.ID, &p.ProjectID, &p.Title,
		scanNullable(&c0.ID),
		scanNullable(&c0.Name),
		scanNullable(&c0.Description),
		scanNullable(&c0.CreatedAt),
		scanNullable(&c0.DeletedAt),
	}

	for rows.Next() {
		if err := rows.Scan(scanArgs...); err != nil {
			return nil, fmt.Errorf("getTaskByIDWithRelations(%v): scanning row: %w", id, err)
		}

		if parent == nil {
			parent = &p
		}

		if !(IsZero(c0.ID)) {
			rPk0 := c0.ID
			if _, ok := seen_Project[rPk0]; !ok {
				seen_Project[rPk0] = struct{}{}
				child := c0
				parent.Project = &child
			}
		}
	}

	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("getTaskByIDWithRelations(%v): iterating rows: %w", id, err)
	}
	if parent == nil {
		return nil, fmt.Errorf("getTaskByIDWithRelations(%v): %w", id, sql.ErrNoRows)
	}

	return parent, nil
}

func fetchAllTasksWithRelations(ctx context.Context, db DBTX, clause string, args []any, cfg QueryOptions) ([]*models.Task, error) {
	query := `
		WITH p AS (
			SELECT p.id, p.project_id, p.title
			FROM tasks p
	` + clause + `
		)
		SELECT 
			p.id, p.project_id, p.title, r0.id, r0.name, r0.description, r0.created_at, r0.deleted_at
		FROM p
		LEFT JOIN projects r0 ON r0.id = p.project_id AND r0.deleted_at IS NULL
		ORDER BY p.id ASC
	`

	rows, err := db.QueryContext(ctx, query, args...)
	if err != nil {
		return nil, fmt.Errorf("fetchAllTasksWithRelations: %w", err)
	}
	defer rows.Close()

	items := make([]*models.Task, 0, 16)
	itemsMap := make(map[int64]*models.Task, 16)

	seen_Project := make(map[seenKey[int64, int64]]struct{}, 64)
	for rows.Next() {
		var p models.Task
		var c0 models.Project
		scanArgs := []any{
			&p.ID, &p.ProjectID, &p.Title,
			scanNullable(&c0.ID),
			scanNullable(&c0.Name),
			scanNullable(&c0.Description),
			scanNullable(&c0.CreatedAt),
			scanNullable(&c0.DeletedAt),
		}

		if err := rows.Scan(scanArgs...); err != nil {
			return nil, fmt.Errorf("fetchAllTasksWithRelations: scanning row: %w", err)
		}

		pPK := p.ID
		parent, exists := itemsMap[pPK]
		if !exists {
			parent = &p
			itemsMap[pPK] = parent
			items = append(items, parent)
		}

		if !(IsZero(c0.ID)) {
			rPk0 := c0.ID
			key0 := seenKey[int64, int64]{parent: pPK, child: rPk0}
			if _, ok := seen_Project[key0]; !ok {
				seen_Project[key0] = struct{}{}
				child := c0
				parent.Project = &child
			}
		}
	}

	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("fetchAllTasksWithRelations: iterating rows: %w", err)
	}

	return items, nil
}
