// Code generated by query-gen. DO NOT EDIT.
package queries

import (
	"context"
	"database/sql"
	"errors"
	"fmt"
	"strings"

	"github.com/abiiranathan/query-gen/example/models"
)

// InsertTask inserts a new Task record into the tasks table.
func InsertTask(ctx context.Context, db DBTX, m *models.Task) error {
	if db == nil {
		return errors.New("insertTask: db is nil")
	}
	if m == nil {
		return errors.New("insertTask: m is nil")
	}

	fields := []struct {
		col        string
		val        any
		omitIfZero bool
	}{
		{col: "project_id", val: m.ProjectID, omitIfZero: false},
		{col: "title", val: m.Title, omitIfZero: false},
	}

	cols := make([]string, 0, len(fields))
	args := make([]any, 0, len(fields))
	placeholders := make([]string, 0, len(fields))

	for _, f := range fields {
		if f.omitIfZero && IsZero(f.val) {
			continue
		}
		cols = append(cols, f.col)
		args = append(args, f.val)
		placeholders = append(placeholders, fmt.Sprintf("$%d", len(args)))
	}

	var query string
	if len(cols) == 0 {
		query = "INSERT INTO tasks DEFAULT VALUES RETURNING id, project_id, title"
	} else {
		query = fmt.Sprintf("INSERT INTO tasks (%s) VALUES (%s) RETURNING id, project_id, title",
			strings.Join(cols, ", "), strings.Join(placeholders, ", "))
	}

	if err := db.QueryRowContext(ctx, query, args...).
		Scan(&m.ID, &m.ProjectID, &m.Title); err != nil {
		return fmt.Errorf("insertTask: %w", err)
	}
	return nil
}

// ============ Bulk insert ========================

// InsertTasks inserts multiple Task records into tasks in efficient parameter-bounded batches.
// Automatically populates database-generated values (e.g., auto-increment primary keys, default values) back into input structs via RETURNING.
func InsertTasks(ctx context.Context, db DBTX, models []*models.Task) error {
	if db == nil {
		return errors.New("insertTasks: db is nil")
	}
	if len(models) == 0 {
		return nil
	}

	const batchSize = 499
	for i := 0; i < len(models); i += batchSize {
		end := min((i + batchSize), len(models))
		batch := models[i:end]
		if err := insertTasksBatch(ctx, db, batch); err != nil {
			return fmt.Errorf("insertTasks: batch [%d:%d]: %w", i, end, err)
		}
	}
	return nil
}

func insertTasksBatch(ctx context.Context, db DBTX, batch []*models.Task) error {
	if len(batch) == 0 {
		return nil
	}

	args := make([]any, 0, len(batch)*2)
	var sb strings.Builder
	sb.Grow(128 + len(batch)*2*8)
	sb.WriteString("INSERT INTO tasks (project_id, title) VALUES ")

	paramIdx := 1
	for i, m := range batch {
		if m == nil {
			return fmt.Errorf("model at index %d is nil", i)
		}
		if i > 0 {
			sb.WriteString(", ")
		}
		sb.WriteByte('(')

		sb.WriteString(getPlaceholder(paramIdx))
		paramIdx++
		args = append(args, m.ProjectID)
		sb.WriteString(", ")
		sb.WriteString(getPlaceholder(paramIdx))
		paramIdx++
		args = append(args, m.Title)
		sb.WriteByte(')')
	}

	sb.WriteString(" RETURNING id, project_id, title")
	rows, err := db.QueryContext(ctx, sb.String(), args...)
	if err != nil {
		return fmt.Errorf("executing bulk insert: %w", err)
	}
	defer rows.Close()

	idx := 0
	for rows.Next() {
		if idx >= len(batch) {
			return errors.New("unexpected extra row returned from insert")
		}
		m := batch[idx]
		if err := rows.Scan(&m.ID, &m.ProjectID, &m.Title); err != nil {
			return fmt.Errorf("scanning row %d: %w", idx, err)
		}
		idx++
	}

	if err := rows.Err(); err != nil {
		return fmt.Errorf("iterating bulk insert rows: %w", err)
	}

	if idx < len(batch) {
		return fmt.Errorf("expected %d inserted rows, got %d", len(batch), idx)
	}

	return nil
}

// GetTaskByID retrieves a single Task record from tasks by its primary key.
func GetTaskByID(ctx context.Context, db DBTX, id int64, opts ...QueryOption) (*models.Task, error) {
	if db == nil {
		return nil, errors.New("getTaskByID: db is nil")
	}

	const query = `
		SELECT id, project_id, title
		FROM tasks
		WHERE id = $1
	`

	row := db.QueryRowContext(ctx, query, id)
	var m models.Task
	if err := row.Scan(&m.ID, &m.ProjectID, &m.Title); err != nil {
		return nil, fmt.Errorf("getTaskByID(%v): %w", id, err)
	}

	return &m, nil
}

// ExistsTaskByID reports whether a Task record with the given primary key exists.
func ExistsTaskByID(ctx context.Context, db DBTX, id int64, opts ...QueryOption) (bool, error) {
	if db == nil {
		return false, errors.New("existsTaskByID: db is nil")
	}

	const query = `SELECT EXISTS(SELECT 1 FROM tasks WHERE id = $1)`

	var exists bool
	if err := db.QueryRowContext(ctx, query, id).Scan(&exists); err != nil {
		return false, fmt.Errorf("existsTaskByID(%v): %w", id, err)
	}
	return exists, nil
}

// CountTasks returns total records matching optional filter criteria.
func CountTasks(ctx context.Context, db DBTX, opts ...QueryOption) (int64, error) {
	if db == nil {
		return 0, errors.New("countTasks: db is nil")
	}

	cfg := parseQueryOptions(opts...)

	var whereClause string
	if cfg.Where != "" {
		whereClause = " WHERE " + cfg.Where
	}

	query := "SELECT COUNT(*) FROM tasks" + whereClause

	var count int64
	if err := db.QueryRowContext(ctx, query, cfg.Args...).Scan(&count); err != nil {
		return 0, fmt.Errorf("countTasks: %w", err)
	}
	return count, nil
}

// FetchAllTasks retrieves a filtered/paginated slice of Task records.
func FetchAllTasks(ctx context.Context, db DBTX, opts ...QueryOption) ([]*models.Task, error) {
	if db == nil {
		return nil, errors.New("fetchAllTasks: db is nil")
	}

	clause, args, _ := applyQueryOptions("id", "", opts...)

	query := "SELECT id, project_id, title FROM tasks" + clause

	rows, err := db.QueryContext(ctx, query, args...)
	if err != nil {
		return nil, fmt.Errorf("fetchAllTasks: %w", err)
	}
	defer rows.Close()

	items := make([]*models.Task, 0, 16)
	for rows.Next() {
		var m models.Task
		if err := rows.Scan(&m.ID, &m.ProjectID, &m.Title); err != nil {
			return nil, fmt.Errorf("fetchAllTasks: scanning row: %w", err)
		}
		items = append(items, &m)
	}

	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("fetchAllTasks: iterating rows: %w", err)
	}

	return items, nil
}

// UpdateTask updates an existing Task record in tasks.
func UpdateTask(ctx context.Context, db DBTX, m *models.Task) error {
	if db == nil {
		return errors.New("updateTask: db is nil")
	}
	if m == nil {
		return errors.New("updateTask: m is nil")
	}

	const query = `
		UPDATE tasks
		SET project_id = $1, title = $2
		WHERE id = $3
	`

	res, err := db.ExecContext(ctx, query, &m.ProjectID, &m.Title, m.ID)
	if err != nil {
		return fmt.Errorf("updateTask(%v): %w", fmt.Sprint(m.ID), err)
	}

	n, err := res.RowsAffected()
	if err != nil {
		return fmt.Errorf("detect rows affected: %w", err)
	}
	if n == 0 {
		return fmt.Errorf("updateTask(%v): %w", fmt.Sprint(m.ID), sql.ErrNoRows)
	}
	return nil
}

// DeleteTask deletes the Task record identified by primary key from tasks.
func DeleteTask(ctx context.Context, db DBTX, id int64, opts ...QueryOption) error {
	if db == nil {
		return errors.New("deleteTask: db is nil")
	}

	const query = `DELETE FROM tasks WHERE id = $1`

	res, err := db.ExecContext(ctx, query, id)
	if err != nil {
		return fmt.Errorf("deleteTask(%v): %w", id, err)
	}

	n, err := res.RowsAffected()
	if err != nil {
		return fmt.Errorf("detect rows affected: %w", err)
	}
	if n == 0 {
		return fmt.Errorf("deleteTask(%v): %w", id, sql.ErrNoRows)
	}
	return nil
}

// DeleteTasks deletes records from tasks matching the provided query options and returns the number of affected rows.
func DeleteTasks(ctx context.Context, db DBTX, opts ...QueryOption) (int64, error) {
	if db == nil {
		return 0, errors.New("deleteTasks: db is nil")
	}

	cfg := parseQueryOptions(opts...)
	if cfg.Where == "" {
		return 0, errors.New("deleteTasks: query options/where clause required to prevent accidental bulk deletion")
	}

	clause, args, _ := applyQueryOptions("", "", opts...)

	var query string
	query = "DELETE FROM tasks" + clause

	res, err := db.ExecContext(ctx, query, args...)
	if err != nil {
		return 0, fmt.Errorf("deleteTasks: %w", err)
	}

	n, err := res.RowsAffected()
	if err != nil {
		return 0, fmt.Errorf("deleteTasks: detecting rows affected: %w", err)
	}

	return n, nil
}

// ================= FETCHING RELATIONS ===============================
