// Code generated by query-gen. DO NOT EDIT.
package queries

import (
	"context"
	"database/sql"
	"errors"
	"fmt"
	"strings"

	"github.com/abiiranathan/query-gen/example/models"
)

// InsertUser inserts a new User record into the users table.
func InsertUser(ctx context.Context, db DBTX, m *models.User) error {
	if db == nil {
		return errors.New("insertUser: db is nil")
	}
	if m == nil {
		return errors.New("insertUser: m is nil")
	}

	fields := []struct {
		col        string
		val        any
		omitIfZero bool
	}{
		{col: "name", val: m.Name, omitIfZero: false},
		{col: "email", val: m.Email, omitIfZero: false},
		{col: "created_at", val: m.CreatedAt, omitIfZero: true},
		{col: "deleted_at", val: m.DeletedAt, omitIfZero: false},
		{col: "age", val: m.Age, omitIfZero: false},
	}

	cols := make([]string, 0, len(fields))
	args := make([]any, 0, len(fields))
	placeholders := make([]string, 0, len(fields))

	for _, f := range fields {
		if f.omitIfZero && IsZero(f.val) {
			continue
		}
		cols = append(cols, f.col)
		args = append(args, f.val)
		placeholders = append(placeholders, fmt.Sprintf("$%d", len(args)))
	}

	var query string
	if len(cols) == 0 {
		query = "INSERT INTO users DEFAULT VALUES RETURNING id, name, email, created_at, deleted_at, age"
	} else {
		query = fmt.Sprintf("INSERT INTO users (%s) VALUES (%s) RETURNING id, name, email, created_at, deleted_at, age",
			strings.Join(cols, ", "), strings.Join(placeholders, ", "))
	}

	if err := db.QueryRowContext(ctx, query, args...).Scan(&m.ID, &m.Name, &m.Email, scanNullable(&m.CreatedAt), scanNullable(&m.DeletedAt), &m.Age); err != nil {
		return fmt.Errorf("insertUser: %w", err)
	}
	return nil
}

// GetUserByID retrieves a single User record from users by its primary key.
func GetUserByID(ctx context.Context, db DBTX, id int64, opts ...QueryOption) (*models.User, error) {
	if db == nil {
		return nil, errors.New("getUserByID: db is nil")
	}

	cfg := parseQueryOptions(opts...)

	if cfg.PreloadAssociations {
		return getUserByIDWithRelations(ctx, db, id, cfg)
	}

	query := `
		SELECT id, name, email, created_at, deleted_at, age
		FROM users
		WHERE id = $1
	`
	if !cfg.IncludeDeleted {
		query += " AND deleted_at IS NULL"
	}

	row := db.QueryRowContext(ctx, query, id)
	var m models.User
	if err := row.Scan(&m.ID, &m.Name, &m.Email, scanNullable(&m.CreatedAt), scanNullable(&m.DeletedAt), &m.Age); err != nil {
		return nil, fmt.Errorf("getUserByID(%v): %w", id, err)
	}

	return &m, nil
}

// ExistsUserByID reports whether a User record with the given primary key exists.
func ExistsUserByID(ctx context.Context, db DBTX, id int64, opts ...QueryOption) (bool, error) {
	if db == nil {
		return false, errors.New("existsUserByID: db is nil")
	}

	cfg := parseQueryOptions(opts...)
	query := `SELECT EXISTS(SELECT 1 FROM users WHERE id = $1`
	if !cfg.IncludeDeleted {
		query += " AND deleted_at IS NULL"
	}
	query += ")"

	var exists bool
	if err := db.QueryRowContext(ctx, query, id).Scan(&exists); err != nil {
		return false, fmt.Errorf("existsUserByID(%v): %w", id, err)
	}
	return exists, nil
}

// CountUsers returns total records matching optional filter criteria.
func CountUsers(ctx context.Context, db DBTX, opts ...QueryOption) (int64, error) {
	if db == nil {
		return 0, errors.New("countUsers: db is nil")
	}

	clause, args, _ := applyQueryOptions("", "deleted_at", opts...)
	query := "SELECT COUNT(*) FROM users" + clause

	var count int64
	if err := db.QueryRowContext(ctx, query, args...).Scan(&count); err != nil {
		return 0, fmt.Errorf("countUsers: %w", err)
	}
	return count, nil
}

// FetchAllUsers retrieves a filtered/paginated slice of User records.
func FetchAllUsers(ctx context.Context, db DBTX, opts ...QueryOption) ([]*models.User, error) {
	if db == nil {
		return nil, errors.New("fetchAllUsers: db is nil")
	}

	clause, args, cfg := applyQueryOptions("id", "deleted_at", opts...)
	if cfg.PreloadAssociations {
		return fetchAllUsersWithRelations(ctx, db, clause, args)
	}

	query := "SELECT id, name, email, created_at, deleted_at, age FROM users" + clause

	rows, err := db.QueryContext(ctx, query, args...)
	if err != nil {
		return nil, fmt.Errorf("fetchAllUsers: %w", err)
	}
	defer rows.Close()

	items := make([]*models.User, 0, 16)
	for rows.Next() {
		var m models.User
		if err := rows.Scan(&m.ID, &m.Name, &m.Email, scanNullable(&m.CreatedAt), scanNullable(&m.DeletedAt), &m.Age); err != nil {
			return nil, fmt.Errorf("fetchAllUsers: scanning row: %w", err)
		}
		items = append(items, &m)
	}

	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("fetchAllUsers: iterating rows: %w", err)
	}

	return items, nil
}

func getUserByIDWithRelations(ctx context.Context, db DBTX, id int64, cfg QueryOptions) (*models.User, error) {

	query := `
		SELECT 
			p.id, p.name, p.email, p.created_at, p.deleted_at, p.age, r0.order_id, r0.user_id, r0.amount
		FROM users p
		LEFT JOIN orders r0 ON r0.user_id = p.id
		WHERE p.id = $1
	`
	if !cfg.IncludeDeleted {
		query += " AND p.deleted_at IS NULL"
	}

	rows, err := db.QueryContext(ctx, query, id)
	if err != nil {
		return nil, fmt.Errorf("getUserByIDWithRelations(%v): %w", id, err)
	}
	defer rows.Close()

	var parent *models.User

	seen_Orders := make(map[int64]bool, 4)

	for rows.Next() {
		var p models.User

		var r0_ID int64
		var r0_UserID int64
		var r0_Amount float64

		scanArgs := []any{
			&p.ID, &p.Name, &p.Email, scanNullable(&p.CreatedAt), scanNullable(&p.DeletedAt), &p.Age,

			scanNullable(&r0_ID),
			scanNullable(&r0_UserID),
			scanNullable(&r0_Amount),
		}

		if err := rows.Scan(scanArgs...); err != nil {
			return nil, fmt.Errorf("getUserByIDWithRelations(%v): scanning row: %w", id, err)
		}

		if parent == nil {
			parent = &p
		}

		rPk0 := r0_ID
		if !IsZero(rPk0) {
			if !seen_Orders[rPk0] {
				seen_Orders[rPk0] = true
				child := models.Order{
					ID:     r0_ID,
					UserID: r0_UserID,
					Amount: r0_Amount,
				}

				parent.Orders = append(parent.Orders, child)

			}
		}

	}

	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("getUserByIDWithRelations(%v): iterating rows: %w", id, err)
	}
	if parent == nil {
		return nil, fmt.Errorf("getUserByIDWithRelations(%v): %w", id, sql.ErrNoRows)
	}

	return parent, nil
}

func fetchAllUsersWithRelations(ctx context.Context, db DBTX, clause string, args []any) ([]*models.User, error) {
	query := `
		WITH p AS (
			SELECT p.id, p.name, p.email, p.created_at, p.deleted_at, p.age
			FROM users p
	` + clause + `
		)
		SELECT 
			p.id, p.name, p.email, p.created_at, p.deleted_at, p.age, r0.order_id, r0.user_id, r0.amount
		FROM p
		LEFT JOIN orders r0 ON r0.user_id = p.id
		ORDER BY p.id ASC
	`

	rows, err := db.QueryContext(ctx, query, args...)
	if err != nil {
		return nil, fmt.Errorf("fetchAllUsersWithRelations: %w", err)
	}
	defer rows.Close()

	items := make([]*models.User, 0, 16)
	itemsMap := make(map[int64]*models.User, 16)

	seen_Orders := make(map[int64]map[int64]bool, 16)

	for rows.Next() {
		var p models.User

		var r0_ID int64
		var r0_UserID int64
		var r0_Amount float64

		scanArgs := []any{
			&p.ID, &p.Name, &p.Email, scanNullable(&p.CreatedAt), scanNullable(&p.DeletedAt), &p.Age,

			scanNullable(&r0_ID),
			scanNullable(&r0_UserID),
			scanNullable(&r0_Amount),
		}

		if err := rows.Scan(scanArgs...); err != nil {
			return nil, fmt.Errorf("fetchAllUsersWithRelations: scanning row: %w", err)
		}

		pPK := p.ID
		parent, exists := itemsMap[pPK]
		if !exists {
			parent = &p
			itemsMap[pPK] = parent
			items = append(items, parent)

			seen_Orders[pPK] = make(map[int64]bool, 4)

		}

		rPk0 := r0_ID
		if !IsZero(rPk0) {
			if !seen_Orders[pPK][rPk0] {
				seen_Orders[pPK][rPk0] = true
				child := models.Order{
					ID:     r0_ID,
					UserID: r0_UserID,
					Amount: r0_Amount,
				}

				parent.Orders = append(parent.Orders, child)

			}
		}

	}

	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("fetchAllUsersWithRelations: iterating rows: %w", err)
	}

	return items, nil
}

// UpdateUser updates an existing User record in users.
func UpdateUser(ctx context.Context, db DBTX, m *models.User) error {
	if db == nil {
		return errors.New("updateUser: db is nil")
	}
	if m == nil {
		return errors.New("updateUser: m is nil")
	}

	const query = `
		UPDATE users
		SET name = $1, email = $2, created_at = $3, deleted_at = $4, age = $5
		WHERE id = $6
	`

	res, err := db.ExecContext(ctx, query, &m.Name, &m.Email, &m.CreatedAt, &m.DeletedAt, &m.Age, m.ID)
	if err != nil {
		return fmt.Errorf("updateUser(%v): %w", m.ID, err)
	}

	n, err := res.RowsAffected()
	if err != nil {
		return fmt.Errorf("detect rows affected: %w", err)
	}
	if n == 0 {
		return fmt.Errorf("updateUser(%v): %w", m.ID, sql.ErrNoRows)
	}
	return nil
}

// DeleteUser deletes the User record identified by id from users.
// If the model contains a DeletedAt column, it soft-deletes by setting DeletedAt to current timestamp
// unless the HardDelete() query option is supplied.
func DeleteUser(ctx context.Context, db DBTX, id int64, opts ...QueryOption) error {
	if db == nil {
		return errors.New("deleteUser: db is nil")
	}

	cfg := parseQueryOptions(opts...)
	if !cfg.HardDelete {
		const query = `UPDATE users SET deleted_at = CURRENT_TIMESTAMP WHERE id = $1 AND deleted_at IS NULL`
		res, err := db.ExecContext(ctx, query, id)
		if err != nil {
			return fmt.Errorf("deleteUser(%v): %w", id, err)
		}
		n, err := res.RowsAffected()
		if err != nil {
			return fmt.Errorf("detect rows affected: %w", err)
		}
		if n == 0 {
			return fmt.Errorf("deleteUser(%v): %w", id, sql.ErrNoRows)
		}
		return nil
	}

	const query = `DELETE FROM users WHERE id = $1`

	res, err := db.ExecContext(ctx, query, id)
	if err != nil {
		return fmt.Errorf("deleteUser(%v): %w", id, err)
	}

	n, err := res.RowsAffected()
	if err != nil {
		return fmt.Errorf("detect rows affected: %w", err)
	}
	if n == 0 {
		return fmt.Errorf("deleteUser(%v): %w", id, sql.ErrNoRows)
	}
	return nil
}

// DeleteUsers deletes records from users matching the provided query options and returns the number of affected rows.
// Requires at least one filtering option (e.g. Where, In, Lt) to prevent accidental bulk deletion.
// If the model contains a DeletedAt column, it soft-deletes records by default unless the HardDelete() option is supplied.
func DeleteUsers(ctx context.Context, db DBTX, opts ...QueryOption) (int64, error) {
	if db == nil {
		return 0, errors.New("deleteUsers: db is nil")
	}

	cfg := parseQueryOptions(opts...)
	if cfg.Where == "" {
		return 0, errors.New("deleteUsers: query options/where clause required to prevent accidental bulk deletion")
	}

	clause, args, cfg := applyQueryOptions("", "deleted_at", opts...)

	var query string

	if !cfg.HardDelete {
		query = "UPDATE users SET deleted_at = CURRENT_TIMESTAMP" + clause
	} else {
		query = "DELETE FROM users" + clause
	}

	res, err := db.ExecContext(ctx, query, args...)
	if err != nil {
		return 0, fmt.Errorf("deleteUsers: %w", err)
	}

	n, err := res.RowsAffected()
	if err != nil {
		return 0, fmt.Errorf("deleteUsers: detecting rows affected: %w", err)
	}

	return n, nil
}
