// Code generated by query-gen. DO NOT EDIT.
package queries

import (
	"context"
	"database/sql"
	"errors"
	"fmt"
	"strings"

	"github.com/abiiranathan/query-gen/example/models"
)

// InsertUser inserts a new User record into the users table.
func InsertUser(ctx context.Context, db DBTX, m *models.User) error {
	if db == nil {
		return errors.New("insertUser: db is nil")
	}
	if m == nil {
		return errors.New("insertUser: m is nil")
	}

	const query = `
		INSERT INTO users (name, email, created_at)
		VALUES ($1, $2, $3)
		RETURNING id
	`

	if err := db.QueryRowContext(ctx, query, &m.Name, &m.Email, &m.CreatedAt).Scan(&m.ID); err != nil {
		return fmt.Errorf("insertUser: %w", err)
	}
	return nil
}

// GetUserByID retrieves a single User record from users by its primary key.
func GetUserByID(ctx context.Context, db DBTX, id int64, opts ...QueryOption) (*models.User, error) {
	if db == nil {
		return nil, errors.New("getUserByID: db is nil")
	}

	cfg := parseQueryOptions(opts...)

	const query = `
		SELECT id, name, email, created_at
		FROM users
		WHERE id = $1
	`

	row := db.QueryRowContext(ctx, query, id)
	var m models.User
	if err := row.Scan(&m.ID, &m.Name, &m.Email, &m.CreatedAt); err != nil {
		return nil, fmt.Errorf("getUserByID(%v): %w", id, err)
	}

	if cfg.PreloadAssociations {
		if err := preloadUserAssociations(ctx, db, []*models.User{&m}); err != nil {
			return nil, fmt.Errorf("getUserByID(%v): preloading associations: %w", id, err)
		}
	}

	return &m, nil
}

// ExistsUserByID reports whether a User record with the given primary key exists.
func ExistsUserByID(ctx context.Context, db DBTX, id int64) (bool, error) {
	if db == nil {
		return false, errors.New("existsUserByID: db is nil")
	}

	const query = `SELECT EXISTS(SELECT 1 FROM users WHERE id = $1)`

	var exists bool
	if err := db.QueryRowContext(ctx, query, id).Scan(&exists); err != nil {
		return false, fmt.Errorf("existsUserByID(%v): %w", id, err)
	}
	return exists, nil
}

// CountUsers returns total records matching optional filter criteria.
func CountUsers(ctx context.Context, db DBTX, opts ...QueryOption) (int64, error) {
	if db == nil {
		return 0, errors.New("countUsers: db is nil")
	}

	clause, args, _ := applyQueryOptions("", opts...)
	query := "SELECT COUNT(*) FROM users" + clause

	var count int64
	if err := db.QueryRowContext(ctx, query, args...).Scan(&count); err != nil {
		return 0, fmt.Errorf("countUsers: %w", err)
	}
	return count, nil
}

// FetchAllUsers retrieves a filtered/paginated slice of User records.
func FetchAllUsers(ctx context.Context, db DBTX, opts ...QueryOption) ([]*models.User, error) {
	if db == nil {
		return nil, errors.New("fetchAllUsers: db is nil")
	}

	clause, args, cfg := applyQueryOptions("id", opts...)
	query := "SELECT id, name, email, created_at FROM users" + clause

	rows, err := db.QueryContext(ctx, query, args...)
	if err != nil {
		return nil, fmt.Errorf("fetchAllUsers: %w", err)
	}
	defer rows.Close()

	var items []*models.User
	for rows.Next() {
		var m models.User
		if err := rows.Scan(&m.ID, &m.Name, &m.Email, &m.CreatedAt); err != nil {
			return nil, fmt.Errorf("fetchAllUsers: scanning row: %w", err)
		}
		items = append(items, &m)
	}

	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("fetchAllUsers: iterating rows: %w", err)
	}

	if cfg.PreloadAssociations && len(items) > 0 {
		if err := preloadUserAssociations(ctx, db, items); err != nil {
			return nil, fmt.Errorf("fetchAllUsers: preloading associations: %w", err)
		}
	}

	return items, nil
}

func preloadUserAssociations(ctx context.Context, db DBTX, items []*models.User) error {
	if len(items) == 0 {
		return nil
	}

	// Preload Orders (HasMany)
	{
		parentMap := make(map[int64]*models.User, len(items))
		pkArgs := make([]any, 0, len(items))
		placeholders := make([]string, 0, len(items))

		for _, item := range items {
			if item != nil {
				parentMap[item.ID] = item
				pkArgs = append(pkArgs, item.ID)
				placeholders = append(placeholders, fmt.Sprintf("$%d", len(pkArgs)))
			}
		}

		if len(pkArgs) > 0 {
			query := fmt.Sprintf(
				"SELECT order_id, user_id, amount FROM orders WHERE user_id IN (%s)",
				strings.Join(placeholders, ", "),
			)
			rows, err := db.QueryContext(ctx, query, pkArgs...)
			if err != nil {
				return fmt.Errorf("preload User.Orders: %w", err)
			}
			defer rows.Close()

			for rows.Next() {
				var child models.Order
				if err := rows.Scan(&child.ID, &child.UserID, &child.Amount); err != nil {
					return fmt.Errorf("preload User.Orders scan: %w", err)
				}

				if parent, ok := parentMap[child.UserID]; ok {
					parent.Orders = append(parent.Orders, child)
				}

			}
			if err := rows.Err(); err != nil {
				return fmt.Errorf("preload User.Orders iteration: %w", err)
			}
		}
	}

	return nil
}

// UpdateUser updates an existing User record in users.
func UpdateUser(ctx context.Context, db DBTX, m *models.User) error {
	if db == nil {
		return errors.New("updateUser: db is nil")
	}
	if m == nil {
		return errors.New("updateUser: m is nil")
	}

	const query = `
		UPDATE users
		SET name = $1, email = $2, created_at = $3
		WHERE id = $4
	`

	res, err := db.ExecContext(ctx, query, &m.Name, &m.Email, &m.CreatedAt, m.ID)
	if err != nil {
		return fmt.Errorf("updateUser(%v): %w", m.ID, err)
	}

	n, err := res.RowsAffected()
	if err != nil {
		return nil
	}
	if n == 0 {
		return fmt.Errorf("updateUser(%v): %w", m.ID, sql.ErrNoRows)
	}
	return nil
}

// DeleteUser deletes the User record identified by id from users.
func DeleteUser(ctx context.Context, db DBTX, id int64) error {
	if db == nil {
		return errors.New("deleteUser: db is nil")
	}

	const query = `DELETE FROM users WHERE id = $1`

	res, err := db.ExecContext(ctx, query, id)
	if err != nil {
		return fmt.Errorf("deleteUser(%v): %w", id, err)
	}

	n, err := res.RowsAffected()
	if err != nil {
		return nil
	}
	if n == 0 {
		return fmt.Errorf("deleteUser(%v): %w", id, sql.ErrNoRows)
	}
	return nil
}
