// Code generated by query-gen. DO NOT EDIT.
package queries

import (
	"context"
	"database/sql"
	"errors"
	"fmt"

	"github.com/abiiranathan/query-gen/example/models"
)

// GetUserSummaryView retrieves a single UserSummaryView record matching mandatory query options/where clause.
// Returns sql.ErrNoRows if no matching record is found.
func GetUserSummaryView(ctx context.Context, db DBTX, opts ...QueryOption) (*models.UserSummaryView, error) {
	if db == nil {
		return nil, errors.New("getUserSummaryView: db is nil")
	}

	cfg := parseQueryOptions(opts...)
	if cfg.Where == "" {
		return nil, errors.New("getUserSummaryView: query options/where clause required to prevent returning arbitrary row")
	}

	pOpts := append([]QueryOption(nil), opts...)
	pOpts = append(pOpts, Limit(1))

	items, err := FetchAllUserSummaryViews(ctx, db, pOpts...)
	if err != nil {
		return nil, fmt.Errorf("getUserSummaryView: %w", err)
	}
	if len(items) == 0 {
		return nil, fmt.Errorf("getUserSummaryView: %w", sql.ErrNoRows)
	}
	return items[0], nil
}

// ExistsUserSummaryView reports whether a UserSummaryView record matching the mandatory query options/where clause exists.
func ExistsUserSummaryView(ctx context.Context, db DBTX, opts ...QueryOption) (bool, error) {
	if db == nil {
		return false, errors.New("existsUserSummaryView: db is nil")
	}

	cfg := parseQueryOptions(opts...)
	if cfg.Where == "" {
		return false, errors.New("existsUserSummaryView: query options/where clause required")
	}

	var whereClause string
	if cfg.Where != "" {
		whereClause = " WHERE " + cfg.Where
	}

	tableName := "user_summary_views"
	if cfg.Table != "" {
		tableName = cfg.Table
	}

	query := "SELECT EXISTS(SELECT 1 FROM " + tableName + whereClause + ")"

	var exists bool
	if err := db.QueryRowContext(ctx, query, cfg.Args...).Scan(&exists); err != nil {
		return false, fmt.Errorf("existsUserSummaryView: %w", err)
	}
	return exists, nil
}

// CountUserSummaryViews returns total records matching optional filter criteria.
func CountUserSummaryViews(ctx context.Context, db DBTX, opts ...QueryOption) (int64, error) {
	if db == nil {
		return 0, errors.New("countUserSummaryViews: db is nil")
	}

	cfg := parseQueryOptions(opts...)

	var whereClause string
	if cfg.Where != "" {
		whereClause = " WHERE " + cfg.Where
	}

	tableName := "user_summary_views"
	if cfg.Table != "" {
		tableName = cfg.Table
	}

	query := "SELECT COUNT(*) FROM " + tableName + whereClause

	var count int64
	if err := db.QueryRowContext(ctx, query, cfg.Args...).Scan(&count); err != nil {
		return 0, fmt.Errorf("countUserSummaryViews: %w", err)
	}
	return count, nil
}

// FetchAllUserSummaryViews retrieves a filtered/paginated slice of UserSummaryView records.
func FetchAllUserSummaryViews(ctx context.Context, db DBTX, opts ...QueryOption) ([]*models.UserSummaryView, error) {
	if db == nil {
		return nil, errors.New("fetchAllUserSummaryViews: db is nil")
	}

	clause, args, cfg := applyQueryOptions("", "", opts...)

	tableName := "user_summary_views"
	if cfg.Table != "" {
		tableName = cfg.Table
	}

	query := "SELECT user_id, name, email, registered_at FROM " + tableName + clause

	rows, err := db.QueryContext(ctx, query, args...)
	if err != nil {
		return nil, fmt.Errorf("fetchAllUserSummaryViews: %w", err)
	}
	defer rows.Close()

	items := make([]*models.UserSummaryView, 0, 16)
	for rows.Next() {
		var m models.UserSummaryView
		if err := rows.Scan(&m.UserID, &m.Name, &m.Email, scanNullable(&m.RegisteredAt)); err != nil {
			return nil, fmt.Errorf("fetchAllUserSummaryViews: scanning row: %w", err)
		}
		items = append(items, &m)
	}

	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("fetchAllUserSummaryViews: iterating rows: %w", err)
	}

	return items, nil
}

// ================= FETCHING RELATIONS ===============================
