// Code generated by query-gen. DO NOT EDIT.
package queries

import (
	"context"
	"database/sql"
	"errors"
	"fmt"
	"slices"
	"strings"

	"github.com/abiiranathan/query-gen/example/models"
)

// InsertUserRole inserts a new UserRole record into the user_roles table.
func InsertUserRole(ctx context.Context, db DBTX, m *models.UserRole) error {
	if db == nil {
		return errors.New("insertUserRole: db is nil")
	}
	if m == nil {
		return errors.New("insertUserRole: m is nil")
	}

	fields := []struct {
		col        string
		val        any
		omitIfZero bool
	}{
		{col: "user_id", val: m.UserID, omitIfZero: false},
		{col: "role_id", val: m.RoleID, omitIfZero: false},
		{col: "assigned_at", val: m.AssignedAt, omitIfZero: true},
	}

	cols := make([]string, 0, len(fields))
	args := make([]any, 0, len(fields))
	placeholders := make([]string, 0, len(fields))

	for _, f := range fields {
		if f.omitIfZero && IsZero(f.val) {
			continue
		}
		cols = append(cols, f.col)
		args = append(args, f.val)
		placeholders = append(placeholders, fmt.Sprintf("$%d", len(args)))
	}

	var query string
	if len(cols) == 0 {
		query = "INSERT INTO user_roles DEFAULT VALUES RETURNING user_id, role_id, assigned_at"
	} else {
		query = fmt.Sprintf("INSERT INTO user_roles (%s) VALUES (%s) RETURNING user_id, role_id, assigned_at",
			strings.Join(cols, ", "), strings.Join(placeholders, ", "))
	}

	if err := db.QueryRowContext(ctx, query, args...).
		Scan(&m.UserID, &m.RoleID, scanNullable(&m.AssignedAt)); err != nil {
		return fmt.Errorf("insertUserRole: %w", err)
	}
	return nil
}

// ============ Bulk insert ========================

// InsertUserRoles inserts multiple UserRole records into user_roles in efficient parameter-bounded batches.
// Automatically populates database-generated values (e.g., auto-increment primary keys, default values) back into input structs via RETURNING.
func InsertUserRoles(ctx context.Context, db DBTX, models []*models.UserRole) error {
	if db == nil {
		return errors.New("insertUserRoles: db is nil")
	}
	if len(models) == 0 {
		return nil
	}

	const batchSize = 333
	for i := 0; i < len(models); i += batchSize {
		end := min((i + batchSize), len(models))
		batch := models[i:end]
		if err := insertUserRolesBatch(ctx, db, batch); err != nil {
			return fmt.Errorf("insertUserRoles: batch [%d:%d]: %w", i, end, err)
		}
	}
	return nil
}

func insertUserRolesBatch(ctx context.Context, db DBTX, batch []*models.UserRole) error {
	if len(batch) == 0 {
		return nil
	}

	args := make([]any, 0, len(batch)*3)
	var sb strings.Builder
	sb.Grow(128 + len(batch)*3*8)
	sb.WriteString("INSERT INTO user_roles (user_id, role_id, assigned_at) VALUES ")

	paramIdx := 1
	for i, m := range batch {
		if m == nil {
			return fmt.Errorf("model at index %d is nil", i)
		}
		if i > 0 {
			sb.WriteString(", ")
		}
		sb.WriteByte('(')

		sb.WriteString(getPlaceholder(paramIdx))
		paramIdx++
		args = append(args, m.UserID)
		sb.WriteString(", ")
		sb.WriteString(getPlaceholder(paramIdx))
		paramIdx++
		args = append(args, m.RoleID)
		sb.WriteString(", ")
		sb.WriteString(getPlaceholder(paramIdx))
		paramIdx++
		args = append(args, m.AssignedAt)
		sb.WriteByte(')')
	}

	sb.WriteString(" RETURNING user_id, role_id, assigned_at")
	rows, err := db.QueryContext(ctx, sb.String(), args...)
	if err != nil {
		return fmt.Errorf("executing bulk insert: %w", err)
	}
	defer rows.Close()

	idx := 0
	for rows.Next() {
		if idx >= len(batch) {
			return errors.New("unexpected extra row returned from insert")
		}
		m := batch[idx]
		if err := rows.Scan(&m.UserID, &m.RoleID, scanNullable(&m.AssignedAt)); err != nil {
			return fmt.Errorf("scanning row %d: %w", idx, err)
		}
		idx++
	}

	if err := rows.Err(); err != nil {
		return fmt.Errorf("iterating bulk insert rows: %w", err)
	}

	if idx < len(batch) {
		return fmt.Errorf("expected %d inserted rows, got %d", len(batch), idx)
	}

	return nil
}

// GetUserRoleByID retrieves a single UserRole record from user_roles by its primary key.
func GetUserRoleByID(ctx context.Context, db DBTX, userID int64, roleID int64, opts ...QueryOption) (*models.UserRole, error) {
	if db == nil {
		return nil, errors.New("getUserRoleByID: db is nil")
	}

	const query = `
		SELECT user_id, role_id, assigned_at
		FROM user_roles
		WHERE user_id = $1 AND role_id = $2
	`

	row := db.QueryRowContext(ctx, query, userID, roleID)
	var m models.UserRole
	if err := row.Scan(&m.UserID, &m.RoleID, scanNullable(&m.AssignedAt)); err != nil {
		return nil, fmt.Errorf("getUserRoleByID(%v): %w", fmt.Sprint(userID, roleID), err)
	}

	return &m, nil
}

// GetUserRole retrieves a single UserRole record matching mandatory query options/where clause.
// Returns sql.ErrNoRows if no matching record is found.
func GetUserRole(ctx context.Context, db DBTX, opts ...QueryOption) (*models.UserRole, error) {
	if db == nil {
		return nil, errors.New("getUserRole: db is nil")
	}

	cfg := parseQueryOptions(opts...)
	if cfg.Where == "" {
		return nil, errors.New("getUserRole: query options/where clause required to prevent returning arbitrary row")
	}

	pOpts := append([]QueryOption(nil), opts...)
	pOpts = append(pOpts, Limit(1))

	items, err := FetchAllUserRoles(ctx, db, pOpts...)
	if err != nil {
		return nil, fmt.Errorf("getUserRole: %w", err)
	}
	if len(items) == 0 {
		return nil, fmt.Errorf("getUserRole: %w", sql.ErrNoRows)
	}
	return items[0], nil
}

// UpdateUserRoleColumns updates only the specified updatable columns/fields for an existing UserRole record in user_roles.
// Column arguments can be database column names (e.g. "email") or Go field names (e.g. "Email").
func UpdateUserRoleColumns(ctx context.Context, db DBTX, m *models.UserRole, cols ...string) error {
	if db == nil {
		return errors.New("updateUserRoleColumns: db is nil")
	}
	if m == nil {
		return errors.New("updateUserRoleColumns: m is nil")
	}
	if len(cols) == 0 {
		return errors.New("updateUserRoleColumns: at least one column/field must be specified")
	}

	allowedColumns := []string{
		"assigned_at", "AssignedAt",
	}

	setClauses := make([]string, 0, len(cols))
	args := make([]any, 0, len(cols)+2)

	for _, col := range cols {
		if !slices.Contains(allowedColumns, col) {
			return fmt.Errorf("updateUserRoleColumns: column or field %q is not updatable", col)
		}

		var dbCol string
		var val any

		switch col {
		case "assigned_at", "AssignedAt":
			dbCol = "assigned_at"
			val = m.AssignedAt
		}

		args = append(args, val)
		setClauses = append(setClauses, fmt.Sprintf("%s = $%d", dbCol, len(args)))
	}

	pkClauses := make([]string, 0, 2)
	pkClauses = append(pkClauses, fmt.Sprintf("%s = $%d", "user_id", len(args)+0+1))
	pkClauses = append(pkClauses, fmt.Sprintf("%s = $%d", "role_id", len(args)+1+1))
	query := fmt.Sprintf("UPDATE user_roles SET %s WHERE %s",
		strings.Join(setClauses, ", "), strings.Join(pkClauses, " AND "))

	args = append(args, m.UserID, m.RoleID)

	res, err := db.ExecContext(ctx, query, args...)
	if err != nil {
		return fmt.Errorf("updateUserRoleColumns(%v): %w", fmt.Sprint(m.UserID, m.RoleID), err)
	}

	n, err := res.RowsAffected()
	if err != nil {
		return fmt.Errorf("detect rows affected: %w", err)
	}
	if n == 0 {
		return fmt.Errorf("updateUserRoleColumns(%v): %w", fmt.Sprint(m.UserID, m.RoleID), sql.ErrNoRows)
	}
	return nil
}

// ExistsUserRoleByID reports whether a UserRole record with the given primary key exists.
func ExistsUserRoleByID(ctx context.Context, db DBTX, userID int64, roleID int64, opts ...QueryOption) (bool, error) {
	if db == nil {
		return false, errors.New("existsUserRoleByID: db is nil")
	}

	const query = `SELECT EXISTS(SELECT 1 FROM user_roles WHERE user_id = $1 AND role_id = $2)`

	var exists bool
	if err := db.QueryRowContext(ctx, query, userID, roleID).Scan(&exists); err != nil {
		return false, fmt.Errorf("existsUserRoleByID(%v): %w", fmt.Sprint(userID, roleID), err)
	}
	return exists, nil
}

// ExistsUserRole reports whether a UserRole record matching the mandatory query options/where clause exists.
func ExistsUserRole(ctx context.Context, db DBTX, opts ...QueryOption) (bool, error) {
	if db == nil {
		return false, errors.New("existsUserRole: db is nil")
	}

	cfg := parseQueryOptions(opts...)
	if cfg.Where == "" {
		return false, errors.New("existsUserRole: query options/where clause required")
	}

	var whereClause string
	if cfg.Where != "" {
		whereClause = " WHERE " + cfg.Where
	}

	query := "SELECT EXISTS(SELECT 1 FROM user_roles" + whereClause + ")"

	var exists bool
	if err := db.QueryRowContext(ctx, query, cfg.Args...).Scan(&exists); err != nil {
		return false, fmt.Errorf("existsUserRole: %w", err)
	}
	return exists, nil
}

// CountUserRoles returns total records matching optional filter criteria.
func CountUserRoles(ctx context.Context, db DBTX, opts ...QueryOption) (int64, error) {
	if db == nil {
		return 0, errors.New("countUserRoles: db is nil")
	}

	cfg := parseQueryOptions(opts...)

	var whereClause string
	if cfg.Where != "" {
		whereClause = " WHERE " + cfg.Where
	}

	query := "SELECT COUNT(*) FROM user_roles" + whereClause

	var count int64
	if err := db.QueryRowContext(ctx, query, cfg.Args...).Scan(&count); err != nil {
		return 0, fmt.Errorf("countUserRoles: %w", err)
	}
	return count, nil
}

// FetchAllUserRoles retrieves a filtered/paginated slice of UserRole records.
func FetchAllUserRoles(ctx context.Context, db DBTX, opts ...QueryOption) ([]*models.UserRole, error) {
	if db == nil {
		return nil, errors.New("fetchAllUserRoles: db is nil")
	}

	clause, args, _ := applyQueryOptions("user_id, role_id", "", opts...)

	query := "SELECT user_id, role_id, assigned_at FROM user_roles" + clause

	rows, err := db.QueryContext(ctx, query, args...)
	if err != nil {
		return nil, fmt.Errorf("fetchAllUserRoles: %w", err)
	}
	defer rows.Close()

	items := make([]*models.UserRole, 0, 16)
	for rows.Next() {
		var m models.UserRole
		if err := rows.Scan(&m.UserID, &m.RoleID, scanNullable(&m.AssignedAt)); err != nil {
			return nil, fmt.Errorf("fetchAllUserRoles: scanning row: %w", err)
		}
		items = append(items, &m)
	}

	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("fetchAllUserRoles: iterating rows: %w", err)
	}

	return items, nil
}

// UpdateUserRole updates an existing UserRole record in user_roles.
func UpdateUserRole(ctx context.Context, db DBTX, m *models.UserRole) error {
	if db == nil {
		return errors.New("updateUserRole: db is nil")
	}
	if m == nil {
		return errors.New("updateUserRole: m is nil")
	}

	const query = `
		UPDATE user_roles
		SET assigned_at = $1
		WHERE user_id = $2 AND role_id = $3
	`

	res, err := db.ExecContext(ctx, query, &m.AssignedAt, m.UserID, m.RoleID)
	if err != nil {
		return fmt.Errorf("updateUserRole(%v): %w", fmt.Sprint(m.UserID, m.RoleID), err)
	}

	n, err := res.RowsAffected()
	if err != nil {
		return fmt.Errorf("detect rows affected: %w", err)
	}
	if n == 0 {
		return fmt.Errorf("updateUserRole(%v): %w", fmt.Sprint(m.UserID, m.RoleID), sql.ErrNoRows)
	}
	return nil
}

// DeleteUserRole deletes the UserRole record identified by primary key from user_roles.
func DeleteUserRole(ctx context.Context, db DBTX, userID int64, roleID int64, opts ...QueryOption) error {
	if db == nil {
		return errors.New("deleteUserRole: db is nil")
	}

	const query = `DELETE FROM user_roles WHERE user_id = $1 AND role_id = $2`

	res, err := db.ExecContext(ctx, query, userID, roleID)
	if err != nil {
		return fmt.Errorf("deleteUserRole(%v): %w", fmt.Sprint(userID, roleID), err)
	}

	n, err := res.RowsAffected()
	if err != nil {
		return fmt.Errorf("detect rows affected: %w", err)
	}
	if n == 0 {
		return fmt.Errorf("deleteUserRole(%v): %w", fmt.Sprint(userID, roleID), sql.ErrNoRows)
	}
	return nil
}

// DeleteUserRoles deletes records from user_roles matching the provided query options and returns the number of affected rows.
func DeleteUserRoles(ctx context.Context, db DBTX, opts ...QueryOption) (int64, error) {
	if db == nil {
		return 0, errors.New("deleteUserRoles: db is nil")
	}

	cfg := parseQueryOptions(opts...)
	if cfg.Where == "" {
		return 0, errors.New("deleteUserRoles: query options/where clause required to prevent accidental bulk deletion")
	}

	clause, args, _ := applyQueryOptions("", "", opts...)

	var query string
	query = "DELETE FROM user_roles" + clause

	res, err := db.ExecContext(ctx, query, args...)
	if err != nil {
		return 0, fmt.Errorf("deleteUserRoles: %w", err)
	}

	n, err := res.RowsAffected()
	if err != nil {
		return 0, fmt.Errorf("deleteUserRoles: detecting rows affected: %w", err)
	}

	return n, nil
}

// ================= FETCHING RELATIONS ===============================
