// Code generated by query-gen. DO NOT EDIT.
package queries

import (
	"context"
	"database/sql"
	"errors"
	"fmt"
	"strings"

	"github.com/abiiranathan/query-gen/example/models"
)

// InsertUserRole inserts a new UserRole record into the user_roles table.
func InsertUserRole(ctx context.Context, db DBTX, m *models.UserRole) error {
	if db == nil {
		return errors.New("insertUserRole: db is nil")
	}
	if m == nil {
		return errors.New("insertUserRole: m is nil")
	}

	fields := []struct {
		col        string
		val        any
		omitIfZero bool
	}{
		{col: "user_id", val: m.UserID, omitIfZero: false},
		{col: "role_id", val: m.RoleID, omitIfZero: false},
		{col: "assigned_at", val: m.AssignedAt, omitIfZero: true},
	}

	cols := make([]string, 0, len(fields))
	args := make([]any, 0, len(fields))
	placeholders := make([]string, 0, len(fields))

	for _, f := range fields {
		if f.omitIfZero && IsZero(f.val) {
			continue
		}
		cols = append(cols, f.col)
		args = append(args, f.val)
		placeholders = append(placeholders, fmt.Sprintf("$%d", len(args)))
	}

	var query string
	if len(cols) == 0 {
		query = "INSERT INTO user_roles DEFAULT VALUES RETURNING user_id, role_id, assigned_at"
	} else {
		query = fmt.Sprintf("INSERT INTO user_roles (%s) VALUES (%s) RETURNING user_id, role_id, assigned_at",
			strings.Join(cols, ", "), strings.Join(placeholders, ", "))
	}

	if err := db.QueryRowContext(ctx, query, args...).
		Scan(&m.UserID, &m.RoleID, scanNullable(&m.AssignedAt)); err != nil {
		return fmt.Errorf("insertUserRole: %w", err)
	}
	return nil
}

// GetUserRoleByID retrieves a single UserRole record from user_roles by its primary key.
func GetUserRoleByID(ctx context.Context, db DBTX, userID int64, roleID int64, opts ...QueryOption) (*models.UserRole, error) {
	if db == nil {
		return nil, errors.New("getUserRoleByID: db is nil")
	}

	const query = `
		SELECT user_id, role_id, assigned_at
		FROM user_roles
		WHERE user_id = $1 AND role_id = $2
	`

	row := db.QueryRowContext(ctx, query, userID, roleID)
	var m models.UserRole
	if err := row.Scan(&m.UserID, &m.RoleID, scanNullable(&m.AssignedAt)); err != nil {
		return nil, fmt.Errorf("getUserRoleByID(%v): %w", fmt.Sprint(userID, roleID), err)
	}

	return &m, nil
}

// ExistsUserRoleByID reports whether a UserRole record with the given primary key exists.
func ExistsUserRoleByID(ctx context.Context, db DBTX, userID int64, roleID int64, opts ...QueryOption) (bool, error) {
	if db == nil {
		return false, errors.New("existsUserRoleByID: db is nil")
	}

	const query = `SELECT EXISTS(SELECT 1 FROM user_roles WHERE user_id = $1 AND role_id = $2)`

	var exists bool
	if err := db.QueryRowContext(ctx, query, userID, roleID).Scan(&exists); err != nil {
		return false, fmt.Errorf("existsUserRoleByID(%v): %w", fmt.Sprint(userID, roleID), err)
	}
	return exists, nil
}

// CountUserRoles returns total records matching optional filter criteria.
func CountUserRoles(ctx context.Context, db DBTX, opts ...QueryOption) (int64, error) {
	if db == nil {
		return 0, errors.New("countUserRoles: db is nil")
	}

	cfg := parseQueryOptions(opts...)

	var whereClause string
	if cfg.Where != "" {
		whereClause = " WHERE " + cfg.Where
	}

	query := "SELECT COUNT(*) FROM user_roles" + whereClause

	var count int64
	if err := db.QueryRowContext(ctx, query, cfg.Args...).Scan(&count); err != nil {
		return 0, fmt.Errorf("countUserRoles: %w", err)
	}
	return count, nil
}

// FetchAllUserRoles retrieves a filtered/paginated slice of UserRole records.
func FetchAllUserRoles(ctx context.Context, db DBTX, opts ...QueryOption) ([]*models.UserRole, error) {
	if db == nil {
		return nil, errors.New("fetchAllUserRoles: db is nil")
	}

	clause, args, _ := applyQueryOptions("user_id, role_id", "", opts...)

	query := "SELECT user_id, role_id, assigned_at FROM user_roles" + clause

	rows, err := db.QueryContext(ctx, query, args...)
	if err != nil {
		return nil, fmt.Errorf("fetchAllUserRoles: %w", err)
	}
	defer rows.Close()

	items := make([]*models.UserRole, 0, 16)
	for rows.Next() {
		var m models.UserRole
		if err := rows.Scan(&m.UserID, &m.RoleID, scanNullable(&m.AssignedAt)); err != nil {
			return nil, fmt.Errorf("fetchAllUserRoles: scanning row: %w", err)
		}
		items = append(items, &m)
	}

	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("fetchAllUserRoles: iterating rows: %w", err)
	}

	return items, nil
}

// UpdateUserRole updates an existing UserRole record in user_roles.
func UpdateUserRole(ctx context.Context, db DBTX, m *models.UserRole) error {
	if db == nil {
		return errors.New("updateUserRole: db is nil")
	}
	if m == nil {
		return errors.New("updateUserRole: m is nil")
	}

	const query = `
		UPDATE user_roles
		SET assigned_at = $1
		WHERE user_id = $2 AND role_id = $3
	`

	res, err := db.ExecContext(ctx, query, &m.AssignedAt, m.UserID, m.RoleID)
	if err != nil {
		return fmt.Errorf("updateUserRole(%v): %w", fmt.Sprint(m.UserID, m.RoleID), err)
	}

	n, err := res.RowsAffected()
	if err != nil {
		return fmt.Errorf("detect rows affected: %w", err)
	}
	if n == 0 {
		return fmt.Errorf("updateUserRole(%v): %w", fmt.Sprint(m.UserID, m.RoleID), sql.ErrNoRows)
	}
	return nil
}

// DeleteUserRole deletes the UserRole record identified by primary key from user_roles.
func DeleteUserRole(ctx context.Context, db DBTX, userID int64, roleID int64, opts ...QueryOption) error {
	if db == nil {
		return errors.New("deleteUserRole: db is nil")
	}

	const query = `DELETE FROM user_roles WHERE user_id = $1 AND role_id = $2`

	res, err := db.ExecContext(ctx, query, userID, roleID)
	if err != nil {
		return fmt.Errorf("deleteUserRole(%v): %w", fmt.Sprint(userID, roleID), err)
	}

	n, err := res.RowsAffected()
	if err != nil {
		return fmt.Errorf("detect rows affected: %w", err)
	}
	if n == 0 {
		return fmt.Errorf("deleteUserRole(%v): %w", fmt.Sprint(userID, roleID), sql.ErrNoRows)
	}
	return nil
}

// DeleteUserRoles deletes records from user_roles matching the provided query options and returns the number of affected rows.
func DeleteUserRoles(ctx context.Context, db DBTX, opts ...QueryOption) (int64, error) {
	if db == nil {
		return 0, errors.New("deleteUserRoles: db is nil")
	}

	cfg := parseQueryOptions(opts...)
	if cfg.Where == "" {
		return 0, errors.New("deleteUserRoles: query options/where clause required to prevent accidental bulk deletion")
	}

	clause, args, _ := applyQueryOptions("", "", opts...)

	var query string
	query = "DELETE FROM user_roles" + clause

	res, err := db.ExecContext(ctx, query, args...)
	if err != nil {
		return 0, fmt.Errorf("deleteUserRoles: %w", err)
	}

	n, err := res.RowsAffected()
	if err != nil {
		return 0, fmt.Errorf("deleteUserRoles: detecting rows affected: %w", err)
	}

	return n, nil
}

// ================= FETCHING RELATIONS ===============================
