// Code generated by query-gen. DO NOT EDIT.
package queries

import (
	"context"
	"database/sql"
	"errors"
	"fmt"

	"github.com/abiiranathan/query-gen/example/models"
)

// InsertUser inserts a new User record into the users table.
func InsertUser(ctx context.Context, db DBTX, m *models.User) error {
	if db == nil {
		return errors.New("insertUser: db is nil")
	}
	if m == nil {
		return errors.New("insertUser: m is nil")
	}

	const query = `
		INSERT INTO users (name, email, created_at)
		VALUES ($1, $2, $3)
		RETURNING id
	`

	if err := db.QueryRowContext(ctx, query, &m.Name, &m.Email, &m.CreatedAt).Scan(&m.ID); err != nil {
		return fmt.Errorf("insertUser: %w", err)
	}
	return nil
}

// GetUserByID retrieves a single User record from users by its primary key.
func GetUserByID(ctx context.Context, db DBTX, id int64) (*models.User, error) {
	if db == nil {
		return nil, errors.New("getUserByID: db is nil")
	}

	const query = `
		SELECT id, name, email, created_at
		FROM users
		WHERE id = $1
	`

	row := db.QueryRowContext(ctx, query, id)
	var m models.User
	if err := row.Scan(&m.ID, &m.Name, &m.Email, &m.CreatedAt); err != nil {
		return nil, fmt.Errorf("getUserByID(%v): %w", id, err)
	}
	return &m, nil
}

// ExistsUserByID reports whether a User record with the given primary key exists.
func ExistsUserByID(ctx context.Context, db DBTX, id int64) (bool, error) {
	if db == nil {
		return false, errors.New("existsUserByID: db is nil")
	}

	const query = `SELECT EXISTS(SELECT 1 FROM users WHERE id = $1)`

	var exists bool
	if err := db.QueryRowContext(ctx, query, id).Scan(&exists); err != nil {
		return false, fmt.Errorf("existsUserByID(%v): %w", id, err)
	}
	return exists, nil
}

// CountUsers returns total records matching optional filter criteria.
func CountUsers(ctx context.Context, db DBTX, opts ...QueryOption) (int64, error) {
	if db == nil {
		return 0, errors.New("countUsers: db is nil")
	}

	clause, args := applyQueryOptions("", opts...)
	query := "SELECT COUNT(*) FROM users" + clause

	var count int64
	if err := db.QueryRowContext(ctx, query, args...).Scan(&count); err != nil {
		return 0, fmt.Errorf("countUsers: %w", err)
	}
	return count, nil
}

// FetchAllUsers retrieves a filtered/paginated slice of User records without associations.
func FetchAllUsers(ctx context.Context, db DBTX, opts ...QueryOption) ([]*models.User, error) {
	if db == nil {
		return nil, errors.New("fetchAllUsers: db is nil")
	}

	clause, args := applyQueryOptions("id", opts...)
	query := "SELECT id, name, email, created_at FROM users" + clause

	rows, err := db.QueryContext(ctx, query, args...)
	if err != nil {
		return nil, fmt.Errorf("fetchAllUsers: %w", err)
	}
	defer rows.Close()

	var items []*models.User
	for rows.Next() {
		var m models.User
		if err := rows.Scan(&m.ID, &m.Name, &m.Email, &m.CreatedAt); err != nil {
			return nil, fmt.Errorf("fetchAllUsers: scanning row: %w", err)
		}
		items = append(items, &m)
	}

	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("fetchAllUsers: iterating rows: %w", err)
	}

	return items, nil
}

// GetUserWithOrdersByID fetches a User and its related Orders (HasMany) by primary key.
func GetUserWithOrdersByID(ctx context.Context, db DBTX, id int64) (*models.User, error) {
	if db == nil {
		return nil, errors.New("getUsersWithOrdersByID: db is nil")
	}

	const query = `
		SELECT 
			p.id, p.name, p.email, p.created_at,
			c.order_id, c.user_id, c.amount
		FROM users p
		LEFT JOIN orders c ON c.user_id = p.id
		WHERE p.id = $1
	`

	rows, err := db.QueryContext(ctx, query, id)
	if err != nil {
		return nil, fmt.Errorf("getUsersWithOrdersByID(%v): %w", id, err)
	}
	defer rows.Close()

	var parent *models.User
	parent = &models.User{}
	found := false

	for rows.Next() {
		var p models.User

		var child_ID int64
		var child_UserID int64
		var child_Amount float64

		scanArgs := []any{
			&p.ID, &p.Name, &p.Email, &p.CreatedAt,
			scanNullable(&child_ID),
			scanNullable(&child_UserID),
			scanNullable(&child_Amount),
		}

		if err := rows.Scan(scanArgs...); err != nil {
			return nil, fmt.Errorf("getUsersWithOrdersByID(%v): scanning row: %w", id, err)
		}

		if !found {
			found = true
			*parent = p
		}

		if !isZero(child_ID) {
			child := models.Order{
				ID:     child_ID,
				UserID: child_UserID,
				Amount: child_Amount,
			}
			parent.Orders = append(parent.Orders, child)
		}
	}

	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("getUsersWithOrdersByID(%v): iterating rows: %w", id, err)
	}
	if !found {
		return nil, fmt.Errorf("getUsersWithOrdersByID(%v): %w", id, sql.ErrNoRows)
	}

	return parent, nil
}

// FetchAllUsersWithOrders retrieves a filtered/paginated slice of User records with their associated Orders (HasMany).
func FetchAllUsersWithOrders(ctx context.Context, db DBTX, opts ...QueryOption) ([]*models.User, error) {
	if db == nil {
		return nil, errors.New("fetchAllUsersWithOrders: db is nil")
	}

	clause, args := applyQueryOptions("p."+"id", opts...)

	query := `
		WITH p AS (
			SELECT p.id, p.name, p.email, p.created_at
			FROM users p
	` + clause + `
		)
		SELECT 
			p.id, p.name, p.email, p.created_at,
			c.order_id, c.user_id, c.amount
		FROM p
		LEFT JOIN orders c ON c.user_id = p.id
		ORDER BY p.id ASC
	`

	rows, err := db.QueryContext(ctx, query, args...)
	if err != nil {
		return nil, fmt.Errorf("fetchAllUsersWithOrders: %w", err)
	}
	defer rows.Close()

	var items []*models.User
	var current *models.User

	for rows.Next() {
		var p models.User

		var child_ID int64
		var child_UserID int64
		var child_Amount float64

		scanArgs := []any{
			&p.ID, &p.Name, &p.Email, &p.CreatedAt,
			scanNullable(&child_ID),
			scanNullable(&child_UserID),
			scanNullable(&child_Amount),
		}

		if err := rows.Scan(scanArgs...); err != nil {
			return nil, fmt.Errorf("fetchAllUsersWithOrders: scanning row: %w", err)
		}

		if current == nil || current.ID != p.ID {
			items = append(items, &p)
			current = items[len(items)-1]
		}

		if !isZero(child_ID) {
			child := models.Order{
				ID:     child_ID,
				UserID: child_UserID,
				Amount: child_Amount,
			}
			current.Orders = append(current.Orders, child)
		}
	}

	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("fetchAllUsersWithOrders: iterating rows: %w", err)
	}

	return items, nil
}

// UpdateUser updates an existing User record in users.
func UpdateUser(ctx context.Context, db DBTX, m *models.User) error {
	if db == nil {
		return errors.New("updateUser: db is nil")
	}
	if m == nil {
		return errors.New("updateUser: m is nil")
	}

	const query = `
		UPDATE users
		SET name = $1, email = $2, created_at = $3
		WHERE id = $4
	`

	res, err := db.ExecContext(ctx, query, &m.Name, &m.Email, &m.CreatedAt, m.ID)
	if err != nil {
		return fmt.Errorf("updateUser(%v): %w", m.ID, err)
	}

	n, err := res.RowsAffected()
	if err != nil {
		return nil
	}
	if n == 0 {
		return fmt.Errorf("updateUser(%v): %w", m.ID, sql.ErrNoRows)
	}
	return nil
}

// DeleteUser deletes the User record identified by id from users.
func DeleteUser(ctx context.Context, db DBTX, id int64) error {
	if db == nil {
		return errors.New("deleteUser: db is nil")
	}

	const query = `DELETE FROM users WHERE id = $1`

	res, err := db.ExecContext(ctx, query, id)
	if err != nil {
		return fmt.Errorf("deleteUser(%v): %w", id, err)
	}

	n, err := res.RowsAffected()
	if err != nil {
		return nil
	}
	if n == 0 {
		return fmt.Errorf("deleteUser(%v): %w", id, sql.ErrNoRows)
	}
	return nil
}
